/* gs/gs_parallel_overlay.cpp: the RmlUi overlay pass of the paraLLEl-GS shim.
 *
 * Part of libicorecomp-parallel-gs; see gs_parallel_lib.cpp for the library
 * overview and gs_parallel_impl.h for the RtPgs type. Holds the overlay
 * textures, the retained overlay frame set through rt_pgs_overlay_set_frame,
 * the overlay draw pass with its pipeline state, and rt_pgs_present_ui's
 * windowed implementation.
 */
#include "gs_parallel_impl.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <mutex>

#ifdef ICORECOMP_PGS_SDL

namespace {

/* Overlay pass SPIR-V: kOverlayVertSpv / kOverlayFragSpv, generated by
 * tools/gen_overlay_spirv.sh from gs/overlay.vert and gs/overlay.frag (ours,
 * MIT, not ROM-derived) because GRANITE_SHIPPING builds carry no runtime
 * shader compiler. Precedent: paraLLEl-GS's own shaders are precompiled the
 * same way via slangmosh (gs/shaders/slangmosh.hpp). */
#include "overlay_shaders.inc"

/* mvp for one overlay draw command: an orthographic projection of the
 * backbuffer, with geometry authored in RtPgsOverlayFrame::surface_width/
 * height pixel space scaled to the backbuffer's actual size, and the
 * command's translate plus (when RT_PGS_OVERLAY_TRANSFORM is set) its
 * transform applied first, both still in surface pixel space. Column-major,
 * column vectors, matching overlay.vert's `mat4 mvp` push constant and
 * RtPgsOverlayCmd::transform's documented layout.
 *
 * No y-flip: Vulkan's default clip space already puts NDC (-1,-1) at the
 * same top-left corner pixel (0,0) is authored at. */
void build_overlay_mvp(float out[16], const RtPgsOverlayCmd& cmd,
                       double bb_w, double bb_h, double surface_w, double surface_h) {
    float m[16];
    if (cmd.flags & RT_PGS_OVERLAY_TRANSFORM) {
        std::memcpy(m, cmd.transform, sizeof(m));
    } else {
        std::memset(m, 0, sizeof(m));
        m[0] = 1.0f; m[5] = 1.0f; m[10] = 1.0f; m[15] = 1.0f;
    }
    /* Translate: applied after the transform, still in surface pixel space
     * (column-major storage: the translation lives in column 3). */
    m[12] += cmd.translate_x;
    m[13] += cmd.translate_y;

    /* Fold "scale surface space into backbuffer space" and "project
     * backbuffer pixels to NDC" into one factor per axis: ndc = pixel /
     * backbuffer_size * 2 - 1, and pixel = surface_pixel * (backbuffer /
     * surface). The two scales multiply out algebraically, so this is
     * exactly equivalent to scaling into backbuffer space and then
     * projecting, without needing an intermediate matrix. */
    const double sx = surface_w > 0.0 ? bb_w / surface_w : 1.0;
    const double sy = surface_h > 0.0 ? bb_h / surface_h : 1.0;
    for (int c = 0; c < 4; ++c) {
        out[c * 4 + 0] = float(double(m[c * 4 + 0]) * sx * (2.0 / bb_w));
        out[c * 4 + 1] = float(double(m[c * 4 + 1]) * sy * (2.0 / bb_h));
        out[c * 4 + 2] = m[c * 4 + 2];
        out[c * 4 + 3] = m[c * 4 + 3];
    }
    /* -1 bias applies only to the translation column (column 3, the only
     * one whose row-3 element is 1 rather than 0; see the derivation this
     * loop implements). */
    out[12] -= 1.0f;
    out[13] -= 1.0f;
}

} // namespace

#endif /* ICORECOMP_PGS_SDL */

/* ---- overlay rendering (milestone 4) --------------------------------------
 *
 * texture_create/destroy and set_frame are plain Vulkan::Device operations
 * (headless or windowed, m_device points at whichever is live) and reuse
 * the m_in_frame fatal guard: texture_create allocates and submits GPU work
 * (Device::create_image with initial data stages and uploads through a
 * command buffer internally), so calling any of the three from inside
 * pump_events -- which runs during the live backend's own begin_frame --
 * would race that in-flight frame's command buffer. draw_overlay and
 * present_ui_windowed (the actual draw) are windowed-only and live with
 * present_frame further down.
 */

void RtPgs::ensure_overlay_white() {
    if (m_overlay_white) return;
    const uint8_t white[4] = { 0xFF, 0xFF, 0xFF, 0xFF };
    Vulkan::ImageInitialData initial = {};
    initial.data = white;
    auto info = Vulkan::ImageCreateInfo::immutable_2d_image(1, 1, VK_FORMAT_R8G8B8A8_UNORM);
    m_overlay_white = m_device->create_image(info, &initial);
    if (!m_overlay_white) {
        fatalf("paraLLEl-GS: failed to create the 1x1 white overlay fallback image");
    }
}

uint32_t RtPgs::overlay_texture_create(const uint8_t* rgba8, uint32_t width, uint32_t height) {
    if (m_in_frame) {
        fatalf("paraLLEl-GS: rt_pgs_overlay_texture_create called while a frame is in flight;"
               " overlay textures must be created between frames");
    }
    if (!rgba8 || !width || !height) {
        warnf("paraLLEl-GS: rt_pgs_overlay_texture_create: invalid arguments (rgba8=%p, %ux%u);"
              " no texture created", (const void*)rgba8, width, height);
        return 0;
    }
    ensure_overlay_white();

    Vulkan::ImageInitialData initial = {};
    initial.data = rgba8;
    auto info = Vulkan::ImageCreateInfo::immutable_2d_image(width, height, VK_FORMAT_R8G8B8A8_UNORM);
    Vulkan::ImageHandle img = m_device->create_image(info, &initial);
    if (!img) {
        warnf("paraLLEl-GS: rt_pgs_overlay_texture_create failed (%ux%u); the device would not"
              " create the image", width, height);
        return 0;
    }
    const uint32_t id = m_overlay_next_texture++;
    m_overlay_textures.emplace(id, std::move(img));
    return id;
}

void RtPgs::overlay_texture_destroy(uint32_t texture) {
    if (m_in_frame) {
        fatalf("paraLLEl-GS: rt_pgs_overlay_texture_destroy called while a frame is in flight;"
               " overlay textures must be destroyed between frames");
    }
    if (!texture) return;
    /* Erasing an id still referenced by the retained overlay frame is the
     * caller's bug (the ABI doc says so); the library does not scan
     * m_overlay_cmds for it, draw_overlay would fail the lookup. */
    if (m_overlay_textures.erase(texture) == 0) {
        warnf("paraLLEl-GS: rt_pgs_overlay_texture_destroy: unknown texture id %u; nothing"
              " destroyed", texture);
    }
}

void RtPgs::overlay_set_frame(const RtPgsOverlayFrame* frame) {
    if (m_in_frame) {
        fatalf("paraLLEl-GS: rt_pgs_overlay_set_frame called while a frame is in flight;"
               " overlay frames must be set between frames");
    }
    if (!frame || frame->cmd_count == 0) {
        m_overlay_vertices.clear();
        m_overlay_indices.clear();
        m_overlay_cmds.clear();
        m_overlay_surface_width = 0;
        m_overlay_surface_height = 0;
        return;
    }
    if ((frame->vertex_count && !frame->vertices) ||
        (frame->index_count && !frame->indices) ||
        !frame->cmds) {
        warnf("paraLLEl-GS: rt_pgs_overlay_set_frame rejected: null array pointer with nonzero"
              " count; the previous overlay frame keeps drawing");
        return;
    }

    /* Validate whole, before touching retained state: a malformed frame
     * keeps the previous one drawing rather than risk out-of-bounds
     * geometry (loud failure beats silent wrongness). */
    for (uint32_t i = 0; i < frame->cmd_count; ++i) {
        const RtPgsOverlayCmd& c = frame->cmds[i];
        if (c.texture != 0 && m_overlay_textures.find(c.texture) == m_overlay_textures.end()) {
            warnf("paraLLEl-GS: rt_pgs_overlay_set_frame rejected: cmd %u references unknown"
                  " texture %u; the previous overlay frame keeps drawing", i, c.texture);
            return;
        }
        const uint64_t index_end = uint64_t(c.index_offset) + c.index_count;
        if (index_end > frame->index_count) {
            warnf("paraLLEl-GS: rt_pgs_overlay_set_frame rejected: cmd %u index range [%u, %llu)"
                  " exceeds %u indices; the previous overlay frame keeps drawing",
                  i, c.index_offset, (unsigned long long)index_end, frame->index_count);
            return;
        }
        for (uint32_t k = c.index_offset; k < c.index_offset + c.index_count; ++k) {
            const int64_t v = int64_t(frame->indices[k]) + c.vertex_offset;
            if (v < 0 || uint64_t(v) >= frame->vertex_count) {
                warnf("paraLLEl-GS: rt_pgs_overlay_set_frame rejected: cmd %u index %u"
                      " (vertex_offset %d) is out of range [0, %u); the previous overlay"
                      " frame keeps drawing",
                      i, frame->indices[k], c.vertex_offset, frame->vertex_count);
                return;
            }
        }
    }

    m_overlay_vertices.assign(frame->vertices, frame->vertices + frame->vertex_count);
    m_overlay_indices.assign(frame->indices, frame->indices + frame->index_count);
    m_overlay_cmds.assign(frame->cmds, frame->cmds + frame->cmd_count);
    m_overlay_surface_width = frame->surface_width;
    m_overlay_surface_height = frame->surface_height;
}

uint32_t RtPgs::present_ui() {
    if (m_in_frame) {
        fatalf("paraLLEl-GS: rt_pgs_present_ui called while a frame is in flight;"
               " it may not be called reentrantly (e.g. from pump_events)");
    }
#ifdef ICORECOMP_PGS_SDL
    if (m_wsi_active) return present_ui_windowed();
#endif
    if (!m_overlay_ui_headless_logged) {
        m_overlay_ui_headless_logged = true;
        warnf("paraLLEl-GS: rt_pgs_present_ui ignored (headless, no window); the overlay frame"
              " is dropped");
    }
    return 0;
}

#ifdef ICORECOMP_PGS_SDL

/* Draws m_overlay_cmds into the render pass cmd already has open (either
 * present_frame's on top of the scanout blit, or present_ui_windowed's on
 * top of its own clear). Callers own the barriers and the render pass;
 * this only sets pipeline state, uploads the retained geometry, and issues
 * the draws. Caller must not call this with an empty overlay frame if it
 * matters (drawing zero cmds is harmless, but present_frame skips the whole
 * pass instead so an idle overlay costs nothing). */
void RtPgs::draw_overlay(Vulkan::CommandBuffer& cmd) {
    ensure_overlay_white();
    if (!m_overlay_program) {
        /* This build has GRANITE_VULKAN_SPIRV_CROSS off (see gs_pgs_context.h
         * neighbors and CMakeCache.txt: no runtime reflection library is
         * linked in, the same reason paraLLEl-GS ships slangmosh's
         * precomputed reflection_bank for ITS shaders), so request_program
         * needs the resource layout by hand instead of reflecting
         * overlay_shaders.inc at run time; an unset input_mask would build a
         * pipeline with none of these vertex attributes wired in at all
         * (CommandBuffer::for_each_bit(layout.attribute_mask, ...)), and an
         * unset push_constant_size a pipeline layout with no room for mvp.
         * Hand-computed from overlay.vert/overlay.frag's declared locations,
         * mirroring exactly what Shader::reflect_resource_layout would have
         * produced (see shader.cpp) for these two small, fixed shaders. */
        Vulkan::ResourceLayout vertex_layout = {};
        vertex_layout.input_mask = 0x7;       /* locations 0,1,2: pos, uv, color */
        vertex_layout.output_mask = 0x3;      /* locations 0,1: v_uv, v_color */
        vertex_layout.push_constant_size = sizeof(float) * 16; /* mat4 mvp */

        Vulkan::ResourceLayout fragment_layout = {};
        fragment_layout.input_mask = 0x3;     /* locations 0,1: v_uv, v_color */
        fragment_layout.output_mask = 0x1;    /* location 0: out_color */
        fragment_layout.sets[0].sampled_image_mask = 0x1; /* binding 0: u_tex */
        fragment_layout.sets[0].fp_mask = 0x1;
        fragment_layout.sets[0].meta[0].array_size = 1;

        m_overlay_program = m_device->request_program(
            kOverlayVertSpv, sizeof(kOverlayVertSpv),
            kOverlayFragSpv, sizeof(kOverlayFragSpv),
            &vertex_layout, &fragment_layout);
        if (!m_overlay_program) {
            fatalf("paraLLEl-GS: overlay shader program failed to compile"
                   " (overlay_shaders.inc); see the Vulkan validation log above");
        }
    }
    if (m_overlay_cmds.empty()) return;

    auto& backbuffer = m_device->get_swapchain_view().get_image();
    const double bb_w = double(backbuffer.get_width());
    const double bb_h = double(backbuffer.get_height());
    const double surface_w = m_overlay_surface_width ? double(m_overlay_surface_width) : bb_w;
    const double surface_h = m_overlay_surface_height ? double(m_overlay_surface_height) : bb_h;
    const double scale_x = surface_w > 0.0 ? bb_w / surface_w : 1.0;
    const double scale_y = surface_h > 0.0 ? bb_h / surface_h : 1.0;

    cmd.set_program(m_overlay_program);
    /* Granite's CommandBuffer constructor calls set_opaque_state() and then
     * memsets the entire static state to zero on the very next line
     * (Granite/vulkan/command_buffer.cpp, CommandBuffer::CommandBuffer), so a
     * freshly requested command buffer carries an all-zero pipeline state, not
     * the opaque preset: write_mask 0, which build_graphics_pipeline turns
     * into colorWriteMask 0 (every channel masked off, nothing reaches the
     * attachment), and topology 0, which is VK_PRIMITIVE_TOPOLOGY_POINT_LIST
     * rather than a triangle list. A pass that sets no base state draws
     * nothing at all. Every Granite pass picks one first; paraLLEl-GS's own
     * scanout blit calls set_opaque_sprite_state() right after
     * begin_render_pass (gs/gs_renderer.cpp). set_opaque_state supplies the
     * triangle-list topology and full write mask this pass needs; the depth,
     * cull and blend calls below override the parts a 2D overlay does not
     * want. */
    cmd.set_opaque_state();
    cmd.set_depth_test(false, false);
    /* Overlay geometry is authored in a y-down pixel space and projected
     * without a flip, so its triangles are clockwise in framebuffer terms
     * and the opaque preset's back-face culling would drop every one of
     * them. A 2D overlay has no back faces: draw both windings. */
    cmd.set_cull_mode(VK_CULL_MODE_NONE);
    cmd.set_blend_enable(true);
    cmd.set_blend_op(VK_BLEND_OP_ADD);

    cmd.set_vertex_attrib(0, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(RtPgsOverlayVertex, x));
    cmd.set_vertex_attrib(1, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(RtPgsOverlayVertex, u));
    cmd.set_vertex_attrib(2, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(RtPgsOverlayVertex, rgba));

    const VkDeviceSize vtx_size = VkDeviceSize(m_overlay_vertices.size()) * sizeof(RtPgsOverlayVertex);
    void* vtx = cmd.allocate_vertex_data(0, vtx_size, sizeof(RtPgsOverlayVertex));
    std::memcpy(vtx, m_overlay_vertices.data(), size_t(vtx_size));

    const VkDeviceSize idx_size = VkDeviceSize(m_overlay_indices.size()) * sizeof(uint32_t);
    void* idx = cmd.allocate_index_data(idx_size, VK_INDEX_TYPE_UINT32);
    std::memcpy(idx, m_overlay_indices.data(), size_t(idx_size));

    if (!m_overlay_diag_logged) {
        /* Once per process: what the first drawn overlay frame looked like
         * at the point it was handed to Vulkan. Cheap insurance for a pass
         * that can only be judged on a GPU this build machine does not
         * have. */
        m_overlay_diag_logged = true;
        const RtPgsOverlayCmd& c0 = m_overlay_cmds[0];
        const RtPgsOverlayVertex& v0 = m_overlay_vertices[size_t(c0.vertex_offset) +
            size_t(m_overlay_indices[c0.index_offset])];
        float mvp0[16];
        build_overlay_mvp(mvp0, c0, bb_w, bb_h, surface_w, surface_h);
        logf("paraLLEl-GS: overlay: first draw: %zu cmds, %zu vertices, backbuffer %ux%u, surface %ux%u;"
             " cmd0 tex %u idx [%u +%u) voff %d flags 0x%x translate (%.1f, %.1f) scissor (%d, %d, %d, %d);"
             " v0 (%.1f, %.1f) uv (%.3f, %.3f) rgba 0x%08x; mvp col0 (%g, %g) col1 (%g, %g) col3 (%g, %g, %g, %g)",
             m_overlay_cmds.size(), m_overlay_vertices.size(),
             unsigned(bb_w), unsigned(bb_h), unsigned(surface_w), unsigned(surface_h),
             c0.texture, c0.index_offset, c0.index_count, c0.vertex_offset, c0.flags,
             double(c0.translate_x), double(c0.translate_y),
             c0.scissor_x, c0.scissor_y, c0.scissor_w, c0.scissor_h,
             double(v0.x), double(v0.y), double(v0.u), double(v0.v), v0.rgba,
             double(mvp0[0]), double(mvp0[1]), double(mvp0[4]), double(mvp0[5]),
             double(mvp0[12]), double(mvp0[13]), double(mvp0[14]), double(mvp0[15]));
    }

    for (const RtPgsOverlayCmd& c : m_overlay_cmds) {
        /* Per command, per gs_parallel_api.h: straight alpha multiplies the
         * source by SRC_ALPHA here, premultiplied alpha (what RmlUi hands us)
         * has that factor already folded into the color and takes ONE. Alpha
         * uses ONE/ONE_MINUS_SRC_ALPHA either way so overlapping translucent
         * draws accumulate coverage correctly. */
        const bool premultiplied = (c.flags & RT_PGS_OVERLAY_PREMULTIPLIED) != 0;
        cmd.set_blend_factors(premultiplied ? VK_BLEND_FACTOR_ONE : VK_BLEND_FACTOR_SRC_ALPHA,
                              VK_BLEND_FACTOR_ONE,
                              VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA, VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA);

        float mvp[16];
        build_overlay_mvp(mvp, c, bb_w, bb_h, surface_w, surface_h);
        cmd.push_constants(mvp, 0, sizeof(mvp));

        const Vulkan::ImageView* view = &m_overlay_white->get_view();
        if (c.texture != 0) {
            auto it = m_overlay_textures.find(c.texture);
            if (it != m_overlay_textures.end()) {
                view = &it->second->get_view();
            } else if (!m_overlay_missing_tex_logged) {
                /* set_frame already rejected an unknown id whole; a texture
                 * destroyed after the frame was set is a caller bug
                 * (documented on rt_pgs_overlay_texture_destroy). Falling
                 * back to white rather than reading a dangling ImageView is
                 * still a different picture from the one asked for, so it
                 * says so. Once per run: this runs per command per frame. */
                m_overlay_missing_tex_logged = true;
                warnf("paraLLEl-GS: overlay: texture %u was destroyed while the retained frame"
                      " still referenced it; that draw uses the white fallback", c.texture);
            }
        }
        cmd.set_texture(0, 0, *view, Vulkan::StockSampler::LinearClamp);

        VkRect2D scissor;
        if (c.flags & RT_PGS_OVERLAY_SCISSOR) {
            int32_t x0 = int32_t(std::lround(double(c.scissor_x) * scale_x));
            int32_t y0 = int32_t(std::lround(double(c.scissor_y) * scale_y));
            int32_t x1 = int32_t(std::lround(double(c.scissor_x + c.scissor_w) * scale_x));
            int32_t y1 = int32_t(std::lround(double(c.scissor_y + c.scissor_h) * scale_y));
            x0 = std::max(x0, 0);
            y0 = std::max(y0, 0);
            x1 = std::min(x1, int32_t(bb_w));
            y1 = std::min(y1, int32_t(bb_h));
            scissor.offset = { x0, y0 };
            scissor.extent = { uint32_t(std::max(0, x1 - x0)), uint32_t(std::max(0, y1 - y0)) };
        } else {
            scissor.offset = { 0, 0 };
            scissor.extent = { uint32_t(bb_w), uint32_t(bb_h) };
        }
        cmd.set_scissor(scissor);

        cmd.draw_indexed(c.index_count, 1, c.index_offset, c.vertex_offset, 0);
    }
}

/* rt_pgs_present_ui's windowed implementation: same begin_frame/end_frame
 * skeleton as present_frame, minus the scanout blit (there is no guest
 * scanout in this path) -- clear to a near-black background, draw the
 * overlay, present. Mirrors present()'s window-closed bookkeeping inline
 * since there is no scanout-producing caller to do it afterwards. */
uint32_t RtPgs::present_ui_windowed() {
    uint32_t flags = 0;
    /* The launcher can present for many fields without present_frame running
     * at all, so this path drains a pending screenshot copy too; otherwise a
     * capture taken on the last guest field before a hand-off would sit
     * unread with its staging buffer held. */
    drain_screenshots();
    m_platform->sync_from_host();
    if (const char* why = m_platform->not_presentable_reason()) {
        /* Same reasoning as present_frame: begin_frame() would park the
         * calling thread while minimized, so poll here instead. The overlay
         * frame for this field is dropped, which is what the shared skip
         * accounting counts. */
        m_platform->poll_input();
        note_present_skipped(why);
    } else {
        m_in_frame = true;
        if (!m_wsi->begin_frame()) {
            m_in_frame = false;
            note_begin_frame_failed("this overlay frame (rt_pgs_present_ui)");
        } else {
            auto& device = m_wsi->get_device();
            auto cmd = device.request_command_buffer();

            cmd->swapchain_touch_in_stages(VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT);

            /* No barriers around the pass. For a swapchain attachment the
             * render pass declares its own layouts and we do not get to pick
             * them (Granite vulkan/render_pass.cpp lines 238-248): this pass
             * clears, so initialLayout is UNDEFINED, and finalLayout is the
             * image's swapchain layout, which the WSI records as
             * VK_IMAGE_LAYOUT_PRESENT_SRC_KHR (Device::init_swapchain's
             * default layout argument, device.hpp). A pre-pass
             * UNDEFINED-to-COLOR_ATTACHMENT_OPTIMAL barrier is therefore
             * redundant, and a post-pass barrier out of
             * COLOR_ATTACHMENT_OPTIMAL names a layout the image was never
             * left in. The pass alone takes it from UNDEFINED to
             * PRESENT_SRC_KHR. */
            Vulkan::RenderPassInfo rp = device.get_swapchain_render_pass(Vulkan::SwapchainRenderPass::ColorOnly);
            rp.clear_attachments = 1u << 0;
            /* Opaque near-black, not full black: distinguishes "launcher up,
             * no scanout" from a dead/hung window at a glance. */
            rp.clear_color[0].float32[0] = 0.06f;
            rp.clear_color[0].float32[1] = 0.06f;
            rp.clear_color[0].float32[2] = 0.06f;
            rp.clear_color[0].float32[3] = 1.0f;
            rp.load_attachments = 0;
            rp.store_attachments = 1u << 0;
            cmd->begin_render_pass(rp);
            draw_overlay(*cmd);
            cmd->end_render_pass();
            device.submit(cmd);

            if (!m_wsi->end_frame()) note_end_frame_failed("this overlay frame (rt_pgs_present_ui)");
            m_in_frame = false;
            note_present_resumed();
            flags |= RT_PGS_VSYNC_PRESENTED;

            /* No scanout was blitted, so the present rectangle is empty and
             * a reader is right to treat it as "no picture". The backbuffer
             * size is knowable here, though, and reporting it as zero would
             * be a worse answer than reporting it: ParallelBackend::present_ui
             * republishes these six values, and the launcher is a window with
             * a size like any other. */
            auto& bb = device.get_swapchain_view().get_image();
            std::lock_guard<std::mutex> lk(m_present_rect_mu);
            m_present_x = 0;
            m_present_y = 0;
            m_present_w = 0;
            m_present_h = 0;
            m_present_bb_w = int32_t(bb.get_width());
            m_present_bb_h = int32_t(bb.get_height());
        }
    }

    /* Same window-closed bookkeeping present() does around present_frame,
     * inlined here since rt_pgs_present_ui has no separate wrapper. */
    if (!m_platform->alive(*m_wsi)) note_window_closed("the overlay present (rt_pgs_present_ui)");
    if (m_window_closed.load(std::memory_order_acquire)) flags |= RT_PGS_VSYNC_WINDOW_CLOSED;
    return flags;
}

#endif /* ICORECOMP_PGS_SDL */
