/* tools/gs_gen_dump/main.cpp: icorecomp-gs-gen-dump.
 *
 * Writes synthetic GS streams in the raw format gs/gs_dumpwriter.cpp records,
 * so the native renderer, the dump parser and the replay tool can all be
 * exercised without a disc and without a capture from the running game.
 *
 * Ours (MIT). Nothing here is ROM-derived: the pixel content is generated by
 * this file, and the register values are address facts recorded in this
 * repository's own comments (gs/gs_parallel_scanout.cpp's placement note and
 * hw/gspriv.cpp's SetGsCrt), not data taken off the disc. The generator is
 * what is committed; the .gs files it writes are not.
 *
 * The cases, and what each one is for:
 *
 *   upload-<format>.gs  a HOST to LOCAL upload of a generated gradient in
 *                       one pixel format, then the NTSC gameplay display
 *                       setup reading it back out. One per format the
 *                       swizzle covers, so a format whose addressing is
 *                       wrong shows as a scrambled picture in exactly the
 *                       file named after it.
 *   ntsc-512x448.gs     the gameplay display setup: DW+1 2560, DH+1 448,
 *                       DX 636, DY 50, MAGH 4, so 512 pixels by 224 lines
 *                       per field, which is the mode area exactly.
 *   movie-720x480.gs    the attract movie's setup: DW+1 2880, DH+1 480,
 *                       MAGH 3 from the same corner, with DISPFB DBX 36 and
 *                       DBY 12. This is the case display.raster changes: crt
 *                       crops the right 80 columns and the bottom 16 lines
 *                       per field, window grows the frame and reads from the
 *                       buffer's origin.
 *   local-to-local.gs   an upload followed by a LOCAL to LOCAL copy into the
 *                       displayed buffer, including one copy with TRXPOS DIR
 *                       reversed over an overlapping rectangle.
 *   two-circuit.gs      both display circuits enabled over the same area with
 *                       different buffers, so PMODE's merge is exercised.
 *
 * Milestone (b) adds the drawing cases. Every one of them clears the frame
 * buffer with a full-screen sprite, draws its geometry, and then programs the
 * same NTSC gameplay display setup, so the replay tool screenshots the result
 * without any other case's state leaking in:
 *
 *   draw-flat-tri.gs    two flat triangles, one of them wound the other way
 *                       round, so the winding normalisation shows as no
 *                       difference at all.
 *   draw-gouraud-tri.gs one Gouraud triangle with a primary at each vertex.
 *   draw-sprites.gs     a row of sprites stepped a sixteenth of a pixel at a
 *                       time, so the sample rule's exclusive right edge is
 *                       the only thing that decides their widths.
 *   draw-strip.gs       a triangle strip, alternating colours per vertex.
 *   draw-fan.gs         a triangle fan around one centre.
 *   draw-depth.gs       a cleared Z buffer, then two overlapping triangles
 *                       drawn far one first and near one first, so the depth
 *                       test and not the submission order has to decide.
 *   draw-fbmsk.gs       one sprite over another with FBMSK protecting the
 *                       green byte.
 *
 * Milestone (c) adds the texture cases. Each uploads its own texture into a
 * page clear of the frame and Z buffers and draws with TME set:
 *
 *   draw-texture-<format>.gs
 *                       a 64 by 64 texture of one format, magnified with
 *                       nearest filtering, one file per colour and palette
 *                       format the sampler reads.
 *   draw-texture-csm2.gs
 *                       the same 8-bit texture through a CSM2 palette, which
 *                       is a line of 16-bit entries at TEXCLUT's offset.
 *   draw-texture-bilinear.gs
 *                       an 8 by 8 texture magnified forty times, nearest on
 *                       the left and linear on the right.
 *   draw-texture-clamp.gs
 *                       four squares of one texture at four times its size,
 *                       one per WMS/WMT mode.
 *   draw-texture-mip.gs one triangle whose Q runs from 1 to 1/8, so the LOD
 *                       runs from 0 to 3 and each level's own colour is a
 *                       band down the picture.
 *   draw-texture-highlight2.gs
 *                       the four TFX functions side by side.
 *   draw-texture-feedback.gs
 *                       a sprite that reads the frame buffer pages it is
 *                       drawing into, which is what the page tracker breaks
 *                       the batch for.
 *
 * Milestone (d) adds the cases for the pixel pipeline's remaining switches,
 * and (f) one for render scale:
 *
 *   draw-aa1-tri.gs     the same triangle twice, without AA1 on the left and
 *                       with it on the right, over a flat background and with
 *                       the blend the coverage alpha feeds. The left edges
 *                       are the comparison.
 *   draw-lines.gs       lines at a fan of slopes through both major axes,
 *                       one line whose endpoints share a pixel, and the same
 *                       fan again with AA1.
 *   draw-scanmsk.gs     three bands of one sprite each, at SCANMSK 0, 2 and
 *                       3, so the even and odd row rules are side by side.
 *   draw-fbz-alias.gs   a frame buffer and a Z buffer at the same base, so
 *                       the pixels where a colour and a depth land on the
 *                       same word show what the write order does.
 *   draw-scale-texture.gs
 *                       a textured triangle with slanted edges over a
 *                       gradient, which is the case to compare between
 *                       display.render_scale 1 and 16.
 *
 * Usage: icorecomp-gs-gen-dump <output-directory>
 */
#include "../../src/runtime/gs/render/gs_swizzle.h"
#include "../../src/runtime/gs/render/gs_texture.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

namespace {

/* ---- the raw stream ------------------------------------------------------- */

class DumpWriter {
public:
    explicit DumpWriter(const std::string& path) {
        m_file = std::fopen(path.c_str(), "wb");
        m_path = path;
    }
    ~DumpWriter() {
        if (m_file) std::fclose(m_file);
    }
    bool ok() const { return m_file != nullptr; }
    const std::string& path() const { return m_path; }

    void priv(uint32_t offset, uint64_t value) {
        offset &= 0x1FFF;
        if (offset < 0x1000) m_lo[(offset >> 4) * 2] = value;
        else m_hi[((offset - 0x1000) >> 4) * 2] = value;
    }

    void gif(int path, const std::vector<uint8_t>& bytes) {
        const uint8_t type = 0;
        const uint8_t p = (uint8_t)path;
        const uint32_t size = (uint32_t)bytes.size();
        std::fwrite(&type, 1, 1, m_file);
        std::fwrite(&p, 1, 1, m_file);
        std::fwrite(&size, 4, 1, m_file);
        std::fwrite(bytes.data(), 1, size, m_file);
    }

    /* A privileged snapshot always precedes a vsync, which is what the dump
     * writer does and what the parser expects. */
    void vsync(uint8_t field) {
        const uint8_t snap = 3;
        std::fwrite(&snap, 1, 1, m_file);
        std::fwrite(m_lo, sizeof(uint64_t), 0x200, m_file);
        std::fwrite(m_hi, sizeof(uint64_t), 0x200, m_file);
        const uint8_t type = 1;
        std::fwrite(&type, 1, 1, m_file);
        std::fwrite(&field, 1, 1, m_file);
    }

private:
    FILE* m_file = nullptr;
    std::string m_path;
    uint64_t m_lo[0x200] = {};
    uint64_t m_hi[0x200] = {};
};

/* ---- GIF packet building -------------------------------------------------- */

struct Packet {
    std::vector<uint8_t> bytes;

    void qword(uint64_t lo, uint64_t hi) {
        const size_t at = bytes.size();
        bytes.resize(at + 16);
        std::memcpy(bytes.data() + at, &lo, 8);
        std::memcpy(bytes.data() + at + 8, &hi, 8);
    }
    void tag(uint32_t nloop, bool eop, uint32_t flg, uint32_t nreg, uint64_t regs) {
        qword((uint64_t)(nloop & 0x7FFF)
              | ((uint64_t)(eop ? 1 : 0) << 15)
              | ((uint64_t)(flg & 3) << 58)
              | ((uint64_t)(nreg & 15) << 60), regs);
    }
    /* One A+D block: PACKED, one register per loop, REGS[0] = 0xE. */
    void registers(const std::vector<std::pair<uint32_t, uint64_t>>& regs, bool eop) {
        tag((uint32_t)regs.size(), eop, 0, 1, 0xEull);
        for (const auto& r : regs) qword(r.second, r.first);
    }
    void image(const std::vector<uint8_t>& payload, bool eop) {
        std::vector<uint8_t> padded = payload;
        padded.resize((padded.size() + 15) & ~size_t(15), 0);
        tag((uint32_t)(padded.size() / 16), eop, 2, 1, 0);
        bytes.insert(bytes.end(), padded.begin(), padded.end());
    }
};

/* ---- register encodings, from the manual's diagrams ----------------------- */

uint64_t bitbltbuf(uint32_t sbp, uint32_t sbw, uint32_t spsm,
                   uint32_t dbp, uint32_t dbw, uint32_t dpsm) {
    return (uint64_t)(sbp & 0x3FFF) | ((uint64_t)(sbw & 0x3F) << 16)
         | ((uint64_t)(spsm & 0x3F) << 24) | ((uint64_t)(dbp & 0x3FFF) << 32)
         | ((uint64_t)(dbw & 0x3F) << 48) | ((uint64_t)(dpsm & 0x3F) << 56);
}

uint64_t trxpos(uint32_t ssax, uint32_t ssay, uint32_t dsax, uint32_t dsay, uint32_t dir) {
    return (uint64_t)(ssax & 0x7FF) | ((uint64_t)(ssay & 0x7FF) << 16)
         | ((uint64_t)(dsax & 0x7FF) << 32) | ((uint64_t)(dsay & 0x7FF) << 48)
         | ((uint64_t)(dir & 3) << 59);
}

uint64_t trxreg(uint32_t w, uint32_t h) {
    return (uint64_t)(w & 0xFFF) | ((uint64_t)(h & 0xFFF) << 32);
}

uint64_t dispfb(uint32_t fbp, uint32_t fbw, uint32_t psm, uint32_t dbx, uint32_t dby) {
    return (uint64_t)(fbp & 0x1FF) | ((uint64_t)(fbw & 0x3F) << 9)
         | ((uint64_t)(psm & 0x1F) << 15) | ((uint64_t)(dbx & 0x7FF) << 32)
         | ((uint64_t)(dby & 0x7FF) << 43);
}

uint64_t display(uint32_t dx, uint32_t dy, uint32_t magh, uint32_t magv,
                 uint32_t dw, uint32_t dh) {
    return (uint64_t)(dx & 0xFFF) | ((uint64_t)(dy & 0x7FF) << 12)
         | ((uint64_t)(magh & 0xF) << 23) | ((uint64_t)(magv & 3) << 27)
         | ((uint64_t)(dw & 0xFFF) << 32) | ((uint64_t)(dh & 0x7FF) << 44);
}

uint64_t pmode(uint32_t en1, uint32_t en2, uint32_t mmod, uint32_t amod,
               uint32_t slbg, uint32_t alp) {
    return (uint64_t)(en1 & 1) | ((uint64_t)(en2 & 1) << 1) | (1ull << 2) /* CRTMD */
         | ((uint64_t)(mmod & 1) << 5) | ((uint64_t)(amod & 1) << 6)
         | ((uint64_t)(slbg & 1) << 7) | ((uint64_t)(alp & 0xFF) << 8);
}

/* SMODE1 as hw/gspriv.cpp's rt_gs_program_crt writes it: CMOD 2 is NTSC,
 * LC 32 is the analog video clock. */
constexpr uint64_t kSmode1Ntsc = (2ull << 13) | (32ull << 3);
/* INT and FFMD, which is what ICO runs. */
constexpr uint64_t kSmode2Interlaced = 1ull | (1ull << 1);

/* Privileged register offsets, from src/runtime/mmio.cpp. */
enum : uint32_t {
    kPmode = 0x0000, kSmode1 = 0x0010, kSmode2 = 0x0020,
    kDispfb1 = 0x0070, kDisplay1 = 0x0080,
    kDispfb2 = 0x0090, kDisplay2 = 0x00A0, kBgcolor = 0x00E0,
};

/* General register addresses. */
enum : uint32_t { kBitbltbuf = 0x50, kTrxpos = 0x51, kTrxreg = 0x52, kTrxdir = 0x53 };
enum : uint32_t { kScanmsk = 0x22 };
enum : uint32_t {
    kPrim = 0x00, kRgbaq = 0x01, kSt = 0x02, kUv = 0x03, kXyz2 = 0x05,
    kTex0_1 = 0x06, kClamp1 = 0x08, kTex1_1 = 0x14, kTex2_1 = 0x16,
    kXyoffset1 = 0x18, kPrmodecont = 0x1A, kTexclut = 0x1C, kMiptbp1_1 = 0x34,
    kMiptbp2_1 = 0x36, kTexa = 0x3B, kTexflush = 0x3F,
    kScissor1 = 0x40, kAlpha1 = 0x42, kTest1 = 0x47, kFrame1 = 0x4C, kZbuf1 = 0x4E,
};

/* ---- drawing register encodings, from the manual's diagrams --------------- */

uint64_t prim(uint32_t type, uint32_t iip, uint32_t abe) {
    return (uint64_t)(type & 7) | ((uint64_t)(iip & 1) << 3) | ((uint64_t)(abe & 1) << 6);
}

/* PRIM with AA1, for the antialiasing case. */
uint64_t prim_aa(uint32_t type, uint32_t iip, uint32_t abe, uint32_t aa1) {
    return (uint64_t)(type & 7) | ((uint64_t)(iip & 1) << 3) | ((uint64_t)(abe & 1) << 6)
         | ((uint64_t)(aa1 & 1) << 7);
}

/* ALPHA: A 0..1, B 2..3, C 4..5, D 6..7, FIX 32..39. Cv = (A - B) * C + D,
 * with C's one at 0x80. */
uint64_t alpha_reg(uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t fix) {
    return (uint64_t)(a & 3) | ((uint64_t)(b & 3) << 2) | ((uint64_t)(c & 3) << 4)
         | ((uint64_t)(d & 3) << 6) | ((uint64_t)(fix & 0xFF) << 32);
}

/* PRIM with every attribute bit the texture cases need. prim() above is the
 * short form the untextured cases use and stays as it was. */
uint64_t prim_tex(uint32_t type, uint32_t iip, uint32_t tme, uint32_t fge, uint32_t abe,
                  uint32_t fst) {
    return (uint64_t)(type & 7) | ((uint64_t)(iip & 1) << 3) | ((uint64_t)(tme & 1) << 4)
         | ((uint64_t)(fge & 1) << 5) | ((uint64_t)(abe & 1) << 6)
         | ((uint64_t)(fst & 1) << 8);
}

/* TEX0, the manual's field order: TBP0 0..13, TBW 14..19, PSM 20..25, TW
 * 26..29, TH 30..33, TCC 34, TFX 35..36, CBP 37..50, CPSM 51..54, CSM 55,
 * CSA 56..60, CLD 61..63. */
uint64_t tex0(uint32_t tbp0, uint32_t tbw, uint32_t psm, uint32_t tw, uint32_t th,
              uint32_t tcc, uint32_t tfx, uint32_t cbp, uint32_t cpsm, uint32_t csm,
              uint32_t csa, uint32_t cld) {
    return (uint64_t)(tbp0 & 0x3FFF) | ((uint64_t)(tbw & 0x3F) << 14)
         | ((uint64_t)(psm & 0x3F) << 20) | ((uint64_t)(tw & 0xF) << 26)
         | ((uint64_t)(th & 0xF) << 30) | ((uint64_t)(tcc & 1) << 34)
         | ((uint64_t)(tfx & 3) << 35) | ((uint64_t)(cbp & 0x3FFF) << 37)
         | ((uint64_t)(cpsm & 0xF) << 51) | ((uint64_t)(csm & 1) << 55)
         | ((uint64_t)(csa & 0x1F) << 56) | ((uint64_t)(cld & 7) << 61);
}

/* TEX1: LCM 0, MXL 2..4, MMAG 5, MMIN 6..8, MTBA 9, L 19..20, K 32..43 with
 * four fractional bits. */
uint64_t tex1(uint32_t lcm, uint32_t mxl, uint32_t mmag, uint32_t mmin, uint32_t mtba,
              uint32_t l, int32_t k) {
    return (uint64_t)(lcm & 1) | ((uint64_t)(mxl & 7) << 2) | ((uint64_t)(mmag & 1) << 5)
         | ((uint64_t)(mmin & 7) << 6) | ((uint64_t)(mtba & 1) << 9)
         | ((uint64_t)(l & 3) << 19) | ((uint64_t)((uint32_t)k & 0xFFF) << 32);
}

/* CLAMP: WMS 0..1, WMT 2..3, MINU 4..13, MAXU 14..23, MINV 24..33, MAXV
 * 34..43. */
uint64_t clamp_reg(uint32_t wms, uint32_t wmt, uint32_t minu, uint32_t maxu,
                   uint32_t minv, uint32_t maxv) {
    return (uint64_t)(wms & 3) | ((uint64_t)(wmt & 3) << 2)
         | ((uint64_t)(minu & 0x3FF) << 4) | ((uint64_t)(maxu & 0x3FF) << 14)
         | ((uint64_t)(minv & 0x3FF) << 24) | ((uint64_t)(maxv & 0x3FF) << 34);
}

/* TEXA: TA0 0..7, AEM 15, TA1 32..39. */
uint64_t texa(uint32_t ta0, uint32_t aem, uint32_t ta1) {
    return (uint64_t)(ta0 & 0xFF) | ((uint64_t)(aem & 1) << 15)
         | ((uint64_t)(ta1 & 0xFF) << 32);
}

/* MIPTBP1 and MIPTBP2 share one layout: three (TBP, TBW) pairs at 20-bit
 * spacing. */
uint64_t miptbp(uint32_t tbp1, uint32_t tbw1, uint32_t tbp2, uint32_t tbw2,
                uint32_t tbp3, uint32_t tbw3) {
    return (uint64_t)(tbp1 & 0x3FFF) | ((uint64_t)(tbw1 & 0x3F) << 14)
         | ((uint64_t)(tbp2 & 0x3FFF) << 20) | ((uint64_t)(tbw2 & 0x3F) << 34)
         | ((uint64_t)(tbp3 & 0x3FFF) << 40) | ((uint64_t)(tbw3 & 0x3F) << 54);
}

/* UV, in sixteenths of a texel, 14 bits per axis. */
uint64_t uv(uint32_t u16, uint32_t v16) {
    return (uint64_t)(u16 & 0x3FFF) | ((uint64_t)(v16 & 0x3FFF) << 32);
}

/* ST, as the two float bit patterns the register carries. */
uint32_t float_bits(float f) {
    uint32_t bits;
    std::memcpy(&bits, &f, 4);
    return bits;
}

uint64_t st(float s, float t) {
    return (uint64_t)float_bits(s) | ((uint64_t)float_bits(t) << 32);
}

uint64_t rgbaq(uint32_t r, uint32_t g, uint32_t b, uint32_t a) {
    /* Q is the float 1.0 the hardware's internal register holds at reset. */
    return (uint64_t)(r & 0xFF) | ((uint64_t)(g & 0xFF) << 8)
         | ((uint64_t)(b & 0xFF) << 16) | ((uint64_t)(a & 0xFF) << 24)
         | (0x3F800000ull << 32);
}

/* The same with an explicit Q, which is what the perspective-correct texture
 * path reads: the hardware keeps Q in the RGBAQ register and S and T in ST. */
uint64_t rgbaq_q(uint32_t r, uint32_t g, uint32_t b, uint32_t a, float q) {
    return (uint64_t)(r & 0xFF) | ((uint64_t)(g & 0xFF) << 8)
         | ((uint64_t)(b & 0xFF) << 16) | ((uint64_t)(a & 0xFF) << 24)
         | ((uint64_t)float_bits(q) << 32);
}

/* X and Y in sixteenths of a pixel, which is the register's own unit. */
uint64_t xyz2(int32_t x16, int32_t y16, uint32_t z) {
    return (uint64_t)(uint32_t)(x16 & 0xFFFF) | ((uint64_t)(uint32_t)(y16 & 0xFFFF) << 16)
         | ((uint64_t)z << 32);
}

uint64_t frame(uint32_t fbp, uint32_t fbw, uint32_t psm, uint32_t fbmsk) {
    return (uint64_t)(fbp & 0x1FF) | ((uint64_t)(fbw & 0x3F) << 16)
         | ((uint64_t)(psm & 0x3F) << 24) | ((uint64_t)fbmsk << 32);
}

uint64_t zbuf(uint32_t zbp, uint32_t psm, uint32_t zmsk) {
    return (uint64_t)(zbp & 0x1FF) | ((uint64_t)(psm & 0xF) << 24)
         | ((uint64_t)(zmsk & 1) << 32);
}

uint64_t scissor(uint32_t x0, uint32_t x1, uint32_t y0, uint32_t y1) {
    return (uint64_t)(x0 & 0x7FF) | ((uint64_t)(x1 & 0x7FF) << 16)
         | ((uint64_t)(y0 & 0x7FF) << 32) | ((uint64_t)(y1 & 0x7FF) << 48);
}

uint64_t test(uint32_t ate, uint32_t atst, uint32_t aref, uint32_t afail,
              uint32_t date, uint32_t datm, uint32_t zte, uint32_t ztst) {
    return (uint64_t)(ate & 1) | ((uint64_t)(atst & 7) << 1)
         | ((uint64_t)(aref & 0xFF) << 4) | ((uint64_t)(afail & 3) << 12)
         | ((uint64_t)(date & 1) << 14) | ((uint64_t)(datm & 1) << 15)
         | ((uint64_t)(zte & 1) << 16) | ((uint64_t)(ztst & 3) << 17);
}

/* ---- generated content ---------------------------------------------------- */

struct FormatInfo {
    uint32_t psm;
    const char* name;
    uint32_t transfer_bits;
};

const FormatInfo kFormats[] = {
    { GS_PSMCT32,  "psmct32",  32 },
    { GS_PSMCT24,  "psmct24",  24 },
    { GS_PSMCT16,  "psmct16",  16 },
    { GS_PSMCT16S, "psmct16s", 16 },
    { GS_PSMT8,    "psmt8",     8 },
    { GS_PSMT4,    "psmt4",     4 },
    { GS_PSMT8H,   "psmt8h",    8 },
    { GS_PSMT4HL,  "psmt4hl",   4 },
    { GS_PSMT4HH,  "psmt4hh",   4 },
    { GS_PSMZ32,   "psmz32",   32 },
    { GS_PSMZ24,   "psmz24",   24 },
    { GS_PSMZ16,   "psmz16",   16 },
    { GS_PSMZ16S,  "psmz16s",  16 },
};

/* A gradient that is different in every channel and different at every
 * coordinate, so a swizzle that transposes or wraps shows up as a visible
 * discontinuity rather than as a plausible picture. */
uint32_t gradient(uint32_t x, uint32_t y, uint32_t bits) {
    const uint32_t r = x & 0xFF;
    const uint32_t g = y & 0xFF;
    const uint32_t b = (x + y) & 0xFF;
    switch (bits) {
        case 32: return r | (g << 8) | (b << 16) | (0x80u << 24);
        case 24: return r | (g << 8) | (b << 16);
        case 16: return ((r >> 3) & 0x1F) | (((g >> 3) & 0x1F) << 5)
                      | (((b >> 3) & 0x1F) << 10) | 0x8000u;
        case 8:  return (x * 3 + y * 5) & 0xFF;
        default: return (x + y) & 0xF;
    }
}

/* The HOST to LOCAL bit stream for one gradient rectangle: pixels packed at
 * the format's own transfer width, least significant bits first inside each
 * byte, which is the order the GIF's image data carries. */
std::vector<uint8_t> gradient_stream(uint32_t w, uint32_t h, uint32_t bits) {
    std::vector<uint8_t> out;
    uint64_t acc = 0;
    uint32_t acc_bits = 0;
    for (uint32_t y = 0; y < h; ++y) {
        for (uint32_t x = 0; x < w; ++x) {
            acc |= (uint64_t)gradient(x, y, bits) << acc_bits;
            acc_bits += bits;
            while (acc_bits >= 8) {
                out.push_back((uint8_t)(acc & 0xFF));
                acc >>= 8;
                acc_bits -= 8;
            }
        }
    }
    if (acc_bits) out.push_back((uint8_t)(acc & 0xFF));
    return out;
}

/* One host-to-local upload as a GIF packet. */
Packet upload_packet(uint32_t dbp, uint32_t dbw, uint32_t dpsm,
                     uint32_t dsax, uint32_t dsay, uint32_t w, uint32_t h,
                     uint32_t bits) {
    Packet p;
    p.registers({
        { kBitbltbuf, bitbltbuf(0, 0, 0, dbp, dbw, dpsm) },
        { kTrxpos,    trxpos(0, 0, dsax, dsay, 0) },
        { kTrxreg,    trxreg(w, h) },
        { kTrxdir,    0 },
    }, false);
    p.image(gradient_stream(w, h, bits), true);
    return p;
}

/* ---- the drawing cases ----------------------------------------------------- */

/* Defined below with the other display setups; every drawing case ends by
 * programming it so the replay tool has something to scan out. */
void program_gameplay(DumpWriter& d, uint32_t fbp, uint32_t psm);

/* Where the drawing cases render. The frame buffer is the one the gameplay
 * display setup shows, at page 64 (byte 0x80000); the Z buffer is put well
 * clear of it, at page 200, because a 512 by 448 PSMCT32 buffer covers pages
 * 64 to 175 and this generator has no reason to make them collide. */
enum : uint32_t {
    kDrawFbp = 64, kDrawFbw = 8, kDrawZbp = 200,
    kDrawW = 512, kDrawH = 448,
};

/* The state every drawing case starts from: no XYOFFSET, so a vertex is a
 * window coordinate directly; the scissor over the whole buffer; PRMODECONT
 * taking the attribute bits from PRIM; and no test of any kind. */
std::vector<std::pair<uint32_t, uint64_t>> draw_state(uint32_t fbmsk, uint32_t zmsk,
                                                      uint32_t zte, uint32_t ztst) {
    return {
        { kPrmodecont, 1 },
        { kXyoffset1,  0 },
        { kScissor1,   scissor(0, kDrawW - 1, 0, kDrawH - 1) },
        { kFrame1,     frame(kDrawFbp, kDrawFbw, GS_PSMCT32, fbmsk) },
        { kZbuf1,      zbuf(kDrawZbp, 0 /* PSMZ32 */, zmsk) },
        { kTest1,      test(0, 1, 0, 0, 0, 0, zte, ztst) },
    };
}

/* A sprite covering the whole buffer, which is how each case starts from a
 * known picture rather than from whatever the previous case left. */
void clear_packet(Packet& p, uint32_t r, uint32_t g, uint32_t b, uint32_t z) {
    p.registers({
        { kPrim,  prim(6 /* sprite */, 0, 0) },
        { kRgbaq, rgbaq(r, g, b, 0x80) },
        { kXyz2,  xyz2(0, 0, z) },
        { kXyz2,  xyz2(kDrawW * 16, kDrawH * 16, z) },
    }, false);
}

bool write_flat_triangle_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-flat-tri.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x20, 0x20, 0x28, 0);
    /* Two triangles of the same shape, submitted with opposite windings. The
     * renderer winds both the same way before rasterising, so they have to
     * come out as the same shape, one red and one green. */
    p.registers({
        { kPrim,  prim(3 /* triangle */, 0, 0) },
        { kRgbaq, rgbaq(0xE0, 0x20, 0x20, 0x80) },
        { kXyz2,  xyz2(40 * 16, 40 * 16, 0) },
        { kXyz2,  xyz2(200 * 16, 60 * 16, 0) },
        { kXyz2,  xyz2(70 * 16, 200 * 16, 0) },
        { kRgbaq, rgbaq(0x20, 0xE0, 0x40, 0x80) },
        { kXyz2,  xyz2(300 * 16, 40 * 16, 0) },
        { kXyz2,  xyz2(330 * 16, 200 * 16, 0) },
        { kXyz2,  xyz2(460 * 16, 60 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_gouraud_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-gouraud-tri.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x10, 0x10, 0x10, 0);
    /* IIP set, so each vertex carries its own colour and every pixel between
     * them is interpolated. */
    p.registers({
        { kPrim,  prim(3, 1 /* IIP */, 0) },
        { kRgbaq, rgbaq(0xFF, 0x00, 0x00, 0x80) },
        { kXyz2,  xyz2(256 * 16, 30 * 16, 0) },
        { kRgbaq, rgbaq(0x00, 0xFF, 0x00, 0x80) },
        { kXyz2,  xyz2(60 * 16, 400 * 16, 0) },
        { kRgbaq, rgbaq(0x00, 0x00, 0xFF, 0x80) },
        { kXyz2,  xyz2(452 * 16, 400 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_sprite_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-sprites.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);
    /* Sixteen sprites, each nominally 20 pixels wide, each starting one
     * sixteenth of a pixel further right than the last. Under the sample
     * rule some of them cover 20 pixels and some 21, and which ones is
     * decided entirely by where the two edges fall between sample points. A
     * renderer that rounded the corners to whole pixels would draw sixteen
     * identical bars. */
    std::vector<std::pair<uint32_t, uint64_t>> regs;
    regs.push_back({ kPrim, prim(6, 0, 0) });
    for (int i = 0; i < 16; ++i) {
        const int32_t x = 20 * 16 + i * (26 * 16) + i;
        regs.push_back({ kRgbaq, rgbaq(0x40 + (uint32_t)i * 12, 0xC0, 0x80, 0x80) });
        regs.push_back({ kXyz2, xyz2(x, 40 * 16, 0) });
        regs.push_back({ kXyz2, xyz2(x + 20 * 16, 200 * 16, 0) });
    }
    /* And one sprite a sixteenth of a pixel wide, which covers a column only
     * when a sample point happens to fall inside it. */
    for (int i = 0; i < 8; ++i) {
        regs.push_back({ kRgbaq, rgbaq(0xFF, 0xFF, 0xFF, 0x80) });
        regs.push_back({ kXyz2, xyz2(40 * 16 + i * 16 + i * 2, 240 * 16, 0) });
        regs.push_back({ kXyz2, xyz2(40 * 16 + i * 16 + i * 2 + 1, 300 * 16, 0) });
    }
    p.registers(regs, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_strip_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-strip.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x08, 0x08, 0x18, 0);
    /* A zigzag strip: eight vertices, six triangles, every one of them made
     * of the last three. Adjacent triangles share an edge, so the top-left
     * rule has to leave no seam and no doubled pixel between them. */
    std::vector<std::pair<uint32_t, uint64_t>> regs;
    regs.push_back({ kPrim, prim(4 /* triangle strip */, 1, 0) });
    for (int i = 0; i < 8; ++i) {
        const uint32_t c = (i & 1) ? 0xFF : 0x40;
        regs.push_back({ kRgbaq, rgbaq(c, 0xFF - c, 0x90, 0x80) });
        regs.push_back({ kXyz2, xyz2((40 + i * 55) * 16, ((i & 1) ? 320 : 80) * 16, 0) });
    }
    p.registers(regs, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_fan_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-fan.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x18, 0x08, 0x08, 0);
    /* A fan: the first vertex stays put and every later one makes a wedge
     * with its predecessor. A renderer that dropped the fan's first vertex
     * would draw a strip instead, which looks nothing like this. */
    std::vector<std::pair<uint32_t, uint64_t>> regs;
    regs.push_back({ kPrim, prim(5 /* triangle fan */, 1, 0) });
    regs.push_back({ kRgbaq, rgbaq(0xFF, 0xFF, 0xFF, 0x80) });
    regs.push_back({ kXyz2, xyz2(256 * 16, 224 * 16, 0) });
    /* Eight rim vertices on a regular octagon, written out as integers so
     * nothing here depends on a floating point library. */
    static const int rim[8][2] = {
        { 256, 44 }, { 383, 97 }, { 436, 224 }, { 383, 351 },
        { 256, 404 }, { 129, 351 }, { 76, 224 }, { 129, 97 },
    };
    for (int i = 0; i < 8; ++i) {
        regs.push_back({ kRgbaq, rgbaq((uint32_t)(i * 31), 0x80, (uint32_t)(255 - i * 31), 0x80) });
        regs.push_back({ kXyz2, xyz2(rim[i][0] * 16, rim[i][1] * 16, 0) });
    }
    /* Close the fan back onto the first rim vertex. */
    regs.push_back({ kRgbaq, rgbaq(0, 0x80, 0xFF, 0x80) });
    regs.push_back({ kXyz2, xyz2(rim[0][0] * 16, rim[0][1] * 16, 0) });
    p.registers(regs, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_depth_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-depth.gs");
    if (!d.ok()) return false;
    Packet p;
    /* Clear both buffers first, with the depth test off and Z writing on, so
     * the Z buffer starts at zero rather than at whatever the store held. */
    p.registers(draw_state(0, 0 /* ZMSK: write Z */, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);

    /* Then the same pair of overlapping triangles twice, on the left drawn
     * far first and on the right drawn near first. With ZTST GREATER the
     * near one has to win both times, so the two halves must look the same
     * apart from their colours. */
    p.registers({ { kTest1, test(0, 1, 0, 0, 0, 0, 1 /* ZTE */, 3 /* GREATER */) } }, false);
    p.registers({
        { kPrim,  prim(3, 0, 0) },
        { kRgbaq, rgbaq(0x30, 0x30, 0xE0, 0x80) },  /* far, blue */
        { kXyz2,  xyz2(30 * 16, 60 * 16, 0x10000000) },
        { kXyz2,  xyz2(230 * 16, 60 * 16, 0x10000000) },
        { kXyz2,  xyz2(130 * 16, 260 * 16, 0x10000000) },
        { kRgbaq, rgbaq(0xE0, 0x60, 0x30, 0x80) },  /* near, orange */
        { kXyz2,  xyz2(80 * 16, 140 * 16, 0x40000000) },
        { kXyz2,  xyz2(240 * 16, 140 * 16, 0x40000000) },
        { kXyz2,  xyz2(160 * 16, 380 * 16, 0x40000000) },

        { kRgbaq, rgbaq(0xE0, 0x60, 0x30, 0x80) },  /* near first this time */
        { kXyz2,  xyz2(340 * 16, 140 * 16, 0x40000000) },
        { kXyz2,  xyz2(500 * 16, 140 * 16, 0x40000000) },
        { kXyz2,  xyz2(420 * 16, 380 * 16, 0x40000000) },
        { kRgbaq, rgbaq(0x30, 0x30, 0xE0, 0x80) },  /* far second */
        { kXyz2,  xyz2(290 * 16, 60 * 16, 0x10000000) },
        { kXyz2,  xyz2(490 * 16, 60 * 16, 0x10000000) },
        { kXyz2,  xyz2(390 * 16, 260 * 16, 0x10000000) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_fbmsk_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-fbmsk.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);
    /* A white sprite over a green background, then the same sprite again
     * with FBMSK protecting the green byte, so the second one leaves the
     * green channel it lands on exactly as it was. */
    p.registers({
        { kPrim,  prim(6, 0, 0) },
        { kRgbaq, rgbaq(0x00, 0xC0, 0x00, 0x80) },
        { kXyz2,  xyz2(40 * 16, 40 * 16, 0) },
        { kXyz2,  xyz2(472 * 16, 400 * 16, 0) },
    }, false);
    p.registers({
        { kRgbaq, rgbaq(0xFF, 0x00, 0xFF, 0x80) },
        { kXyz2,  xyz2(80 * 16, 80 * 16, 0) },
        { kXyz2,  xyz2(240 * 16, 360 * 16, 0) },
    }, false);
    p.registers({
        { kFrame1, frame(kDrawFbp, kDrawFbw, GS_PSMCT32, 0x0000FF00u) },
        { kRgbaq,  rgbaq(0xFF, 0x00, 0xFF, 0x80) },
        { kXyz2,   xyz2(272 * 16, 80 * 16, 0) },
        { kXyz2,   xyz2(432 * 16, 360 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* ---- the texture cases -------------------------------------------------------
 *
 * Milestone (c). Every one of them uploads its own texture into a page well
 * clear of the frame and Z buffers, programs the texture registers, draws
 * with TME set, and ends with the same gameplay display setup the other
 * drawing cases use.
 *
 * Where the texture lives: page 300 for the texture, page 320 for its
 * palette, page 340 upwards for the mip levels. The frame buffer is pages 64
 * to 175 and the Z buffer starts at page 200, so nothing here collides with
 * anything the drawing cases already use, and the one case that does collide
 * does it on purpose (the feedback case below).
 */
enum : uint32_t {
    kTexBp = 300 * 32, kPalBp = 320 * 32, kMipBp = 340 * 32,
    kTexW = 64, kTexH = 64, kTexTw = 6, kTexTh = 6,
};

/* MODULATE with a fragment colour of 0x80 in every channel is the identity,
 * because alpha's one on the GS is 0x80 and the product shifts by seven. It
 * is what the cases that want to see the texel itself use. */
constexpr uint32_t kNeutral = 0x80;

void push32(std::vector<uint8_t>& out, uint32_t v) {
    out.push_back((uint8_t)(v & 0xFF));
    out.push_back((uint8_t)((v >> 8) & 0xFF));
    out.push_back((uint8_t)((v >> 16) & 0xFF));
    out.push_back((uint8_t)((v >> 24) & 0xFF));
}

void push16(std::vector<uint8_t>& out, uint32_t v) {
    out.push_back((uint8_t)(v & 0xFF));
    out.push_back((uint8_t)((v >> 8) & 0xFF));
}

/* The colour a palette entry holds. Distinct in all three channels and
 * monotonic in the index, so a palette read through the wrong arrangement
 * shows as a gradient broken into blocks rather than as a plausible
 * picture. */
uint32_t palette_colour(uint32_t index, uint32_t entries) {
    const uint32_t i = entries == 16 ? index * 17 : index;
    return (i & 0xFF) | (((255 - i) & 0xFF) << 8) | (((i * 5) & 0xFF) << 16)
         | (0x80u << 24);
}

/* The CSM1 arrangement, transcribed here and not called out of
 * gs_texture.h.
 *
 * The manual's CLUT diagram puts a 256-entry palette in the buffer as a 16
 * by 16 region, and reading an entry back means going to the slot whose
 * index has bits 3 and 4 exchanged. That sentence is written out below as a
 * bit shuffle rather than by reusing gs_clut_slot_csm1_8(), so the generator
 * and the renderer hold two transcriptions of it: a change to either that
 * the other did not get is caught at generation time by the check in
 * clut_stream_8 rather than showing up as a picture nobody compared.
 *
 * What this still does not do is settle the rule. Both sides read the same
 * sentence off the same diagram, so a misreading of the diagram is a
 * misreading in both. Only a captured 8-bit palette upload from the running
 * game settles it, and docs/GS_RENDERER.md keeps it on the inferred list for
 * that reason. */
uint32_t csm1_slot_reference(uint32_t index) {
    const uint32_t low = index & 0x07u;          /* bits 0..2, unmoved */
    const uint32_t b3 = (index >> 3) & 1u;
    const uint32_t b4 = (index >> 4) & 1u;
    const uint32_t high = index & 0xE0u;         /* bits 5..7, unmoved */
    return low | (b4 << 3) | (b3 << 4) | high;
}

/* A 256-entry CSM1 palette as the 16 by 16 image the hardware reads, which
 * is not the same as the entries in index order. The generator writes the
 * image already in that arrangement, the way a game's own palette is stored,
 * so the intended picture is the smooth gradient above. */
std::vector<uint8_t> clut_stream_8() {
    std::vector<uint8_t> out;
    for (uint32_t slot = 0; slot < 256; ++slot) {
        const uint32_t mine = csm1_slot_reference(slot);
        const uint32_t theirs = gsr::gs_clut_slot_csm1_8(slot);
        if (mine != theirs) {
            std::fprintf(stderr,
                         "gs-gen-dump: the CSM1 arrangement here and the one in "
                         "gs_texture.h disagree at index %u (%u versus %u). One of the "
                         "two transcriptions changed; settle which is right before this "
                         "case means anything.\n", slot, mine, theirs);
            std::exit(1);
        }
        push32(out, palette_colour(mine, 256));
    }
    return out;
}

/* A 16-entry palette is an 8 by 2 image and has no arrangement to undo. */
std::vector<uint8_t> clut_stream_4() {
    std::vector<uint8_t> out;
    for (uint32_t i = 0; i < 16; ++i) push32(out, palette_colour(i, 16));
    return out;
}

/* The same 256 entries as a line of 16-bit colours, which is what CSM2
 * reads. */
std::vector<uint8_t> clut_stream_csm2() {
    std::vector<uint8_t> out;
    for (uint32_t i = 0; i < 256; ++i) {
        const uint32_t c = palette_colour(i, 256);
        push16(out, ((c & 0xF8u) >> 3) | ((((c >> 8) & 0xF8u) >> 3) << 5)
                  | ((((c >> 16) & 0xF8u) >> 3) << 10) | 0x8000u);
    }
    return out;
}

std::vector<uint8_t> solid_stream(uint32_t w, uint32_t h, uint32_t colour) {
    std::vector<uint8_t> out;
    for (uint32_t i = 0; i < w * h; ++i) push32(out, colour);
    return out;
}

/* One host-to-local upload of an already built stream. */
Packet raw_upload(uint32_t dbp, uint32_t dbw, uint32_t dpsm, uint32_t w, uint32_t h,
                  const std::vector<uint8_t>& payload) {
    Packet p;
    p.registers({
        { kBitbltbuf, bitbltbuf(0, 0, 0, dbp, dbw, dpsm) },
        { kTrxpos,    trxpos(0, 0, 0, 0, 0) },
        { kTrxreg,    trxreg(w, h) },
        { kTrxdir,    0 },
    }, false);
    p.image(payload, true);
    return p;
}

/* Whether a texture format reads a palette, and how wide its index is. */
uint32_t index_bits_of(uint32_t psm) {
    if (psm == GS_PSMT8 || psm == GS_PSMT8H) return 8;
    if (psm == GS_PSMT4 || psm == GS_PSMT4HL || psm == GS_PSMT4HH) return 4;
    return 0;
}

/* draw-texture-<format>.gs: a 64 by 64 texture of that format, magnified
 * with nearest filtering over a 320 pixel square. A format whose addressing,
 * expansion or palette lookup is wrong shows as a scrambled square in the
 * file named after it. */
bool write_texture_format_case(const std::string& dir, const FormatInfo& f) {
    DumpWriter d(dir + "/draw-texture-" + f.name + ".gs");
    if (!d.ok()) return false;
    const uint32_t ibits = index_bits_of(f.psm);

    d.gif(2, upload_packet(kTexBp, 1, f.psm, 0, 0, kTexW, kTexH, f.transfer_bits).bytes);
    if (ibits == 8) {
        d.gif(2, raw_upload(kPalBp, 1, GS_PSMCT32, 16, 16, clut_stream_8()).bytes);
    } else if (ibits == 4) {
        d.gif(2, raw_upload(kPalBp, 1, GS_PSMCT32, 8, 2, clut_stream_4()).bytes);
    }

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x10, 0x10, 0x18, 0);
    p.registers({
        { kTexa,   texa(0x80, 0, 0x80) },
        { kClamp1, clamp_reg(0, 0, 0, 0, 0, 0) },
        /* LCM 1 with K 0 fixes the LOD at zero, so no mip level is selected
         * and MMAG decides the filter on its own. */
        { kTex1_1, tex1(1, 0, 0, 0, 0, 0, 0) },
        { kTex0_1, tex0(kTexBp, 1, f.psm, kTexTw, kTexTh, 1, 0 /* MODULATE */,
                        kPalBp, GS_PSMCT32, 0, 0, ibits ? 1u : 0u) },
        { kPrim,   prim_tex(6 /* sprite */, 0, 1 /* TME */, 0, 0, 1 /* FST */) },
        { kRgbaq,  rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kUv,     uv(0, 0) },
        { kXyz2,   xyz2(96 * 16, 64 * 16, 0) },
        { kUv,     uv(kTexW * 16, kTexH * 16) },
        { kXyz2,   xyz2((96 + 320) * 16, (64 + 320) * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-csm2.gs: the same 8-bit texture through a CSM2 palette, which
 * is a line of 16-bit entries at TEXCLUT's own offset rather than a 16 by 16
 * block, and takes no arrangement at all. TEXA supplies the alpha for those
 * 16-bit entries. */
bool write_texture_csm2_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-csm2.gs");
    if (!d.ok()) return false;
    d.gif(2, upload_packet(kTexBp, 1, GS_PSMT8, 0, 0, kTexW, kTexH, 8).bytes);
    d.gif(2, raw_upload(kPalBp, 4, GS_PSMCT16, 256, 1, clut_stream_csm2()).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x10, 0x10, 0x18, 0);
    p.registers({
        { kTexa,    texa(0x80, 0, 0x80) },
        { kClamp1,  clamp_reg(0, 0, 0, 0, 0, 0) },
        { kTex1_1,  tex1(1, 0, 0, 0, 0, 0, 0) },
        { kTexclut, (uint64_t)4 /* CBW */ },
        { kTex0_1,  tex0(kTexBp, 1, GS_PSMT8, kTexTw, kTexTh, 1, 0, kPalBp,
                         GS_PSMCT16, 1 /* CSM2 */, 0, 1) },
        { kPrim,    prim_tex(6, 0, 1, 0, 0, 1) },
        { kRgbaq,   rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kUv,      uv(0, 0) },
        { kXyz2,    xyz2(96 * 16, 64 * 16, 0) },
        { kUv,      uv(kTexW * 16, kTexH * 16) },
        { kXyz2,    xyz2((96 + 320) * 16, (64 + 320) * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-bilinear.gs: an 8 by 8 texture magnified forty times, nearest
 * on the left and linear on the right. The left half is eight hard squares
 * per axis; the right half is the same squares with the four-texel blend
 * between them, and its outermost half texel is where the texel centre rule
 * shows. */
bool write_texture_bilinear_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-bilinear.gs");
    if (!d.ok()) return false;
    d.gif(2, upload_packet(kTexBp, 1, GS_PSMCT32, 0, 0, 8, 8, 32).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);
    const std::vector<std::pair<uint32_t, uint64_t>> common = {
        { kTexa,   texa(0x80, 0, 0x80) },
        { kClamp1, clamp_reg(1 /* CLAMP */, 1, 0, 0, 0, 0) },
        { kTex0_1, tex0(kTexBp, 1, GS_PSMCT32, 3, 3, 1, 0, 0, 0, 0, 0, 0) },
        { kRgbaq,  rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kPrim,   prim_tex(6, 0, 1, 0, 0, 1) },
    };
    p.registers(common, false);
    p.registers({
        { kTex1_1, tex1(1, 0, 0 /* MMAG nearest */, 0, 0, 0, 0) },
        { kUv,     uv(0, 0) },
        { kXyz2,   xyz2(16 * 16, 64 * 16, 0) },
        { kUv,     uv(8 * 16, 8 * 16) },
        { kXyz2,   xyz2(240 * 16, 288 * 16, 0) },
    }, false);
    p.registers({
        { kTex1_1, tex1(1, 0, 1 /* MMAG linear */, 1, 0, 0, 0) },
        { kUv,     uv(0, 0) },
        { kXyz2,   xyz2(272 * 16, 64 * 16, 0) },
        { kUv,     uv(8 * 16, 8 * 16) },
        { kXyz2,   xyz2(496 * 16, 288 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-clamp.gs: four squares of the same texture with the same UV
 * range, four texture widths across, one per WMS/WMT mode. REPEAT tiles it
 * four times, CLAMP stretches the last row and column over the rest,
 * REGION_CLAMP does the same to a sub-rectangle, and REGION_REPEAT tiles a
 * 16 texel window because MINU is a mask and MAXU the pattern OR'd in. */
bool write_texture_clamp_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-clamp.gs");
    if (!d.ok()) return false;
    d.gif(2, upload_packet(kTexBp, 1, GS_PSMCT32, 0, 0, kTexW, kTexH, 32).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x08, 0);
    p.registers({
        { kTexa,   texa(0x80, 0, 0x80) },
        { kTex1_1, tex1(1, 0, 0, 0, 0, 0, 0) },
        { kTex0_1, tex0(kTexBp, 1, GS_PSMCT32, kTexTw, kTexTh, 1, 0, 0, 0, 0, 0, 0) },
        { kRgbaq,  rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kPrim,   prim_tex(6, 0, 1, 0, 0, 1) },
    }, false);
    struct Mode { uint64_t clamp; int32_t x, y; };
    const Mode modes[4] = {
        { clamp_reg(0, 0, 0, 0, 0, 0), 24, 24 },
        { clamp_reg(1, 1, 0, 0, 0, 0), 272, 24 },
        { clamp_reg(2, 2, 16, 47, 16, 47), 24, 240 },
        { clamp_reg(3, 3, 15, 32, 15, 32), 272, 240 },
    };
    for (int i = 0; i < 4; ++i) {
        const bool last = (i == 3);
        p.registers({
            { kClamp1, modes[i].clamp },
            { kUv,     uv(0, 0) },
            { kXyz2,   xyz2(modes[i].x * 16, modes[i].y * 16, 0) },
            { kUv,     uv(kTexW * 4 * 16, kTexH * 4 * 16) },
            { kXyz2,   xyz2((modes[i].x + 216) * 16, (modes[i].y + 184) * 16, 0) },
        }, last);
    }
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-mip.gs: one triangle whose Q runs from 1 at the top edge to
 * 1/8 at the bottom vertex, so LOD runs from 0 to 3 down the picture and the
 * mip level changes with it. Each level is a flat colour of its own, so the
 * bands are the levels: level 0 red, 1 green, 2 blue, 3 white, with
 * LINEAR_MIPMAP_LINEAR blending between them. MIPTBP1 names the three
 * levels explicitly rather than relying on MTBA's automatic packing, which
 * is the rule this renderer infers. */
bool write_texture_mip_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-mip.gs");
    if (!d.ok()) return false;
    /* Level 0 is 64 by 64 at kMipBp, and each level after it is a quarter of
     * the blocks: 64x64x4 bytes is 64 blocks, then 16, then 4. */
    const uint32_t lvl0 = kMipBp, lvl1 = kMipBp + 64, lvl2 = lvl1 + 16, lvl3 = lvl2 + 4;
    d.gif(2, raw_upload(lvl0, 1, GS_PSMCT32, 64, 64,
                        solid_stream(64, 64, 0x800000E0u)).bytes);
    d.gif(2, raw_upload(lvl1, 1, GS_PSMCT32, 32, 32,
                        solid_stream(32, 32, 0x8000E000u)).bytes);
    d.gif(2, raw_upload(lvl2, 1, GS_PSMCT32, 16, 16,
                        solid_stream(16, 16, 0x80E00000u)).bytes);
    d.gif(2, raw_upload(lvl3, 1, GS_PSMCT32, 8, 8,
                        solid_stream(8, 8, 0x80E0E0E0u)).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x08, 0x08, 0x08, 0);
    p.registers({
        { kTexa,     texa(0x80, 0, 0x80) },
        { kClamp1,   clamp_reg(1, 1, 0, 0, 0, 0) },
        { kMiptbp1_1, miptbp(lvl1, 1, lvl2, 1, lvl3, 1) },
        /* LCM 0 computes the LOD from Q, MXL 3 stops the chain at level 3,
         * MMIN 5 is LINEAR_MIPMAP_LINEAR and MMAG 1 is LINEAR. */
        { kTex1_1,   tex1(0, 3, 1, 5, 0, 0, 0) },
        { kTex0_1,   tex0(lvl0, 1, GS_PSMCT32, 6, 6, 1, 0, 0, 0, 0, 0, 0) },
        { kPrim,     prim_tex(3 /* triangle */, 0, 1, 0, 0, 0 /* STQ */) },
        /* S and T are divided by Q per pixel, so the values written here are
         * the coordinate already multiplied by that vertex's Q. */
        { kRgbaq,    rgbaq_q(kNeutral, kNeutral, kNeutral, kNeutral, 1.0f) },
        { kSt,       st(0.0f, 0.0f) },
        { kXyz2,     xyz2(40 * 16, 40 * 16, 0) },
        { kRgbaq,    rgbaq_q(kNeutral, kNeutral, kNeutral, kNeutral, 1.0f) },
        { kSt,       st(4.0f, 0.0f) },
        { kXyz2,     xyz2(472 * 16, 40 * 16, 0) },
        { kRgbaq,    rgbaq_q(kNeutral, kNeutral, kNeutral, kNeutral, 0.125f) },
        { kSt,       st(0.25f, 0.5f) },
        { kXyz2,     xyz2(256 * 16, 408 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-highlight2.gs: the same texture through all four TFX
 * functions, left to right, with a fragment colour of half and a fragment
 * alpha of 0x40. MODULATE halves the texel, DECAL ignores the fragment
 * entirely, HIGHLIGHT adds the fragment alpha to the colour and to the
 * alpha, and HIGHLIGHT2 adds it to the colour and keeps the texel's alpha.
 * The two HIGHLIGHT modes differ only in alpha, so the frame buffer's alpha
 * byte is where that difference is; the pair is drawn anyway because the
 * alpha then decides a blend or a destination alpha test in any capture that
 * follows. */
bool write_texture_highlight_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-highlight2.gs");
    if (!d.ok()) return false;
    d.gif(2, upload_packet(kTexBp, 1, GS_PSMCT32, 0, 0, kTexW, kTexH, 32).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x08, 0x08, 0x08, 0);
    p.registers({
        { kTexa,   texa(0x80, 0, 0x80) },
        { kClamp1, clamp_reg(1, 1, 0, 0, 0, 0) },
        { kTex1_1, tex1(1, 0, 0, 0, 0, 0, 0) },
        { kRgbaq,  rgbaq(0x40, 0x40, 0x40, 0x40) },
        { kPrim,   prim_tex(6, 0, 1, 0, 0, 1) },
    }, false);
    for (uint32_t tfx = 0; tfx < 4; ++tfx) {
        const int32_t x = 16 + (int32_t)tfx * 124;
        p.registers({
            { kTex0_1, tex0(kTexBp, 1, GS_PSMCT32, kTexTw, kTexTh, 1, tfx, 0, 0, 0, 0, 0) },
            { kUv,     uv(0, 0) },
            { kXyz2,   xyz2(x * 16, 120 * 16, 0) },
            { kUv,     uv(kTexW * 16, kTexH * 16) },
            { kXyz2,   xyz2((x + 112) * 16, 232 * 16, 0) },
        }, tfx == 3);
    }
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* draw-texture-feedback.gs: a sprite that reads the frame buffer it is
 * drawing into, which is the case the page tracker exists for. The picture
 * is drawn first, then sampled out of the same pages and written back
 * magnified into the lower half. A renderer that keeps both primitives in
 * one dispatch reads whatever the other tiles happen to have written by
 * then, which is a race and shows as a torn or empty copy. */
bool write_texture_feedback_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-texture-feedback.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x10, 0);
    /* Something to read back: four solid bars across the top left. */
    std::vector<std::pair<uint32_t, uint64_t>> bars;
    bars.push_back({ kPrim, prim(6, 0, 0) });
    for (int i = 0; i < 4; ++i) {
        bars.push_back({ kRgbaq, rgbaq(0xE0 - (uint32_t)i * 0x30,
                                       0x30 + (uint32_t)i * 0x30, 0x80, 0x80) });
        bars.push_back({ kXyz2, xyz2(0, (int32_t)(i * 32) * 16, 0) });
        bars.push_back({ kXyz2, xyz2(256 * 16, (int32_t)(i * 32 + 32) * 16, 0) });
    }
    p.registers(bars, false);
    /* Now read those very pages as a texture. TBP0 is the frame buffer's own
     * base and TBW its own width. */
    p.registers({
        { kTexa,   texa(0x80, 0, 0x80) },
        { kClamp1, clamp_reg(1, 1, 0, 0, 0, 0) },
        { kTex1_1, tex1(1, 0, 0, 0, 0, 0, 0) },
        { kTex0_1, tex0(kDrawFbp * 32, kDrawFbw, GS_PSMCT32, 9, 9, 1, 0, 0, 0, 0, 0, 0) },
        { kPrim,   prim_tex(6, 0, 1, 0, 0, 1) },
        { kRgbaq,  rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kUv,     uv(0, 0) },
        { kXyz2,   xyz2(0, 224 * 16, 0) },
        { kUv,     uv(256 * 16, 128 * 16) },
        { kXyz2,   xyz2(512 * 16, 448 * 16, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* ---- the milestone (d) and (f) cases ----------------------------------------
 *
 * Same shape as the rest: the state, a full-screen clear, the geometry, and
 * the gameplay display setup so the replay tool can screenshot it.
 */

bool write_aa1_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-aa1-tri.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x18, 0x18, 0x20, 0);
    /* The blend AA1's coverage feeds: Cv = (Cs - Cd) * As / 0x80 + Cd, which
     * is A source, B destination, C source alpha, D destination. With the
     * primitive's own alpha at 0x80 an interior pixel is the source colour
     * exactly, so anything that is not the flat triangle colour is coverage
     * doing its work at an edge. */
    std::vector<std::pair<uint32_t, uint64_t>> regs;
    regs.push_back({ kAlpha1, alpha_reg(0, 1, 0, 1, 0) });

    /* Left: no AA1, so the edges are the sample rule's own staircase. */
    regs.push_back({ kPrim, prim_aa(3, 0, 1, 0) });
    regs.push_back({ kRgbaq, rgbaq(0xE0, 0x40, 0x30, 0x80) });
    regs.push_back({ kXyz2, xyz2(40 * 16, 60 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(230 * 16, 110 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(70 * 16, 380 * 16, 0) });

    /* Right: the same shape, AA1 set. */
    regs.push_back({ kPrim, prim_aa(3, 0, 1, 1) });
    regs.push_back({ kRgbaq, rgbaq(0x30, 0xC0, 0xE0, 0x80) });
    regs.push_back({ kXyz2, xyz2(296 * 16, 60 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(486 * 16, 110 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(326 * 16, 380 * 16, 0) });

    /* And a very shallow triangle, where a whole edge is nearly horizontal
     * and one pixel of coverage covers many columns. */
    regs.push_back({ kRgbaq, rgbaq(0xF0, 0xE0, 0x60, 0x80) });
    regs.push_back({ kXyz2, xyz2(40 * 16, 410 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(480 * 16, 424 * 16, 0) });
    regs.push_back({ kXyz2, xyz2(40 * 16, 438 * 16, 0) });
    p.registers(regs, true);

    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_lines_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-lines.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x08, 0x08, 0x08, 0);

    std::vector<std::pair<uint32_t, uint64_t>> regs;
    /* A fan of sixteen lines from one corner, so every slope from flat to
     * steep is drawn and the major axis changes halfway through the fan. IIP
     * is set, so the colour along each line is interpolated too. */
    regs.push_back({ kPrim, prim(1 /* line */, 1, 0) });
    for (int i = 0; i < 16; ++i) {
        const int32_t ex = 40 + 200 - i * 12;
        const int32_t ey = 40 + i * 12;
        regs.push_back({ kRgbaq, rgbaq(0xFF - (uint32_t)i * 12, 0x40 + (uint32_t)i * 12,
                                       0x80, 0x80) });
        regs.push_back({ kXyz2, xyz2(40 * 16, 40 * 16, 0) });
        regs.push_back({ kRgbaq, rgbaq(0x40, 0xFF, 0xC0, 0x80) });
        regs.push_back({ kXyz2, xyz2(ex * 16, ey * 16, 0) });
    }
    /* One line whose two endpoints fall inside a single pixel of the major
     * axis, three sixteenths apart. The renderer draws the pixel the first
     * vertex falls in and says so once. */
    regs.push_back({ kRgbaq, rgbaq(0xFF, 0xFF, 0xFF, 0x80) });
    regs.push_back({ kXyz2, xyz2(300 * 16 + 2, 60 * 16 + 3, 0) });
    regs.push_back({ kXyz2, xyz2(300 * 16 + 5, 60 * 16 + 5, 0) });

    /* The same fan again with AA1 and the coverage blend, lower down the
     * picture, so the two are side by side in one screenshot. */
    regs.push_back({ kAlpha1, alpha_reg(0, 1, 0, 1, 0) });
    regs.push_back({ kPrim, prim_aa(1, 1, 1, 1) });
    for (int i = 0; i < 16; ++i) {
        const int32_t ex = 40 + 200 - i * 12;
        const int32_t ey = 240 + i * 12;
        regs.push_back({ kRgbaq, rgbaq(0xFF - (uint32_t)i * 12, 0x40 + (uint32_t)i * 12,
                                       0x80, 0x80) });
        regs.push_back({ kXyz2, xyz2(40 * 16, 240 * 16, 0) });
        regs.push_back({ kRgbaq, rgbaq(0x40, 0xFF, 0xC0, 0x80) });
        regs.push_back({ kXyz2, xyz2(ex * 16, ey * 16, 0) });
    }
    p.registers(regs, true);

    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_scanmsk_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-scanmsk.gs");
    if (!d.ok()) return false;
    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);
    /* Three bands of one sprite each. The first is drawn with no mask, the
     * second with SCANMSK 2 (even rows only) and the third with SCANMSK 3
     * (odd rows only), so the two masks are visible as combs against the
     * solid band above them and against each other. */
    const uint32_t masks[3] = { 0, 2, 3 };
    for (int i = 0; i < 3; ++i) {
        p.registers({
            { kScanmsk, masks[i] },
            { kPrim,    prim(6, 0, 0) },
            { kRgbaq,   rgbaq(0x30 + (uint32_t)i * 0x50, 0xC0, 0xF0 - (uint32_t)i * 0x50,
                              0x80) },
            { kXyz2,    xyz2(40 * 16, (int32_t)(40 + i * 120) * 16, 0) },
            { kXyz2,    xyz2(472 * 16, (int32_t)(140 + i * 120) * 16, 0) },
        }, false);
    }
    /* Back to no mask, so the register does not leak into whatever reads the
     * dump next. */
    p.registers({ { kScanmsk, 0 } }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_fbz_alias_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-fbz-alias.gs");
    if (!d.ok()) return false;
    Packet p;
    /* The frame buffer and the Z buffer at the same base. The two formats
     * have the same page geometry and different block orders, so a pixel's
     * colour and its depth land on the same word for some pixels and not for
     * others, which is exactly the case the fine pass has a rule for: where
     * they do, the depth is written second and is what the memory holds.
     *
     * The Z values are large and vary across the triangle, so the pixels
     * whose colour word the depth landed on are obvious. */
    p.registers({
        { kPrmodecont, 1 },
        { kXyoffset1,  0 },
        { kScissor1,   scissor(0, kDrawW - 1, 0, kDrawH - 1) },
        { kFrame1,     frame(kDrawFbp, kDrawFbw, GS_PSMCT32, 0) },
        { kZbuf1,      zbuf(kDrawFbp, 0 /* PSMZ32 */, 0 /* ZMSK: write Z */) },
        { kTest1,      test(0, 1, 0, 0, 0, 0, 0, 1) },
    }, false);
    clear_packet(p, 0x10, 0x30, 0x10, 0);
    p.registers({
        { kPrim,  prim(3, 0, 0) },
        { kRgbaq, rgbaq(0xC0, 0x40, 0x40, 0x80) },
        { kXyz2,  xyz2(60 * 16, 60 * 16, 0x20000000) },
        { kXyz2,  xyz2(450 * 16, 120 * 16, 0x60000000) },
        { kXyz2,  xyz2(120 * 16, 380 * 16, 0xA0000000) },
    }, false);
    /* The same triangle again on the right with ZMSK set, where no depth is
     * written and the colour therefore survives. */
    p.registers({
        { kZbuf1, zbuf(kDrawFbp, 0, 1 /* ZMSK: no Z write */) },
    }, false);
    p.registers({
        { kPrim,  prim(3, 0, 0) },
        { kRgbaq, rgbaq(0x40, 0x40, 0xC0, 0x80) },
        { kXyz2,  xyz2(200 * 16, 400 * 16, 0x20000000) },
        { kXyz2,  xyz2(480 * 16, 400 * 16, 0x60000000) },
        { kXyz2,  xyz2(480 * 16, 440 * 16, 0xA0000000) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_scale_case(const std::string& dir) {
    DumpWriter d(dir + "/draw-scale-texture.gs");
    if (!d.ok()) return false;
    /* The case to look at with display.render_scale 1 against 16: a gradient
     * behind a textured triangle whose three edges are all at awkward angles,
     * so every one of them is a staircase at scale 1 and a set of intermediate
     * pixels above it. Nothing here is antialiased by the game: what changes
     * between the two runs is the sampling, and the texture is magnified
     * enough that its own filtering is not what the eye lands on. */
    d.gif(2, upload_packet(kTexBp, 1, GS_PSMCT32, 0, 0, kTexW, kTexH, 32).bytes);

    Packet p;
    p.registers(draw_state(0, 1, 0, 1), false);
    clear_packet(p, 0x00, 0x00, 0x00, 0);
    /* The background: two Gouraud triangles making one gradient over the
     * whole buffer, so the picture behind the edges is not flat and a
     * resolved edge pixel has something to be between. */
    p.registers({
        { kPrim,  prim(3, 1, 0) },
        { kRgbaq, rgbaq(0x10, 0x20, 0x60, 0x80) },
        { kXyz2,  xyz2(0, 0, 0) },
        { kRgbaq, rgbaq(0x80, 0x30, 0x20, 0x80) },
        { kXyz2,  xyz2(kDrawW * 16, 0, 0) },
        { kRgbaq, rgbaq(0x20, 0x70, 0x30, 0x80) },
        { kXyz2,  xyz2(0, kDrawH * 16, 0) },

        { kRgbaq, rgbaq(0x80, 0x30, 0x20, 0x80) },
        { kXyz2,  xyz2(kDrawW * 16, 0, 0) },
        { kRgbaq, rgbaq(0x20, 0x70, 0x30, 0x80) },
        { kXyz2,  xyz2(0, kDrawH * 16, 0) },
        { kRgbaq, rgbaq(0xA0, 0xA0, 0x40, 0x80) },
        { kXyz2,  xyz2(kDrawW * 16, kDrawH * 16, 0) },
    }, false);
    /* The textured triangle. UV coordinates, nearest filtering, MODULATE with
     * the neutral fragment colour, so the texels arrive unaltered. */
    p.registers({
        { kTexa,   texa(0x80, 0, 0x80) },
        { kClamp1, clamp_reg(0, 0, 0, 0, 0, 0) },
        { kTex1_1, tex1(1, 0, 0, 0, 0, 0, 0) },
        { kTex0_1, tex0(kTexBp, 1, GS_PSMCT32, kTexTw, kTexTh, 1, 0 /* MODULATE */,
                        0, 0, 0, 0, 0) },
        { kPrim,   prim_tex(3, 0, 1, 0, 0, 1) },
        { kRgbaq,  rgbaq(kNeutral, kNeutral, kNeutral, kNeutral) },
        { kUv,     uv(0, 0) },
        { kXyz2,   xyz2(70 * 16 + 5, 50 * 16 + 11, 0) },
        { kUv,     uv(kTexW * 16, 0) },
        { kXyz2,   xyz2(460 * 16 + 9, 150 * 16 + 3, 0) },
        { kUv,     uv(0, kTexH * 16) },
        { kXyz2,   xyz2(160 * 16 + 7, 400 * 16 + 13, 0) },
    }, true);
    d.gif(2, p.bytes);
    program_gameplay(d, kDrawFbp, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

/* ---- the display setups --------------------------------------------------- */

/* Gameplay: 512 pixels by 224 lines per field, which is the NTSC mode area
 * exactly at MAGH+1 = 5. The buffer is 512 wide (FBW 8) at page 64, which is
 * byte 0x80000, where the game renders. */
void program_gameplay(DumpWriter& d, uint32_t fbp, uint32_t psm) {
    d.priv(kSmode1, kSmode1Ntsc);
    d.priv(kSmode2, kSmode2Interlaced);
    d.priv(kPmode, pmode(0, 1, 1, 0, 0, 0xFF));
    d.priv(kBgcolor, 0);
    d.priv(kDispfb2, dispfb(fbp, 8, psm, 0, 0));
    d.priv(kDisplay2, display(636, 50, 4, 0, 2559, 447));
}

/* The attract movie: 720 pixels by 240 lines per field from the same corner,
 * read at DBX 36, DBY 12 out of a 720-wide buffer (FBW 12 covers 768). */
void program_movie(DumpWriter& d, uint32_t fbp, uint32_t psm) {
    d.priv(kSmode1, kSmode1Ntsc);
    d.priv(kSmode2, kSmode2Interlaced);
    d.priv(kPmode, pmode(0, 1, 1, 0, 0, 0xFF));
    d.priv(kBgcolor, 0);
    d.priv(kDispfb2, dispfb(fbp, 12, psm, 36, 12));
    d.priv(kDisplay2, display(636, 50, 3, 0, 2879, 479));
}

bool write_upload_case(const std::string& dir, const FormatInfo& f) {
    DumpWriter d(dir + "/upload-" + f.name + ".gs");
    if (!d.ok()) return false;
    /* Uploaded to page 64 (byte 0x80000), the buffer the gameplay setup
     * displays, so a format whose swizzle is wrong is visible in the
     * scanout rather than only in a memory dump. */
    d.gif(2, upload_packet(64 * 32, 8, f.psm, 0, 0, 256, 256, f.transfer_bits).bytes);
    /* Displayed as PSMCT32 whatever was uploaded: the CRTC reads only the
     * four colour formats, so an indexed or Z upload is shown as the raw
     * words it landed on. That is the point of these files. */
    program_gameplay(d, 64, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_ntsc_case(const std::string& dir) {
    DumpWriter d(dir + "/ntsc-512x448.gs");
    if (!d.ok()) return false;
    d.gif(2, upload_packet(64 * 32, 8, GS_PSMCT32, 0, 0, 512, 448, 32).bytes);
    program_gameplay(d, 64, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_movie_case(const std::string& dir) {
    DumpWriter d(dir + "/movie-720x480.gs");
    if (!d.ok()) return false;
    /* 720x480 at page 0, which is where a synthetic movie buffer can sit
     * without colliding with the gameplay buffer above. */
    d.gif(2, upload_packet(0, 12, GS_PSMCT32, 0, 0, 720, 480, 32).bytes);
    program_movie(d, 0, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_local_to_local_case(const std::string& dir) {
    DumpWriter d(dir + "/local-to-local.gs");
    if (!d.ok()) return false;
    /* Upload into a scratch buffer at page 0, then copy it into the
     * displayed buffer at page 64. */
    d.gif(2, upload_packet(0, 8, GS_PSMCT32, 0, 0, 256, 256, 32).bytes);

    Packet copy;
    copy.registers({
        { kBitbltbuf, bitbltbuf(0, 8, GS_PSMCT32, 64 * 32, 8, GS_PSMCT32) },
        { kTrxpos,    trxpos(0, 0, 0, 0, 0) },
        { kTrxreg,    trxreg(256, 256) },
        { kTrxdir,    2 },
    }, true);
    d.gif(2, copy.bytes);

    /* The same buffer copied onto itself, overlapping, with TRXPOS DIR 3
     * (lower right to upper left). Order is the only thing that makes this
     * case different from DIR 0, so it is the one that catches a copy loop
     * that ignores DIR. */
    Packet overlap;
    overlap.registers({
        { kBitbltbuf, bitbltbuf(64 * 32, 8, GS_PSMCT32, 64 * 32, 8, GS_PSMCT32) },
        { kTrxpos,    trxpos(0, 0, 8, 8, 3) },
        { kTrxreg,    trxreg(200, 200) },
        { kTrxdir,    2 },
    }, true);
    d.gif(2, overlap.bytes);

    program_gameplay(d, 64, GS_PSMCT32);
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

bool write_two_circuit_case(const std::string& dir) {
    DumpWriter d(dir + "/two-circuit.gs");
    if (!d.ok()) return false;
    /* Two buffers with different gradients, one per circuit, over the same
     * window. Circuit 1 is the front layer and MMOD 0 takes the blend factor
     * from its own alpha, which the 32-bit gradient sets to 0x80 (one), so
     * ALP is exercised by flipping MMOD in a hand edit rather than being
     * baked in here. */
    d.gif(2, upload_packet(0, 8, GS_PSMCT32, 0, 0, 512, 448, 32).bytes);
    d.gif(2, upload_packet(64 * 32, 8, GS_PSMCT16, 0, 0, 512, 448, 16).bytes);

    d.priv(kSmode1, kSmode1Ntsc);
    d.priv(kSmode2, kSmode2Interlaced);
    d.priv(kPmode, pmode(1, 1, 1, 0, 0, 0x40));
    d.priv(kBgcolor, 0x00204060);
    d.priv(kDispfb1, dispfb(0, 8, GS_PSMCT32, 0, 0));
    d.priv(kDisplay1, display(636, 50, 4, 0, 2559, 447));
    d.priv(kDispfb2, dispfb(64, 8, GS_PSMCT16, 0, 0));
    d.priv(kDisplay2, display(636, 50, 4, 0, 2559, 447));
    d.vsync(0);
    d.vsync(1);
    std::printf("wrote %s\n", d.path().c_str());
    return true;
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: icorecomp-gs-gen-dump <output-directory>\n");
        return 1;
    }
    const std::string dir = argv[1];
    bool ok = true;
    for (const FormatInfo& f : kFormats) ok = write_upload_case(dir, f) && ok;
    ok = write_ntsc_case(dir) && ok;
    ok = write_movie_case(dir) && ok;
    ok = write_local_to_local_case(dir) && ok;
    ok = write_two_circuit_case(dir) && ok;
    ok = write_flat_triangle_case(dir) && ok;
    ok = write_gouraud_case(dir) && ok;
    ok = write_sprite_case(dir) && ok;
    ok = write_strip_case(dir) && ok;
    ok = write_fan_case(dir) && ok;
    ok = write_depth_case(dir) && ok;
    ok = write_fbmsk_case(dir) && ok;
    for (const FormatInfo& f : kFormats) {
        /* The Z formats are addressable as textures and this renderer reads
         * them, but a Z buffer bound as a texture is not something the
         * manual describes, so the format sweep stays on the colour and
         * palette formats. */
        if (f.psm >= GS_PSMZ32) continue;
        ok = write_texture_format_case(dir, f) && ok;
    }
    ok = write_texture_csm2_case(dir) && ok;
    ok = write_texture_bilinear_case(dir) && ok;
    ok = write_texture_clamp_case(dir) && ok;
    ok = write_texture_mip_case(dir) && ok;
    ok = write_texture_highlight_case(dir) && ok;
    ok = write_texture_feedback_case(dir) && ok;
    ok = write_aa1_case(dir) && ok;
    ok = write_lines_case(dir) && ok;
    ok = write_scanmsk_case(dir) && ok;
    ok = write_fbz_alias_case(dir) && ok;
    ok = write_scale_case(dir) && ok;
    if (!ok) {
        std::fprintf(stderr, "icorecomp-gs-gen-dump: one or more files could not be written "
                             "into %s\n", dir.c_str());
        return 1;
    }
    return 0;
}
