// src/runtime/gs/render/shaders/msl/overlay.vert.metal: MSL for src/runtime/gs/render/shaders/overlay.vert, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The argument indices were rewritten to the convention in
// src/runtime/rhi/metal/rhi_metal_bindings.h; that header says why.
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Push
{
    float4x4 transform;
    float2 surface_size;
    float2 translate;
    uint use_transform;
    uint use_texture;
};

struct main0_out
{
    float2 v_uv [[user(locn0)]];
    float4 v_color [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float2 a_position [[attribute(0)]];
    float2 a_uv [[attribute(1)]];
    float4 a_color [[attribute(2)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant Push& pc [[buffer(20)]])
{
    main0_out out = {};
    float4 p = float4(in.a_position + pc.translate, 0.0, 1.0);
    if (pc.use_transform != 0u)
    {
        p = pc.transform * p;
    }
    out.gl_Position = float4(((2.0 * p.x) / pc.surface_size.x) - p.w, ((2.0 * p.y) / pc.surface_size.y) - p.w, 0.0, p.w);
    out.v_uv = in.a_uv;
    out.v_color = in.a_color;
    out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
    return out;
}
