// src/runtime/gs/render/shaders/msl/overlay.frag.metal: MSL for src/runtime/gs/render/shaders/overlay.frag, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The argument indices were rewritten to the convention in
// src/runtime/rhi/metal/rhi_metal_bindings.h; that header says why.
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Push
{
    float4x4 transform;
    float2 surface_size;
    float2 translate;
    uint use_transform;
    uint use_texture;
};

struct main0_out
{
    float4 o_color [[color(0)]];
};

struct main0_in
{
    float2 v_uv [[user(locn0)]];
    float4 v_color [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant Push& pc [[buffer(20)]], array<texture2d<float>, 8> g_textures [[texture(0)]], array<sampler, 4> g_samplers [[sampler(0)]])
{
    main0_out out = {};
    float4 c = in.v_color;
    if (pc.use_texture != 0u)
    {
        c *= g_textures[0].sample(g_samplers[1], in.v_uv);
    }
    out.o_color = c;
    return out;
}
