// src/runtime/gs/render/shaders/msl/raster.comp.metal: MSL for src/runtime/gs/render/shaders/raster.comp, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The argument indices were rewritten to the convention in
// src/runtime/rhi/metal/rhi_metal_bindings.h; that header says why.
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

template<typename T, typename U, typename V>
[[clang::optnone]] T spvMulExtended(V l, V r)
{
    return T{U(l * r), U(mulhi(l, r))};
}

struct ResType
{
    int _m0;
    int _m1;
};

struct ResType_1
{
    uint _m0;
    uint _m1;
};

struct GsBuffer
{
    uint data[1];
};

struct Push
{
    uint frame_base_block;
    uint frame_bw;
    uint frame_psm;
    uint frame_mask;
    uint z_base_block;
    uint z_psm;
    uint z_write;
    uint tile_x0;
    uint tile_y0;
    uint fogcol;
    uint dimx0;
    uint dimx1;
    uint samples;
    uint tile_w;
    uint tile_h;
    uint shadow;
};

constant spvUnsafeArray<uint, 32> _752 = spvUnsafeArray<uint, 32>({ 0u, 1u, 4u, 5u, 16u, 17u, 20u, 21u, 2u, 3u, 6u, 7u, 18u, 19u, 22u, 23u, 8u, 9u, 12u, 13u, 24u, 25u, 28u, 29u, 10u, 11u, 14u, 15u, 26u, 27u, 30u, 31u });
constant spvUnsafeArray<uint, 32> _763 = spvUnsafeArray<uint, 32>({ 24u, 25u, 28u, 29u, 8u, 9u, 12u, 13u, 26u, 27u, 30u, 31u, 10u, 11u, 14u, 15u, 16u, 17u, 20u, 21u, 0u, 1u, 4u, 5u, 18u, 19u, 22u, 23u, 2u, 3u, 6u, 7u });
constant spvUnsafeArray<uint, 32> _776 = spvUnsafeArray<uint, 32>({ 0u, 2u, 8u, 10u, 1u, 3u, 9u, 11u, 4u, 6u, 12u, 14u, 5u, 7u, 13u, 15u, 16u, 18u, 24u, 26u, 17u, 19u, 25u, 27u, 20u, 22u, 28u, 30u, 21u, 23u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _786 = spvUnsafeArray<uint, 32>({ 0u, 2u, 16u, 18u, 1u, 3u, 17u, 19u, 8u, 10u, 24u, 26u, 9u, 11u, 25u, 27u, 4u, 6u, 20u, 22u, 5u, 7u, 21u, 23u, 12u, 14u, 28u, 30u, 13u, 15u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _796 = spvUnsafeArray<uint, 32>({ 24u, 26u, 16u, 18u, 25u, 27u, 17u, 19u, 28u, 30u, 20u, 22u, 29u, 31u, 21u, 23u, 8u, 10u, 0u, 2u, 9u, 11u, 1u, 3u, 12u, 14u, 4u, 6u, 13u, 15u, 5u, 7u });
constant spvUnsafeArray<uint, 32> _806 = spvUnsafeArray<uint, 32>({ 24u, 26u, 8u, 10u, 25u, 27u, 9u, 11u, 16u, 18u, 0u, 2u, 17u, 19u, 1u, 3u, 28u, 30u, 12u, 14u, 29u, 31u, 13u, 15u, 20u, 22u, 4u, 6u, 21u, 23u, 5u, 7u });
constant spvUnsafeArray<uint, 16> _844 = spvUnsafeArray<uint, 16>({ 0u, 1u, 4u, 5u, 8u, 9u, 12u, 13u, 2u, 3u, 6u, 7u, 10u, 11u, 14u, 15u });

static inline __attribute__((always_inline))
uint gs_psm_family(thread const uint& psm)
{
    if (((((psm == 0u) || (psm == 1u)) || (psm == 27u)) || (psm == 36u)) || (psm == 44u))
    {
        return 0u;
    }
    if ((psm == 48u) || (psm == 49u))
    {
        return 5u;
    }
    if (psm == 2u)
    {
        return 1u;
    }
    if (psm == 10u)
    {
        return 2u;
    }
    if (psm == 50u)
    {
        return 6u;
    }
    if (psm == 58u)
    {
        return 7u;
    }
    if (psm == 19u)
    {
        return 3u;
    }
    if (psm == 20u)
    {
        return 4u;
    }
    return 255u;
}

static inline __attribute__((always_inline))
uint gs_page_width(thread const uint& fam)
{
    if ((fam == 3u) || (fam == 4u))
    {
        return 128u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_page_height(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 128u;
    }
    if (fam == 3u)
    {
        return 64u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 32u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_block_width(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 32u;
    }
    if (fam == 3u)
    {
        return 16u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    return 16u;
}

static inline __attribute__((always_inline))
uint gs_block_height(thread const uint& fam)
{
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    if ((fam == 3u) || (fam == 4u))
    {
        return 16u;
    }
    return 8u;
}

static inline __attribute__((always_inline))
uint gs_page_block_cols(thread const uint& fam)
{
    uint param = fam;
    uint param_1 = fam;
    return gs_page_width(param) / gs_block_width(param_1);
}

static inline __attribute__((always_inline))
uint gs_block_number(thread const uint& fam, thread const uint& bx, thread const uint& by)
{
    uint param = fam;
    uint i = (by * gs_page_block_cols(param)) + bx;
    if ((fam == 0u) || (fam == 3u))
    {
        return _752[i];
    }
    if (fam == 5u)
    {
        return _763[i];
    }
    if ((fam == 1u) || (fam == 4u))
    {
        return _776[i];
    }
    if (fam == 2u)
    {
        return _786[i];
    }
    if (fam == 6u)
    {
        return _796[i];
    }
    if (fam == 7u)
    {
        return _806[i];
    }
    return 0u;
}

static inline __attribute__((always_inline))
uint gs_addr_bits(thread const uint& psm)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    if (fam == 3u)
    {
        return 8u;
    }
    if (fam == 4u)
    {
        return 4u;
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        return 16u;
    }
    return 32u;
}

static inline __attribute__((always_inline))
uint gs_block_offset(thread const uint& fam, thread const uint& x, thread const uint& y)
{
    uint param = fam;
    uint bw = gs_block_width(param);
    uint param_1 = fam;
    uint bh = gs_block_height(param_1);
    uint lx = x % bw;
    uint ly = y % bh;
    if ((fam == 0u) || (fam == 5u))
    {
        uint col = ly >> uint(1);
        return (col * 16u) + _844[((ly & 1u) * 8u) + (lx & 7u)];
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        uint col_1 = ly >> uint(1);
        uint w = _844[((ly & 1u) * 8u) + (lx & 7u)];
        uint hword = (lx >> uint(3)) & 1u;
        return ((col_1 * 32u) + (w * 2u)) + hword;
    }
    uint col_2 = ly >> uint(2);
    uint row = ly & 3u;
    uint rot = (row >= 2u) ? 4u : 0u;
    uint w_1 = _844[(((lx >> uint(3)) & 1u) * 8u) + (((lx & 7u) + rot) & 7u)];
    uint _924;
    if (row == 0u)
    {
        _924 = 0u;
    }
    else
    {
        uint _930;
        if (row == 1u)
        {
            _930 = 2u;
        }
        else
        {
            _930 = (row == 2u) ? 1u : 3u;
        }
        _924 = _930;
    }
    uint sub = _924;
    if ((col_2 & 1u) != 0u)
    {
        sub ^= 2u;
    }
    if (fam == 3u)
    {
        return ((col_2 * 64u) + (w_1 * 4u)) + sub;
    }
    uint nib = (((lx >> uint(4)) & 1u) * 4u) + sub;
    return ((col_2 * 128u) + (w_1 * 8u)) + nib;
}

static inline __attribute__((always_inline))
uint gs_pixel_addr(thread const uint& psm, thread const uint& base_block, thread const uint& fbw, thread const uint& x, thread const uint& y)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    uint param_1 = fam;
    uint pw = gs_page_width(param_1);
    uint param_2 = fam;
    uint ph = gs_page_height(param_2);
    uint pages_across = (fbw * 64u) / pw;
    if (pages_across == 0u)
    {
        pages_across = 1u;
    }
    uint page = ((y / ph) * pages_across) + (x / pw);
    uint param_3 = fam;
    uint bx = (x % pw) / gs_block_width(param_3);
    uint param_4 = fam;
    uint by = (y % ph) / gs_block_height(param_4);
    uint param_5 = fam;
    uint param_6 = bx;
    uint param_7 = by;
    uint block = ((base_block + (page * 32u)) + gs_block_number(param_5, param_6, param_7)) & 16383u;
    uint param_8 = psm;
    uint units_per_block = 2048u / gs_addr_bits(param_8);
    uint param_9 = fam;
    uint param_10 = x;
    uint param_11 = y;
    return (block * units_per_block) + gs_block_offset(param_9, param_10, param_11);
}

static inline __attribute__((always_inline))
bool gs_alias_pixel(thread const uint& frame_psm, thread const uint& frame_addr, thread const uint& z_psm, thread const uint& z_addr)
{
    uint param = frame_psm;
    uint param_1 = z_psm;
    return (gs_addr_bits(param) == gs_addr_bits(param_1)) && (frame_addr == z_addr);
}

static inline __attribute__((always_inline))
uint mem_index(thread const uint& word, thread uint& g_plane)
{
    return (word & 1048575u) + g_plane;
}

static inline __attribute__((always_inline))
uint mem_load(thread const uint& word, thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16])
{
    uint param = word;
    uint i = mem_index(param, g_plane);
    uint _2734;
    if (g_shadow)
    {
        _2734 = g_buf[5]->data[i];
    }
    else
    {
        _2734 = g_buf[0]->data[i];
    }
    return _2734;
}

static inline __attribute__((always_inline))
uint gs_expand16(thread const uint& v)
{
    uint r = (v & 31u) << uint(3);
    uint g = ((v >> uint(5)) & 31u) << uint(3);
    uint b = ((v >> uint(10)) & 31u) << uint(3);
    uint a = ((v >> uint(15)) & 1u) * 128u;
    return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
}

static inline __attribute__((always_inline))
uint frame_load(thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint& g_faddr)
{
    uint psm = pc.frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint param = g_faddr >> uint(1);
        uint w = mem_load(param, g_plane, g_shadow, g_buf);
        uint _2828;
        if ((g_faddr & 1u) != 0u)
        {
            _2828 = w >> uint(16);
        }
        else
        {
            _2828 = w & 65535u;
        }
        uint hw = _2828;
        uint param_1 = hw;
        return gs_expand16(param_1);
    }
    uint param_2 = g_faddr;
    return mem_load(param_2, g_plane, g_shadow, g_buf);
}

static inline __attribute__((always_inline))
uint z_load(thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint& g_zaddr)
{
    uint psm = pc.z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint param = g_zaddr >> uint(1);
        uint w = mem_load(param, g_plane, g_shadow, g_buf);
        uint _2939;
        if ((g_zaddr & 1u) != 0u)
        {
            _2939 = w >> uint(16);
        }
        else
        {
            _2939 = w & 65535u;
        }
        return _2939;
    }
    uint param_1 = g_zaddr;
    uint w_1 = mem_load(param_1, g_plane, g_shadow, g_buf);
    uint _2955;
    if (psm == 49u)
    {
        _2955 = w_1 & 16777215u;
    }
    else
    {
        _2955 = w_1;
    }
    return _2955;
}

static inline __attribute__((always_inline))
uint gs_sample_cols(thread const uint& samples)
{
    if (samples >= 8u)
    {
        return 4u;
    }
    if (samples >= 4u)
    {
        return 2u;
    }
    return 1u;
}

static inline __attribute__((always_inline))
int gs_sample_x(thread const uint& samples, thread const uint& s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    return int(((((s % cols) * 2u) + 1u) * 8u) / cols);
}

static inline __attribute__((always_inline))
int gs_sample_y(thread const uint& samples, thread const uint& s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    uint rows = samples / cols;
    return int((((((s / cols) % rows) * 2u) + 1u) * 8u) / rows);
}

static inline __attribute__((always_inline))
bool gs_scanmsk_draws(thread const uint& msk, thread const int& py)
{
    if (msk < 2u)
    {
        return true;
    }
    return (uint(py) & 1u) == (msk & 1u);
}

static inline __attribute__((always_inline))
int2 gs_cross64(thread const int& a, thread const int& b, thread const int& c, thread const int& d)
{
    ResType _1143 = spvMulExtended<ResType, int>(a, b);
    int lo1 = _1143._m0;
    int hi1 = _1143._m1;
    ResType _1150 = spvMulExtended<ResType, int>(c, d);
    int lo2 = _1150._m0;
    int hi2 = _1150._m1;
    uint u1 = uint(lo1);
    uint u2 = uint(lo2);
    uint lo = u1 - u2;
    int borrow = int(u1 < u2);
    int hi = (hi1 - hi2) - borrow;
    return int2(int(lo), hi);
}

static inline __attribute__((always_inline))
int gs_i64_sign(thread const int2& v)
{
    if (v.y < 0)
    {
        return -1;
    }
    if (v.y > 0)
    {
        return 1;
    }
    return int(uint(v.x) != 0u);
}

static inline __attribute__((always_inline))
bool gs_edge_tie(thread const int& dx, thread const int& dy)
{
    bool _1483 = dy < 0;
    bool _1492;
    if (!_1483)
    {
        _1492 = (dy == 0) && (dx > 0);
    }
    else
    {
        _1492 = _1483;
    }
    return _1492;
}

static inline __attribute__((always_inline))
bool gs_edge_accept_value(thread const int2& e, thread const int& dx, thread const int& dy)
{
    int2 param = e;
    int s = gs_i64_sign(param);
    if (s > 0)
    {
        return true;
    }
    if (s < 0)
    {
        return false;
    }
    int param_1 = dx;
    int param_2 = dy;
    return gs_edge_tie(param_1, param_2);
}

static inline __attribute__((always_inline))
float gs_i64_float(thread const int2& v)
{
    return (float(v.y) * 4294967296.0) + float(uint(v.x));
}

static inline __attribute__((always_inline))
float gs_aa_edge_cover(thread const float& e, thread const int& dx, thread const int& dy)
{
    float fdx = float(dx);
    float fdy = float(dy);
    float len = sqrt((fdx * fdx) + (fdy * fdy));
    if (len == 0.0)
    {
        return 1.0;
    }
    float d = e / (16.0 * len);
    float a = abs(fdy) / len;
    float b = abs(fdx) / len;
    float amax = fast::max(a, b);
    float amin = fast::min(a, b);
    float reach = 0.5 * (amax + amin);
    float slab = 0.5 * (amax - amin);
    float ad = abs(d);
    if (ad >= reach)
    {
        return float(d > 0.0);
    }
    if (ad <= slab)
    {
        return 0.5 + (d / amax);
    }
    float t = reach - ad;
    float corner = (t * t) / ((2.0 * amax) * amin);
    float _1356;
    if (d > 0.0)
    {
        _1356 = 1.0 - corner;
    }
    else
    {
        _1356 = corner;
    }
    return _1356;
}

static inline __attribute__((always_inline))
float gs_aa_triangle_cover(thread const int& x0, thread const int& y0, thread const int& x1, thread const int& y1, thread const int& x2, thread const int& y2, thread const int& sx, thread const int& sy)
{
    int param = x1 - x0;
    int param_1 = sy - y0;
    int param_2 = y1 - y0;
    int param_3 = sx - x0;
    int2 param_4 = gs_cross64(param, param_1, param_2, param_3);
    float param_5 = gs_i64_float(param_4);
    int param_6 = x1 - x0;
    int param_7 = y1 - y0;
    float a = gs_aa_edge_cover(param_5, param_6, param_7);
    int param_8 = x2 - x1;
    int param_9 = sy - y1;
    int param_10 = y2 - y1;
    int param_11 = sx - x1;
    int2 param_12 = gs_cross64(param_8, param_9, param_10, param_11);
    float param_13 = gs_i64_float(param_12);
    int param_14 = x2 - x1;
    int param_15 = y2 - y1;
    float b = gs_aa_edge_cover(param_13, param_14, param_15);
    int param_16 = x0 - x2;
    int param_17 = sy - y2;
    int param_18 = y0 - y2;
    int param_19 = sx - x2;
    int2 param_20 = gs_cross64(param_16, param_17, param_18, param_19);
    float param_21 = gs_i64_float(param_20);
    int param_22 = x0 - x2;
    int param_23 = y0 - y2;
    float c = gs_aa_edge_cover(param_21, param_22, param_23);
    return fast::min(fast::min(a, b), c);
}

static inline __attribute__((always_inline))
bool gs_covers_sprite_at(thread const int& x0, thread const int& y0, thread const int& x1, thread const int& y1, thread const int& sx, thread const int& sy)
{
    return (((sx >= x0) && (sx < x1)) && (sy >= y0)) && (sy < y1);
}

static inline __attribute__((always_inline))
bool gs_covers_point(thread const int& x0, thread const int& y0, thread const int& px, thread const int& py)
{
    bool _1538 = (x0 >> 4) == px;
    bool _1545;
    if (_1538)
    {
        _1545 = (y0 >> 4) == py;
    }
    else
    {
        _1545 = _1538;
    }
    return _1545;
}

static inline __attribute__((always_inline))
bool gs_covers_line_dot(thread const int& x0, thread const int& y0, thread const int& px, thread const int& py)
{
    bool _1654 = (x0 >> 4) == px;
    bool _1661;
    if (_1654)
    {
        _1661 = (y0 >> 4) == py;
    }
    else
    {
        _1661 = _1654;
    }
    return _1661;
}

static inline __attribute__((always_inline))
bool gs_covers_line_span(thread const int& mj0, thread const int& mj1, thread const int& p)
{
    int sp = (p * 16) + 8;
    return (sp >= mj0) && (sp < mj1);
}

static inline __attribute__((always_inline))
int gs_line_minor(thread const int& minor_ref, thread const int& slope, thread const int& refp, thread const int& p)
{
    return minor_ref + (slope * (p - refp));
}

static inline __attribute__((always_inline))
int gs_line_offset(thread const int& minor_ref, thread const int& slope, thread const int& refp, thread const int& p, thread const int& smin)
{
    int param = minor_ref;
    int param_1 = slope;
    int param_2 = refp;
    int param_3 = p;
    return int(uint(gs_line_minor(param, param_1, param_2, param_3)) - (uint(smin) * 4096u));
}

static inline __attribute__((always_inline))
float gs_aa_line_cover(thread const int& minor_ref, thread const int& slope, thread const int& refp, thread const int& p, thread const int& smin)
{
    int param = minor_ref;
    int param_1 = slope;
    int param_2 = refp;
    int param_3 = p;
    int param_4 = smin;
    int d = gs_line_offset(param, param_1, param_2, param_3, param_4);
    if (d < 0)
    {
        d = -d;
    }
    if (d >= 65536)
    {
        return 0.0;
    }
    return 1.0 - (float(d) / 65536.0);
}

static inline __attribute__((always_inline))
bool gs_covers_line_at(thread const int& mj0, thread const int& mj1, thread const int& minor_ref, thread const int& slope, thread const int& refp, thread const int& p, thread const int& smin)
{
    int param = mj0;
    int param_1 = mj1;
    int param_2 = p;
    if (!gs_covers_line_span(param, param_1, param_2))
    {
        return false;
    }
    int param_3 = minor_ref;
    int param_4 = slope;
    int param_5 = refp;
    int param_6 = p;
    int param_7 = smin;
    int d = gs_line_offset(param_3, param_4, param_5, param_6, param_7);
    return (d >= (-32768)) && (d < 32768);
}

static inline __attribute__((always_inline))
uint gs_z_at(thread const uint& z_i, thread const uint& z_f, thread const uint& zdx_i, thread const uint& zdx_f, thread const uint& zdy_i, thread const uint& zdy_f, thread const uint& dxp, thread const uint& dyp)
{
    ResType_1 _1790 = spvMulExtended<ResType_1, uint>(zdx_f, dxp);
    uint lx = _1790._m0;
    uint hx = _1790._m1;
    ResType_1 _1797 = spvMulExtended<ResType_1, uint>(zdy_f, dyp);
    uint ly = _1797._m0;
    uint hy = _1797._m1;
    uint frac = z_f;
    uint carry = 0u;
    ResType_1 _1806;
    _1806._m0 = frac + lx;
    _1806._m1 = select(uint(1), uint(0), _1806._m0 >= max(frac, lx));
    uint c = _1806._m1;
    frac = _1806._m0;
    carry += c;
    ResType_1 _1814;
    _1814._m0 = frac + ly;
    _1814._m1 = select(uint(1), uint(0), _1814._m0 >= max(frac, ly));
    c = _1814._m1;
    frac = _1814._m0;
    carry += c;
    return ((((z_i + (zdx_i * dxp)) + (zdy_i * dyp)) + hx) + hy) + carry;
}

static inline __attribute__((always_inline))
uint gs_z_precision_mask(thread const uint& psm)
{
    if (psm == 49u)
    {
        return 16777215u;
    }
    if ((psm == 50u) || (psm == 58u))
    {
        return 65535u;
    }
    return 4294967295u;
}

static inline __attribute__((always_inline))
uint chan(thread const uint& rgba, thread const uint& i)
{
    return (rgba >> (i * 8u)) & 255u;
}

static inline __attribute__((always_inline))
int clamp255(thread const int& v)
{
    return clamp(v, 0, 255);
}

static inline __attribute__((always_inline))
uint gs_tex0_tw(thread const uint& lo)
{
    return (lo >> uint(26)) & 15u;
}

static inline __attribute__((always_inline))
uint gs_tex0_th(thread const uint& lo, thread const uint& hi)
{
    return ((lo >> uint(30)) & 3u) | ((hi & 3u) << uint(2));
}

static inline __attribute__((always_inline))
uint gs_tex1_mxl(thread const uint& lo)
{
    return (lo >> uint(2)) & 7u;
}

static inline __attribute__((always_inline))
uint gs_tex1_lcm(thread const uint& lo)
{
    return lo & 1u;
}

static inline __attribute__((always_inline))
uint gs_tex1_l(thread const uint& lo)
{
    return (lo >> uint(19)) & 3u;
}

static inline __attribute__((always_inline))
int gs_tex1_k(thread const uint& hi)
{
    int k = int(hi & 4095u);
    int _1953;
    if (k >= 2048)
    {
        _1953 = k - 4096;
    }
    else
    {
        _1953 = k;
    }
    return _1953;
}

static inline __attribute__((always_inline))
int gs_tex_lod(thread const uint& lcm, thread const uint& l, thread const int& k, thread const float& q, thread const uint& mxl)
{
    if (lcm != 0u)
    {
        return k;
    }
    float aq = abs(q);
    if (!(aq > 1.0000000031710768509710513471353e-30))
    {
        return int(mxl) * 16;
    }
    float lod = log2(1.0 / aq) * float(1u << l);
    return int(floor(lod * 16.0)) + k;
}

static inline __attribute__((always_inline))
uint gs_tex1_mmag(thread const uint& lo)
{
    return (lo >> uint(5)) & 1u;
}

static inline __attribute__((always_inline))
uint gs_tex1_mmin(thread const uint& lo)
{
    return (lo >> uint(6)) & 7u;
}

static inline __attribute__((always_inline))
uint gs_tex0_psm(thread const uint& lo)
{
    return (lo >> uint(20)) & 63u;
}

static inline __attribute__((always_inline))
uint gs_tex0_tbp0(thread const uint& lo)
{
    return lo & 16383u;
}

static inline __attribute__((always_inline))
uint gs_tex1_mtba(thread const uint& lo)
{
    return (lo >> uint(9)) & 1u;
}

static inline __attribute__((always_inline))
uint gs_miptbp_tbp(thread const uint& lo, thread const uint& hi, thread const uint& which)
{
    if (which == 0u)
    {
        return lo & 16383u;
    }
    if (which == 1u)
    {
        return ((lo >> uint(20)) & 4095u) | ((hi & 3u) << uint(12));
    }
    return (hi >> uint(8)) & 16383u;
}

static inline __attribute__((always_inline))
uint gs_tex_level_size(thread const uint& log2_size, thread const uint& level0)
{
    uint s = 1u << log2_size;
    s = s >> level0;
    return (s == 0u) ? 1u : s;
}

static inline __attribute__((always_inline))
uint gs_tex_level_blocks(thread const uint& psm, thread const uint& log2w, thread const uint& log2h, thread const uint& level0)
{
    uint param = log2w;
    uint param_1 = level0;
    uint w = gs_tex_level_size(param, param_1);
    uint param_2 = log2h;
    uint param_3 = level0;
    uint h = gs_tex_level_size(param_2, param_3);
    uint param_4 = psm;
    uint bytes = ((w * h) * gs_addr_bits(param_4)) / 8u;
    uint blocks = bytes / 256u;
    return (blocks == 0u) ? 1u : blocks;
}

static inline __attribute__((always_inline))
uint gs_mip_tbp(thread const uint& tex0_lo, thread const uint& tex0_hi, thread const uint& tex1_lo, thread const uint& m1lo, thread const uint& m1hi, thread const uint& m2lo, thread const uint& m2hi, thread const uint& level0)
{
    if (level0 == 0u)
    {
        uint param = tex0_lo;
        return gs_tex0_tbp0(param);
    }
    uint param_1 = tex1_lo;
    if (gs_tex1_mtba(param_1) == 0u)
    {
        if (level0 <= 3u)
        {
            uint param_2 = m1lo;
            uint param_3 = m1hi;
            uint param_4 = level0 - 1u;
            return gs_miptbp_tbp(param_2, param_3, param_4);
        }
        uint param_5 = m2lo;
        uint param_6 = m2hi;
        uint param_7 = level0 - 4u;
        return gs_miptbp_tbp(param_5, param_6, param_7);
    }
    uint param_8 = tex0_lo;
    uint psm = gs_tex0_psm(param_8);
    uint param_9 = tex0_lo;
    uint log2w = gs_tex0_tw(param_9);
    uint param_10 = tex0_lo;
    uint param_11 = tex0_hi;
    uint log2h = gs_tex0_th(param_10, param_11);
    uint param_12 = tex0_lo;
    uint base = gs_tex0_tbp0(param_12);
    for (uint n = 0u; n < level0; n++)
    {
        uint param_13 = psm;
        uint param_14 = log2w;
        uint param_15 = log2h;
        uint param_16 = n;
        base += gs_tex_level_blocks(param_13, param_14, param_15, param_16);
    }
    return base;
}

static inline __attribute__((always_inline))
uint gs_tex0_tbw(thread const uint& lo)
{
    return (lo >> uint(14)) & 63u;
}

static inline __attribute__((always_inline))
uint gs_miptbp_tbw(thread const uint& lo, thread const uint& hi, thread const uint& which)
{
    if (which == 0u)
    {
        return (lo >> uint(14)) & 63u;
    }
    if (which == 1u)
    {
        return (hi >> uint(2)) & 63u;
    }
    return (hi >> uint(22)) & 63u;
}

static inline __attribute__((always_inline))
uint gs_mip_tbw(thread const uint& tex0_lo, thread const uint& tex1_lo, thread const uint& m1lo, thread const uint& m1hi, thread const uint& m2lo, thread const uint& m2hi, thread const uint& level0)
{
    if (level0 == 0u)
    {
        uint param = tex0_lo;
        return gs_tex0_tbw(param);
    }
    uint param_1 = tex1_lo;
    if (gs_tex1_mtba(param_1) == 0u)
    {
        if (level0 <= 3u)
        {
            uint param_2 = m1lo;
            uint param_3 = m1hi;
            uint param_4 = level0 - 1u;
            return gs_miptbp_tbw(param_2, param_3, param_4);
        }
        uint param_5 = m2lo;
        uint param_6 = m2hi;
        uint param_7 = level0 - 4u;
        return gs_miptbp_tbw(param_5, param_6, param_7);
    }
    uint param_8 = tex0_lo;
    uint bw = gs_tex0_tbw(param_8) >> level0;
    return (bw == 0u) ? 1u : bw;
}

static inline __attribute__((always_inline))
uint gs_clamp_wms(thread const uint& lo)
{
    return lo & 3u;
}

static inline __attribute__((always_inline))
uint gs_clamp_wmt(thread const uint& lo)
{
    return (lo >> uint(2)) & 3u;
}

static inline __attribute__((always_inline))
uint gs_clamp_minu(thread const uint& lo)
{
    return (lo >> uint(4)) & 1023u;
}

static inline __attribute__((always_inline))
uint gs_clamp_maxu(thread const uint& lo)
{
    return (lo >> uint(14)) & 1023u;
}

static inline __attribute__((always_inline))
uint gs_clamp_minv(thread const uint& lo, thread const uint& hi)
{
    return ((lo >> uint(24)) & 255u) | ((hi & 3u) << uint(8));
}

static inline __attribute__((always_inline))
uint gs_clamp_maxv(thread const uint& hi)
{
    return (hi >> uint(2)) & 1023u;
}

static inline __attribute__((always_inline))
int gs_iclamp(thread const int& v, thread const int& lo, thread const int& hi)
{
    int _1840;
    if (v < lo)
    {
        _1840 = lo;
    }
    else
    {
        _1840 = (v > hi) ? hi : v;
    }
    return _1840;
}

static inline __attribute__((always_inline))
int gs_tex_wrap(thread const int& c, thread const uint& mode, thread const uint& minv, thread const uint& maxv, thread const uint& size)
{
    if (mode == 0u)
    {
        return c & int(size - 1u);
    }
    if (mode == 1u)
    {
        int param = c;
        int param_1 = 0;
        int param_2 = int(size) - 1;
        return gs_iclamp(param, param_1, param_2);
    }
    if (mode == 2u)
    {
        int param_3 = c;
        int param_4 = int(minv);
        int param_5 = int(maxv);
        return gs_iclamp(param_3, param_4, param_5);
    }
    return (c & int(minv)) | int(maxv);
}

static inline __attribute__((always_inline))
uint gs_word_mask(thread const uint& psm)
{
    if ((psm == 1u) || (psm == 49u))
    {
        return 16777215u;
    }
    if (psm == 27u)
    {
        return 4278190080u;
    }
    if (psm == 36u)
    {
        return 251658240u;
    }
    if (psm == 44u)
    {
        return 4026531840u;
    }
    return 4294967295u;
}

static inline __attribute__((always_inline))
uint gs_word_shift(thread const uint& psm)
{
    if ((psm == 27u) || (psm == 36u))
    {
        return 24u;
    }
    if (psm == 44u)
    {
        return 28u;
    }
    return 0u;
}

static inline __attribute__((always_inline))
uint tex_fetch_raw(thread const uint& psm, thread const uint& base, thread const uint& bw, thread const int& x, thread const int& y, device GsBuffer* (&g_buf)[16])
{
    uint param = psm;
    uint param_1 = base;
    uint param_2 = bw;
    uint param_3 = uint(x);
    uint param_4 = uint(y);
    uint addr = gs_pixel_addr(param, param_1, param_2, param_3, param_4);
    uint param_5 = psm;
    uint bits = gs_addr_bits(param_5);
    if (bits == 32u)
    {
        uint w = g_buf[0]->data[addr & 1048575u];
        uint param_6 = psm;
        uint param_7 = psm;
        return (w & gs_word_mask(param_6)) >> gs_word_shift(param_7);
    }
    uint word = (addr * bits) >> uint(5);
    uint shift = (addr * bits) & 31u;
    uint w_1 = g_buf[0]->data[word & 1048575u];
    return (w_1 >> shift) & ((1u << bits) - 1u);
}

static inline __attribute__((always_inline))
uint gs_tex_index_bits(thread const uint& psm)
{
    if ((psm == 19u) || (psm == 27u))
    {
        return 8u;
    }
    if (((psm == 20u) || (psm == 36u)) || (psm == 44u))
    {
        return 4u;
    }
    return 0u;
}

static inline __attribute__((always_inline))
uint gs_tex0_csm(thread const uint& hi)
{
    return (hi >> uint(23)) & 1u;
}

static inline __attribute__((always_inline))
uint gs_tex0_csa(thread const uint& hi)
{
    return (hi >> uint(24)) & 31u;
}

static inline __attribute__((always_inline))
uint gs_clut_slot_csm1_8(thread const uint& index)
{
    uint bit3 = (index >> uint(3)) & 1u;
    uint bit4 = (index >> uint(4)) & 1u;
    return ((index & 231u) | (bit3 << uint(4))) | (bit4 << uint(3));
}

static inline __attribute__((always_inline))
uint gs_clut_entry(thread const uint& index, thread const uint& bits_per_index, thread const uint& csm, thread const uint& csa)
{
    if (bits_per_index == 4u)
    {
        return (csa * 16u) + (index & 15u);
    }
    if (csm == 0u)
    {
        uint param = index & 255u;
        return gs_clut_slot_csm1_8(param);
    }
    return index & 255u;
}

static inline __attribute__((always_inline))
uint gs_tex0_cpsm(thread const uint& hi)
{
    return (hi >> uint(19)) & 15u;
}

static inline __attribute__((always_inline))
uint gs_texa_ta1(thread const uint& texa)
{
    return (texa >> uint(16)) & 255u;
}

static inline __attribute__((always_inline))
uint gs_texa_ta0(thread const uint& texa)
{
    return texa & 255u;
}

static inline __attribute__((always_inline))
uint gs_texa_aem(thread const uint& texa)
{
    return (texa >> uint(8)) & 1u;
}

static inline __attribute__((always_inline))
uint gs_texa_expand16(thread const uint& v16, thread const uint& texa)
{
    uint r = (v16 & 31u) << uint(3);
    uint g = ((v16 >> uint(5)) & 31u) << uint(3);
    uint b = ((v16 >> uint(10)) & 31u) << uint(3);
    uint abit = (v16 >> uint(15)) & 1u;
    uint _2079;
    if (abit != 0u)
    {
        uint param = texa;
        _2079 = gs_texa_ta1(param);
    }
    else
    {
        uint param_1 = texa;
        _2079 = gs_texa_ta0(param_1);
    }
    uint a = _2079;
    uint param_2 = texa;
    bool _2096 = (gs_texa_aem(param_2) != 0u) && (abit == 0u);
    bool _2103;
    if (_2096)
    {
        _2103 = (v16 & 32767u) == 0u;
    }
    else
    {
        _2103 = _2096;
    }
    if (_2103)
    {
        a = 0u;
    }
    return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
}

static inline __attribute__((always_inline))
uint clut_lookup(thread const uint& index, thread const uint& index_bits, thread const uint& t0hi, thread const uint& clut_base, thread const uint& texa, device GsBuffer* (&g_buf)[16])
{
    uint param = t0hi;
    uint param_1 = t0hi;
    uint param_2 = index;
    uint param_3 = index_bits;
    uint param_4 = gs_tex0_csm(param);
    uint param_5 = gs_tex0_csa(param_1);
    uint entry = gs_clut_entry(param_2, param_3, param_4, param_5);
    uint param_6 = t0hi;
    if (gs_tex0_cpsm(param_6) == 0u)
    {
        return g_buf[4]->data[clut_base + (entry & 255u)];
    }
    uint w = g_buf[4]->data[clut_base + ((entry >> uint(1)) & 255u)];
    uint _3105;
    if ((entry & 1u) != 0u)
    {
        _3105 = w >> uint(16);
    }
    else
    {
        _3105 = w & 65535u;
    }
    uint hw = _3105;
    uint param_7 = hw;
    uint param_8 = texa;
    return gs_texa_expand16(param_7, param_8);
}

static inline __attribute__((always_inline))
uint gs_texa_expand24(thread const uint& v24, thread const uint& texa)
{
    uint rgb = v24 & 16777215u;
    uint param = texa;
    uint a = gs_texa_ta0(param);
    uint param_1 = texa;
    if ((gs_texa_aem(param_1) != 0u) && (rgb == 0u))
    {
        a = 0u;
    }
    return rgb | (a << uint(24));
}

static inline __attribute__((always_inline))
uint gs_tex_direct_rgba(thread const uint& psm, thread const uint& raw, thread const uint& texa)
{
    if ((psm == 1u) || (psm == 49u))
    {
        uint param = raw;
        uint param_1 = texa;
        return gs_texa_expand24(param, param_1);
    }
    if ((((psm == 2u) || (psm == 10u)) || (psm == 50u)) || (psm == 58u))
    {
        uint param_2 = raw & 65535u;
        uint param_3 = texa;
        return gs_texa_expand16(param_2, param_3);
    }
    return raw;
}

static inline __attribute__((always_inline))
uint tex_texel(thread const uint& psm, thread const uint& base, thread const uint& bw, thread const int& x, thread const int& y, thread const uint& t0hi, thread const uint& clut_base, thread const uint& texa, device GsBuffer* (&g_buf)[16])
{
    uint param = psm;
    uint param_1 = base;
    uint param_2 = bw;
    int param_3 = x;
    int param_4 = y;
    uint raw = tex_fetch_raw(param, param_1, param_2, param_3, param_4, g_buf);
    uint param_5 = psm;
    uint ibits = gs_tex_index_bits(param_5);
    if (ibits != 0u)
    {
        uint param_6 = raw;
        uint param_7 = ibits;
        uint param_8 = t0hi;
        uint param_9 = clut_base;
        uint param_10 = texa;
        return clut_lookup(param_6, param_7, param_8, param_9, param_10, g_buf);
    }
    uint param_11 = psm;
    uint param_12 = raw;
    uint param_13 = texa;
    return gs_tex_direct_rgba(param_11, param_12, param_13);
}

static inline __attribute__((always_inline))
uint gs_tex_bilerp(thread const uint& c00, thread const uint& c10, thread const uint& c01, thread const uint& c11, thread const uint& fu, thread const uint& fv)
{
    uint out_v = 0u;
    uint w00 = (16u - fu) * (16u - fv);
    uint w10 = fu * (16u - fv);
    uint w01 = (16u - fu) * fv;
    uint w11 = fu * fv;
    for (uint i = 0u; i < 4u; i++)
    {
        uint v = (((((c00 >> (i * 8u)) & 255u) * w00) + (((c10 >> (i * 8u)) & 255u) * w10)) + (((c01 >> (i * 8u)) & 255u) * w01)) + (((c11 >> (i * 8u)) & 255u) * w11);
        out_v |= ((((v + 128u) >> uint(8)) & 255u) << (i * 8u));
    }
    return out_v;
}

static inline __attribute__((always_inline))
uint tex_level(thread const uint& t0lo, thread const uint& t0hi, thread const uint& t1lo, thread const uint& m1lo, thread const uint& m1hi, thread const uint& m2lo, thread const uint& m2hi, thread const uint& clo, thread const uint& chi, thread const uint& texa, thread const uint& clut_base, thread const int& u16, thread const int& v16, thread const uint& level0, thread const bool& linear, device GsBuffer* (&g_buf)[16])
{
    uint param = t0lo;
    uint psm = gs_tex0_psm(param);
    uint param_1 = t0lo;
    uint param_2 = t0hi;
    uint param_3 = t1lo;
    uint param_4 = m1lo;
    uint param_5 = m1hi;
    uint param_6 = m2lo;
    uint param_7 = m2hi;
    uint param_8 = level0;
    uint base = gs_mip_tbp(param_1, param_2, param_3, param_4, param_5, param_6, param_7, param_8);
    uint param_9 = t0lo;
    uint param_10 = t1lo;
    uint param_11 = m1lo;
    uint param_12 = m1hi;
    uint param_13 = m2lo;
    uint param_14 = m2hi;
    uint param_15 = level0;
    uint bw = gs_mip_tbw(param_9, param_10, param_11, param_12, param_13, param_14, param_15);
    uint param_16 = t0lo;
    uint param_17 = gs_tex0_tw(param_16);
    uint param_18 = level0;
    uint w = gs_tex_level_size(param_17, param_18);
    uint param_19 = t0lo;
    uint param_20 = t0hi;
    uint param_21 = gs_tex0_th(param_19, param_20);
    uint param_22 = level0;
    uint h = gs_tex_level_size(param_21, param_22);
    uint param_23 = clo;
    uint wms = gs_clamp_wms(param_23);
    uint param_24 = clo;
    uint wmt = gs_clamp_wmt(param_24);
    uint param_25 = clo;
    uint minu = gs_clamp_minu(param_25);
    uint param_26 = clo;
    uint maxu = gs_clamp_maxu(param_26);
    uint param_27 = clo;
    uint param_28 = chi;
    uint minv = gs_clamp_minv(param_27, param_28);
    uint param_29 = chi;
    uint maxv = gs_clamp_maxv(param_29);
    int su = u16 >> int(level0);
    int sv = v16 >> int(level0);
    if (!linear)
    {
        int param_30 = su >> 4;
        uint param_31 = wms;
        uint param_32 = minu;
        uint param_33 = maxu;
        uint param_34 = w;
        int x = gs_tex_wrap(param_30, param_31, param_32, param_33, param_34);
        int param_35 = sv >> 4;
        uint param_36 = wmt;
        uint param_37 = minv;
        uint param_38 = maxv;
        uint param_39 = h;
        int y = gs_tex_wrap(param_35, param_36, param_37, param_38, param_39);
        uint param_40 = psm;
        uint param_41 = base;
        uint param_42 = bw;
        int param_43 = x;
        int param_44 = y;
        uint param_45 = t0hi;
        uint param_46 = clut_base;
        uint param_47 = texa;
        return tex_texel(param_40, param_41, param_42, param_43, param_44, param_45, param_46, param_47, g_buf);
    }
    int uu = su - 8;
    int vv = sv - 8;
    int param_48 = uu >> 4;
    uint param_49 = wms;
    uint param_50 = minu;
    uint param_51 = maxu;
    uint param_52 = w;
    int x0 = gs_tex_wrap(param_48, param_49, param_50, param_51, param_52);
    int param_53 = (uu >> 4) + 1;
    uint param_54 = wms;
    uint param_55 = minu;
    uint param_56 = maxu;
    uint param_57 = w;
    int x1 = gs_tex_wrap(param_53, param_54, param_55, param_56, param_57);
    int param_58 = vv >> 4;
    uint param_59 = wmt;
    uint param_60 = minv;
    uint param_61 = maxv;
    uint param_62 = h;
    int y0 = gs_tex_wrap(param_58, param_59, param_60, param_61, param_62);
    int param_63 = (vv >> 4) + 1;
    uint param_64 = wmt;
    uint param_65 = minv;
    uint param_66 = maxv;
    uint param_67 = h;
    int y1 = gs_tex_wrap(param_63, param_64, param_65, param_66, param_67);
    uint fu = uint(uu & 15);
    uint fv = uint(vv & 15);
    uint param_68 = psm;
    uint param_69 = base;
    uint param_70 = bw;
    int param_71 = x0;
    int param_72 = y0;
    uint param_73 = t0hi;
    uint param_74 = clut_base;
    uint param_75 = texa;
    uint param_76 = psm;
    uint param_77 = base;
    uint param_78 = bw;
    int param_79 = x1;
    int param_80 = y0;
    uint param_81 = t0hi;
    uint param_82 = clut_base;
    uint param_83 = texa;
    uint param_84 = psm;
    uint param_85 = base;
    uint param_86 = bw;
    int param_87 = x0;
    int param_88 = y1;
    uint param_89 = t0hi;
    uint param_90 = clut_base;
    uint param_91 = texa;
    uint param_92 = psm;
    uint param_93 = base;
    uint param_94 = bw;
    int param_95 = x1;
    int param_96 = y1;
    uint param_97 = t0hi;
    uint param_98 = clut_base;
    uint param_99 = texa;
    uint param_100 = tex_texel(param_68, param_69, param_70, param_71, param_72, param_73, param_74, param_75, g_buf);
    uint param_101 = tex_texel(param_76, param_77, param_78, param_79, param_80, param_81, param_82, param_83, g_buf);
    uint param_102 = tex_texel(param_84, param_85, param_86, param_87, param_88, param_89, param_90, param_91, g_buf);
    uint param_103 = tex_texel(param_92, param_93, param_94, param_95, param_96, param_97, param_98, param_99, g_buf);
    uint param_104 = fu;
    uint param_105 = fv;
    return gs_tex_bilerp(param_100, param_101, param_102, param_103, param_104, param_105);
}

static inline __attribute__((always_inline))
uint gs_tex_mix16(thread const uint& a, thread const uint& b, thread const uint& f)
{
    uint out_v = 0u;
    for (uint i = 0u; i < 4u; i++)
    {
        uint va = (a >> (i * 8u)) & 255u;
        uint vb = (b >> (i * 8u)) & 255u;
        out_v |= ((((((va * (16u - f)) + (vb * f)) + 8u) >> uint(4)) & 255u) << (i * 8u));
    }
    return out_v;
}

static inline __attribute__((always_inline))
uint tex_sample(thread const uint& t0lo, thread const uint& t0hi, thread const uint& t1lo, thread const uint& t1hi, thread const uint& m1lo, thread const uint& m1hi, thread const uint& m2lo, thread const uint& m2hi, thread const uint& clo, thread const uint& chi, thread const uint& texa, thread const uint& clut_base, thread const int& u16, thread const int& v16, thread const float& q, device GsBuffer* (&g_buf)[16])
{
    uint param = t1lo;
    uint mxl = gs_tex1_mxl(param);
    uint param_1 = t1lo;
    uint param_2 = t1lo;
    uint param_3 = t1hi;
    uint param_4 = gs_tex1_lcm(param_1);
    uint param_5 = gs_tex1_l(param_2);
    int param_6 = gs_tex1_k(param_3);
    float param_7 = q;
    uint param_8 = mxl;
    int lod = gs_tex_lod(param_4, param_5, param_6, param_7, param_8);
    uint level0 = 0u;
    uint lfrac = 0u;
    uint filt;
    if (lod < 0)
    {
        uint param_9 = t1lo;
        filt = gs_tex1_mmag(param_9);
    }
    else
    {
        uint param_10 = t1lo;
        filt = gs_tex1_mmin(param_10);
        level0 = min((uint(lod) >> uint(4)), mxl);
        lfrac = uint(lod) & 15u;
    }
    bool linear = ((filt == 1u) || (filt == 4u)) || (filt == 5u);
    bool mipped = filt >= 2u;
    if (!mipped)
    {
        level0 = 0u;
    }
    uint param_11 = t0lo;
    uint param_12 = t0hi;
    uint param_13 = t1lo;
    uint param_14 = m1lo;
    uint param_15 = m1hi;
    uint param_16 = m2lo;
    uint param_17 = m2hi;
    uint param_18 = clo;
    uint param_19 = chi;
    uint param_20 = texa;
    uint param_21 = clut_base;
    int param_22 = u16;
    int param_23 = v16;
    uint param_24 = level0;
    bool param_25 = linear;
    uint c = tex_level(param_11, param_12, param_13, param_14, param_15, param_16, param_17, param_18, param_19, param_20, param_21, param_22, param_23, param_24, param_25, g_buf);
    bool blend_levels = (filt == 3u) || (filt == 5u);
    if ((blend_levels && (lfrac != 0u)) && (level0 < mxl))
    {
        uint param_26 = t0lo;
        uint param_27 = t0hi;
        uint param_28 = t1lo;
        uint param_29 = m1lo;
        uint param_30 = m1hi;
        uint param_31 = m2lo;
        uint param_32 = m2hi;
        uint param_33 = clo;
        uint param_34 = chi;
        uint param_35 = texa;
        uint param_36 = clut_base;
        int param_37 = u16;
        int param_38 = v16;
        uint param_39 = level0 + 1u;
        bool param_40 = linear;
        uint c2 = tex_level(param_26, param_27, param_28, param_29, param_30, param_31, param_32, param_33, param_34, param_35, param_36, param_37, param_38, param_39, param_40, g_buf);
        uint param_41 = c;
        uint param_42 = c2;
        uint param_43 = lfrac;
        c = gs_tex_mix16(param_41, param_42, param_43);
    }
    return c;
}

static inline __attribute__((always_inline))
uint gs_tex0_tfx(thread const uint& hi)
{
    return (hi >> uint(3)) & 3u;
}

static inline __attribute__((always_inline))
uint gs_tex0_tcc(thread const uint& hi)
{
    return (hi >> uint(2)) & 1u;
}

static inline __attribute__((always_inline))
uint gs_tex_function(thread const uint& texel, thread const uint& frag, thread const uint& tfx, thread const uint& tcc)
{
    uint af = (frag >> uint(24)) & 255u;
    uint at = (texel >> uint(24)) & 255u;
    uint out_rgb = 0u;
    int v;
    for (uint i = 0u; i < 3u; i++)
    {
        uint ct = (texel >> (i * 8u)) & 255u;
        uint cf = (frag >> (i * 8u)) & 255u;
        if (tfx == 1u)
        {
            v = int(ct);
        }
        else
        {
            v = int((ct * cf) >> uint(7));
            if ((tfx == 2u) || (tfx == 3u))
            {
                v += int(af);
            }
        }
        int param = v;
        int param_1 = 0;
        int param_2 = 255;
        out_rgb |= (uint(gs_iclamp(param, param_1, param_2)) << (i * 8u));
    }
    uint out_a;
    if (tcc == 0u)
    {
        out_a = af;
    }
    else
    {
        if (tfx == 0u)
        {
            int param_3 = int((at * af) >> uint(7));
            int param_4 = 0;
            int param_5 = 255;
            out_a = uint(gs_iclamp(param_3, param_4, param_5));
        }
        else
        {
            if (tfx == 2u)
            {
                int param_6 = int(at + af);
                int param_7 = 0;
                int param_8 = 255;
                out_a = uint(gs_iclamp(param_6, param_7, param_8));
            }
            else
            {
                out_a = at;
            }
        }
    }
    return out_rgb | (out_a << uint(24));
}

static inline __attribute__((always_inline))
uint gs_aa_alpha(thread const float& cover)
{
    int a = int((cover * 128.0) + 0.5);
    if (a < 0)
    {
        a = 0;
    }
    if (a > 128)
    {
        a = 128;
    }
    return uint(a);
}

static inline __attribute__((always_inline))
int dimx_entry(thread const uint& px, thread const uint& py, constant Push& pc)
{
    uint i = ((py & 3u) * 4u) + (px & 3u);
    uint _3617;
    if (i < 8u)
    {
        _3617 = pc.dimx0;
    }
    else
    {
        _3617 = pc.dimx1;
    }
    uint w = _3617;
    uint _3629;
    if (i < 8u)
    {
        _3629 = i * 4u;
    }
    else
    {
        _3629 = (i - 8u) * 4u;
    }
    uint sh = _3629;
    int d = int((w >> sh) & 7u);
    int _3647;
    if (d > 3)
    {
        _3647 = d - 8;
    }
    else
    {
        _3647 = d;
    }
    return _3647;
}

static inline __attribute__((always_inline))
uint gs_pack16(thread const uint& rgba)
{
    return ((((rgba & 255u) >> uint(3)) | ((((rgba >> uint(8)) & 255u) >> uint(3)) << uint(5))) | ((((rgba >> uint(16)) & 255u) >> uint(3)) << uint(10))) | ((((rgba >> uint(24)) & 255u) >> uint(7)) << uint(15));
}

static inline __attribute__((always_inline))
uint gs_frame_pack(thread const uint& psm, thread const uint& rgba)
{
    if ((psm == 2u) || (psm == 10u))
    {
        uint param = rgba;
        return gs_pack16(param);
    }
    return rgba;
}

static inline __attribute__((always_inline))
uint gs_alias_word(thread const uint& frame_psm, thread const uint& rgba, thread const uint& z_psm, thread const uint& z, thread const bool& wrote_z)
{
    uint param = frame_psm;
    uint param_1 = rgba;
    uint bits = gs_frame_pack(param, param_1);
    if (!wrote_z)
    {
        return bits;
    }
    uint param_2 = z_psm;
    uint zm = gs_z_precision_mask(param_2);
    return (bits & (~zm)) | (z & zm);
}

static inline __attribute__((always_inline))
uint gs_frame_unpack(thread const uint& psm, thread const uint& bits)
{
    if ((psm == 2u) || (psm == 10u))
    {
        uint param = bits & 65535u;
        return gs_expand16(param);
    }
    return bits;
}

static inline __attribute__((always_inline))
void shade(thread const uint& pi, thread const int& px, thread const int& py, thread const int& sxp, thread const int& syp, thread const uint& idx, device GsBuffer* (&g_buf)[16], constant Push& pc, threadgroup spvUnsafeArray<uint, 256>& s_color, threadgroup spvUnsafeArray<uint, 256>& s_depth, thread bool& g_wrote_color, thread bool& g_wrote_z, thread bool& g_alias)
{
    uint base = pi * 50u;
    uint flags = g_buf[1]->data[base + 0u];
    uint kind = flags & 7u;
    uint scx = g_buf[1]->data[base + 21u];
    uint scy = g_buf[1]->data[base + 22u];
    bool _3686 = px < int(scx & 65535u);
    bool _3695;
    if (!_3686)
    {
        _3695 = px > int(scx >> uint(16));
    }
    else
    {
        _3695 = _3686;
    }
    if (_3695)
    {
        return;
    }
    bool _3703 = py < int(scy & 65535u);
    bool _3712;
    if (!_3703)
    {
        _3712 = py > int(scy >> uint(16));
    }
    else
    {
        _3712 = _3703;
    }
    if (_3712)
    {
        return;
    }
    uint param = (flags >> 11u) & 3u;
    int param_1 = py;
    if (!gs_scanmsk_draws(param, param_1))
    {
        return;
    }
    int x0 = int(g_buf[1]->data[base + 1u]);
    int y0 = int(g_buf[1]->data[base + 2u]);
    int x1 = int(g_buf[1]->data[base + 3u]);
    int y1 = int(g_buf[1]->data[base + 4u]);
    int x2 = int(g_buf[1]->data[base + 5u]);
    int y2 = int(g_buf[1]->data[base + 6u]);
    float w0 = 0.0;
    float w1 = 0.0;
    float w2 = 0.0;
    float wsum = 1.0;
    float tline = 0.0;
    bool _3771 = (flags & 256u) != 0u;
    bool _3777;
    if (_3771)
    {
        _3777 = pc.samples == 1u;
    }
    else
    {
        _3777 = _3771;
    }
    bool _3785;
    if (_3777)
    {
        _3785 = (kind == 3u) || (kind == 1u);
    }
    else
    {
        _3785 = _3777;
    }
    bool aa1 = _3785;
    bool abe = (flags & 128u) != 0u;
    float cover = 1.0;
    if (kind == 3u)
    {
        int param_2 = x1 - x0;
        int param_3 = syp - y0;
        int param_4 = y1 - y0;
        int param_5 = sxp - x0;
        int2 ea = gs_cross64(param_2, param_3, param_4, param_5);
        int param_6 = x2 - x1;
        int param_7 = syp - y1;
        int param_8 = y2 - y1;
        int param_9 = sxp - x1;
        int2 eb = gs_cross64(param_6, param_7, param_8, param_9);
        int param_10 = x0 - x2;
        int param_11 = syp - y2;
        int param_12 = y0 - y2;
        int param_13 = sxp - x2;
        int2 ec = gs_cross64(param_10, param_11, param_12, param_13);
        int2 param_14 = ea;
        int param_15 = x1 - x0;
        int param_16 = y1 - y0;
        bool _3860 = gs_edge_accept_value(param_14, param_15, param_16);
        bool _3874;
        if (_3860)
        {
            int2 param_17 = eb;
            int param_18 = x2 - x1;
            int param_19 = y2 - y1;
            _3874 = gs_edge_accept_value(param_17, param_18, param_19);
        }
        else
        {
            _3874 = _3860;
        }
        bool _3888;
        if (_3874)
        {
            int2 param_20 = ec;
            int param_21 = x0 - x2;
            int param_22 = y0 - y2;
            _3888 = gs_edge_accept_value(param_20, param_21, param_22);
        }
        else
        {
            _3888 = _3874;
        }
        bool inside = _3888;
        if (aa1)
        {
            int param_23 = x0;
            int param_24 = y0;
            int param_25 = x1;
            int param_26 = y1;
            int param_27 = x2;
            int param_28 = y2;
            int param_29 = sxp;
            int param_30 = syp;
            cover = gs_aa_triangle_cover(param_23, param_24, param_25, param_26, param_27, param_28, param_29, param_30);
            if (cover <= 0.0)
            {
                return;
            }
            if ((!inside) && (!abe))
            {
                return;
            }
        }
        else
        {
            if (!inside)
            {
                return;
            }
        }
        int2 param_31 = eb;
        w0 = gs_i64_float(param_31);
        int2 param_32 = ec;
        w1 = gs_i64_float(param_32);
        int2 param_33 = ea;
        w2 = gs_i64_float(param_33);
        wsum = (w0 + w1) + w2;
        if (wsum == 0.0)
        {
            wsum = 1.0;
        }
    }
    else
    {
        if (kind == 2u)
        {
            int param_34 = x0;
            int param_35 = y0;
            int param_36 = x1;
            int param_37 = y1;
            int param_38 = sxp;
            int param_39 = syp;
            if (!gs_covers_sprite_at(param_34, param_35, param_36, param_37, param_38, param_39))
            {
                return;
            }
        }
        else
        {
            if (kind == 0u)
            {
                int param_40 = x0;
                int param_41 = y0;
                int param_42 = px;
                int param_43 = py;
                if (!gs_covers_point(param_40, param_41, param_42, param_43))
                {
                    return;
                }
            }
            else
            {
                if ((flags & 1024u) != 0u)
                {
                    int param_44 = x0;
                    int param_45 = y0;
                    int param_46 = px;
                    int param_47 = py;
                    if (!gs_covers_line_dot(param_44, param_45, param_46, param_47))
                    {
                        return;
                    }
                }
                else
                {
                    bool major_x = (flags & 8u) != 0u;
                    int m0 = major_x ? x0 : y0;
                    int m1 = major_x ? x1 : y1;
                    int p = major_x ? px : py;
                    int smin = major_x ? syp : sxp;
                    int _4033;
                    if (major_x)
                    {
                        _4033 = int(g_buf[1]->data[base + 7u]);
                    }
                    else
                    {
                        _4033 = int(g_buf[1]->data[base + 8u]);
                    }
                    int refp = _4033;
                    int slope = int(g_buf[1]->data[base + 25u]);
                    int lo = min(m0, m1);
                    int hi = max(m0, m1);
                    int param_48 = lo;
                    int param_49 = hi;
                    int param_50 = p;
                    if (!gs_covers_line_span(param_48, param_49, param_50))
                    {
                        return;
                    }
                    if (aa1)
                    {
                        int param_51 = x2;
                        int param_52 = slope;
                        int param_53 = refp;
                        int param_54 = p;
                        int param_55 = smin;
                        cover = gs_aa_line_cover(param_51, param_52, param_53, param_54, param_55);
                        if (cover <= 0.0)
                        {
                            return;
                        }
                        int param_56 = lo;
                        int param_57 = hi;
                        int param_58 = x2;
                        int param_59 = slope;
                        int param_60 = refp;
                        int param_61 = p;
                        int param_62 = smin;
                        if ((!gs_covers_line_at(param_56, param_57, param_58, param_59, param_60, param_61, param_62)) && (!abe))
                        {
                            return;
                        }
                    }
                    else
                    {
                        int param_63 = lo;
                        int param_64 = hi;
                        int param_65 = x2;
                        int param_66 = slope;
                        int param_67 = refp;
                        int param_68 = p;
                        int param_69 = smin;
                        if (!gs_covers_line_at(param_63, param_64, param_65, param_66, param_67, param_68, param_69))
                        {
                            return;
                        }
                    }
                    float _4137;
                    if (m1 != m0)
                    {
                        _4137 = float(((p * 16) + 8) - m0) / float(m1 - m0);
                    }
                    else
                    {
                        _4137 = 0.0;
                    }
                    tline = _4137;
                    tline = fast::clamp(tline, 0.0, 1.0);
                }
            }
        }
    }
    uint dxp = uint(px - int(g_buf[1]->data[base + 7u]));
    uint dyp = uint(py - int(g_buf[1]->data[base + 8u]));
    uint param_70 = g_buf[1]->data[base + 9u];
    uint param_71 = g_buf[1]->data[base + 10u];
    uint param_72 = g_buf[1]->data[base + 11u];
    uint param_73 = g_buf[1]->data[base + 12u];
    uint param_74 = g_buf[1]->data[base + 13u];
    uint param_75 = g_buf[1]->data[base + 14u];
    uint param_76 = dxp;
    uint param_77 = dyp;
    uint param_78 = pc.z_psm;
    uint zsrc = gs_z_at(param_70, param_71, param_72, param_73, param_74, param_75, param_76, param_77) & gs_z_precision_mask(param_78);
    bool iip = (flags & 16u) != 0u;
    uint rgba;
    if ((kind == 3u) && iip)
    {
        uint c0 = g_buf[1]->data[base + 15u];
        uint c1 = g_buf[1]->data[base + 16u];
        uint c2 = g_buf[1]->data[base + 17u];
        float inv = 1.0 / wsum;
        uint acc = 0u;
        for (uint i = 0u; i < 4u; i++)
        {
            uint param_79 = c0;
            uint param_80 = i;
            uint param_81 = c1;
            uint param_82 = i;
            uint param_83 = c2;
            uint param_84 = i;
            float v = (((w0 * float(chan(param_79, param_80))) + (w1 * float(chan(param_81, param_82)))) + (w2 * float(chan(param_83, param_84)))) * inv;
            int param_85 = int(floor(v + 0.5));
            acc |= (uint(clamp255(param_85)) << (i * 8u));
        }
        rgba = acc;
    }
    else
    {
        if ((kind == 1u) && iip)
        {
            uint c0_1 = g_buf[1]->data[base + 15u];
            uint c1_1 = g_buf[1]->data[base + 16u];
            uint acc_1 = 0u;
            for (uint i_1 = 0u; i_1 < 4u; i_1++)
            {
                uint param_86 = c0_1;
                uint param_87 = i_1;
                uint param_88 = c1_1;
                uint param_89 = i_1;
                float v_1 = mix(float(chan(param_86, param_87)), float(chan(param_88, param_89)), tline);
                int param_90 = int(floor(v_1 + 0.5));
                acc_1 |= (uint(clamp255(param_90)) << (i_1 * 8u));
            }
            rgba = acc_1;
        }
        else
        {
            rgba = g_buf[1]->data[base + 18u];
        }
    }
    if ((flags & 32u) != 0u)
    {
        uint t0lo = g_buf[1]->data[base + 26u];
        uint t0hi = g_buf[1]->data[base + 27u];
        bool fst = (flags & 512u) != 0u;
        float fu = 0.0;
        float fv = 0.0;
        float fs = 0.0;
        float ft = 0.0;
        float fq = 1.0;
        if (kind == 3u)
        {
            float inv_1 = 1.0 / wsum;
            if (fst)
            {
                uint a0 = g_buf[1]->data[base + 38u];
                uint a1 = g_buf[1]->data[base + 39u];
                uint a2 = g_buf[1]->data[base + 40u];
                fu = (((w0 * float(a0 & 65535u)) + (w1 * float(a1 & 65535u))) + (w2 * float(a2 & 65535u))) * inv_1;
                fv = (((w0 * float(a0 >> uint(16))) + (w1 * float(a1 >> uint(16)))) + (w2 * float(a2 >> uint(16)))) * inv_1;
            }
            else
            {
                fs = (((w0 * as_type<float>(g_buf[1]->data[base + 41u])) + (w1 * as_type<float>(g_buf[1]->data[base + 44u]))) + (w2 * as_type<float>(g_buf[1]->data[base + 47u]))) * inv_1;
                ft = (((w0 * as_type<float>(g_buf[1]->data[base + 42u])) + (w1 * as_type<float>(g_buf[1]->data[base + 45u]))) + (w2 * as_type<float>(g_buf[1]->data[base + 48u]))) * inv_1;
                fq = (((w0 * as_type<float>(g_buf[1]->data[base + 43u])) + (w1 * as_type<float>(g_buf[1]->data[base + 46u]))) + (w2 * as_type<float>(g_buf[1]->data[base + 49u]))) * inv_1;
            }
        }
        else
        {
            if (kind == 2u)
            {
                float _4539;
                if (x1 != x0)
                {
                    _4539 = float(sxp - x0) / float(x1 - x0);
                }
                else
                {
                    _4539 = 0.0;
                }
                float tx = _4539;
                float _4557;
                if (y1 != y0)
                {
                    _4557 = float(syp - y0) / float(y1 - y0);
                }
                else
                {
                    _4557 = 0.0;
                }
                float ty = _4557;
                if (fst)
                {
                    uint a0_1 = g_buf[1]->data[base + 38u];
                    uint a1_1 = g_buf[1]->data[base + 39u];
                    fu = mix(float(a0_1 & 65535u), float(a1_1 & 65535u), tx);
                    fv = mix(float(a0_1 >> uint(16)), float(a1_1 >> uint(16)), ty);
                }
                else
                {
                    fs = mix(as_type<float>(g_buf[1]->data[base + 41u]), as_type<float>(g_buf[1]->data[base + 44u]), tx);
                    ft = mix(as_type<float>(g_buf[1]->data[base + 42u]), as_type<float>(g_buf[1]->data[base + 45u]), ty);
                    fq = as_type<float>(g_buf[1]->data[base + 43u]);
                }
            }
            else
            {
                if (kind == 1u)
                {
                    if (fst)
                    {
                        uint a0_2 = g_buf[1]->data[base + 38u];
                        uint a1_2 = g_buf[1]->data[base + 39u];
                        fu = mix(float(a0_2 & 65535u), float(a1_2 & 65535u), tline);
                        fv = mix(float(a0_2 >> uint(16)), float(a1_2 >> uint(16)), tline);
                    }
                    else
                    {
                        fs = mix(as_type<float>(g_buf[1]->data[base + 41u]), as_type<float>(g_buf[1]->data[base + 44u]), tline);
                        ft = mix(as_type<float>(g_buf[1]->data[base + 42u]), as_type<float>(g_buf[1]->data[base + 45u]), tline);
                        fq = mix(as_type<float>(g_buf[1]->data[base + 43u]), as_type<float>(g_buf[1]->data[base + 46u]), tline);
                    }
                }
                else
                {
                    uint a0_3 = g_buf[1]->data[base + 38u];
                    fu = float(a0_3 & 65535u);
                    fv = float(a0_3 >> uint(16));
                    fs = as_type<float>(g_buf[1]->data[base + 41u]);
                    ft = as_type<float>(g_buf[1]->data[base + 42u]);
                    fq = as_type<float>(g_buf[1]->data[base + 43u]);
                }
            }
        }
        int u16;
        int v16;
        if (fst)
        {
            u16 = int(floor(fu + 0.5));
            v16 = int(floor(fv + 0.5));
            fq = 1.0;
        }
        else
        {
            float _4745;
            if (fq != 0.0)
            {
                _4745 = 1.0 / fq;
            }
            else
            {
                _4745 = 0.0;
            }
            float iq = _4745;
            uint param_91 = t0lo;
            u16 = int(floor((((fs * iq) * float(1u << gs_tex0_tw(param_91))) * 16.0) + 0.5));
            uint param_92 = t0lo;
            uint param_93 = t0hi;
            v16 = int(floor((((ft * iq) * float(1u << gs_tex0_th(param_92, param_93))) * 16.0) + 0.5));
        }
        uint param_94 = t0lo;
        uint param_95 = t0hi;
        uint param_96 = g_buf[1]->data[base + 28u];
        uint param_97 = g_buf[1]->data[base + 29u];
        uint param_98 = g_buf[1]->data[base + 34u];
        uint param_99 = g_buf[1]->data[base + 35u];
        uint param_100 = g_buf[1]->data[base + 36u];
        uint param_101 = g_buf[1]->data[base + 37u];
        uint param_102 = g_buf[1]->data[base + 30u];
        uint param_103 = g_buf[1]->data[base + 31u];
        uint param_104 = g_buf[1]->data[base + 32u];
        uint param_105 = g_buf[1]->data[base + 33u];
        int param_106 = u16;
        int param_107 = v16;
        float param_108 = fq;
        uint texel = tex_sample(param_94, param_95, param_96, param_97, param_98, param_99, param_100, param_101, param_102, param_103, param_104, param_105, param_106, param_107, param_108, g_buf);
        uint param_109 = t0hi;
        uint param_110 = t0hi;
        uint param_111 = texel;
        uint param_112 = rgba;
        uint param_113 = gs_tex0_tfx(param_109);
        uint param_114 = gs_tex0_tcc(param_110);
        rgba = gs_tex_function(param_111, param_112, param_113, param_114);
    }
    if ((flags & 64u) != 0u)
    {
        uint f;
        if ((kind == 3u) && iip)
        {
            uint fp = g_buf[1]->data[base + 19u];
            float v_2 = (((w0 * float(fp & 255u)) + (w1 * float((fp >> uint(8)) & 255u))) + (w2 * float((fp >> uint(16)) & 255u))) / wsum;
            int param_115 = int(floor(v_2 + 0.5));
            f = uint(clamp255(param_115));
        }
        else
        {
            if ((kind == 1u) && iip)
            {
                uint fp_1 = g_buf[1]->data[base + 19u];
                float v_3 = mix(float(fp_1 & 255u), float((fp_1 >> uint(8)) & 255u), tline);
                int param_116 = int(floor(v_3 + 0.5));
                f = uint(clamp255(param_116));
            }
            else
            {
                f = g_buf[1]->data[base + 20u] & 255u;
            }
        }
        uint acc_2 = rgba & 4278190080u;
        for (uint i_2 = 0u; i_2 < 3u; i_2++)
        {
            uint fc = (pc.fogcol >> (i_2 * 8u)) & 255u;
            uint param_117 = rgba;
            uint param_118 = i_2;
            uint v_4 = (((chan(param_117, param_118) * f) + (fc * (255u - f))) + 127u) / 255u;
            acc_2 |= ((v_4 & 255u) << (i_2 * 8u));
        }
        rgba = acc_2;
    }
    uint test = g_buf[1]->data[base + 23u];
    uint alpha = g_buf[1]->data[base + 24u];
    uint dst = s_color[idx];
    uint src_a = (rgba >> uint(24)) & 255u;
    bool write_rgb = true;
    bool write_a = true;
    bool write_z = true;
    if ((test & 1u) != 0u)
    {
        uint atst = (test >> 1u) & 7u;
        uint aref = (test >> 4u) & 255u;
        bool pass;
        if (atst == 0u)
        {
            pass = false;
        }
        else
        {
            if (atst == 1u)
            {
                pass = true;
            }
            else
            {
                if (atst == 2u)
                {
                    pass = src_a < aref;
                }
                else
                {
                    if (atst == 3u)
                    {
                        pass = src_a <= aref;
                    }
                    else
                    {
                        if (atst == 4u)
                        {
                            pass = src_a == aref;
                        }
                        else
                        {
                            if (atst == 5u)
                            {
                                pass = src_a >= aref;
                            }
                            else
                            {
                                if (atst == 6u)
                                {
                                    pass = src_a > aref;
                                }
                                else
                                {
                                    pass = src_a != aref;
                                }
                            }
                        }
                    }
                }
            }
        }
        if (!pass)
        {
            uint afail = (test >> 12u) & 3u;
            if (afail == 0u)
            {
                return;
            }
            if (afail == 1u)
            {
                write_z = false;
            }
            else
            {
                if (afail == 2u)
                {
                    write_rgb = false;
                    write_a = false;
                }
                else
                {
                    write_z = false;
                    write_a = false;
                }
            }
        }
    }
    if ((test & 16384u) != 0u)
    {
        uint datm = uint((test & 32768u) != 0u);
        if (((dst >> uint(31)) & 1u) != datm)
        {
            return;
        }
    }
    if ((test & 65536u) != 0u)
    {
        uint ztst = (test >> 17u) & 3u;
        uint zdst = s_depth[idx];
        bool pass_1;
        if (ztst == 0u)
        {
            pass_1 = false;
        }
        else
        {
            if (ztst == 1u)
            {
                pass_1 = true;
            }
            else
            {
                if (ztst == 2u)
                {
                    pass_1 = zsrc >= zdst;
                }
                else
                {
                    pass_1 = zsrc > zdst;
                }
            }
        }
        if (!pass_1)
        {
            return;
        }
    }
    uint _5163;
    if (aa1)
    {
        float param_119 = cover;
        _5163 = gs_aa_alpha(param_119);
    }
    else
    {
        _5163 = 128u;
    }
    uint cov_alpha = _5163;
    uint outc = rgba;
    bool blend = (flags & 128u) != 0u;
    bool _5184;
    if (blend)
    {
        _5184 = (alpha & 131072u) != 0u;
    }
    else
    {
        _5184 = blend;
    }
    if (_5184 && (src_a < 128u))
    {
        blend = false;
    }
    if (blend)
    {
        uint sa = (alpha >> 0u) & 3u;
        uint sb = (alpha >> 2u) & 3u;
        uint sc = (alpha >> 4u) & 3u;
        uint sd = (alpha >> 6u) & 3u;
        uint fix = (alpha >> 8u) & 255u;
        int c;
        if (sc == 0u)
        {
            c = int(aa1 ? cov_alpha : src_a);
        }
        else
        {
            if (sc == 1u)
            {
                c = int((dst >> uint(24)) & 255u);
            }
            else
            {
                c = int(fix);
            }
        }
        bool cclamp = (alpha & 65536u) != 0u;
        uint res = 0u;
        int _5265;
        int _5278;
        int _5291;
        int _5311;
        for (uint i_3 = 0u; i_3 < 3u; i_3++)
        {
            uint param_120 = rgba;
            uint param_121 = i_3;
            int cs = int(chan(param_120, param_121));
            uint param_122 = dst;
            uint param_123 = i_3;
            int cd = int(chan(param_122, param_123));
            if (sa == 0u)
            {
                _5265 = cs;
            }
            else
            {
                _5265 = (sa == 1u) ? cd : 0;
            }
            int a = _5265;
            if (sb == 0u)
            {
                _5278 = cs;
            }
            else
            {
                _5278 = (sb == 1u) ? cd : 0;
            }
            int b = _5278;
            if (sd == 0u)
            {
                _5291 = cs;
            }
            else
            {
                _5291 = (sd == 1u) ? cd : 0;
            }
            int d = _5291;
            int v_5 = (((a - b) * c) >> 7) + d;
            if (cclamp)
            {
                _5311 = clamp(v_5, 0, 255);
            }
            else
            {
                _5311 = v_5 & 255;
            }
            v_5 = _5311;
            res |= (uint(v_5) << (i_3 * 8u));
        }
        outc = res | (rgba & 4278190080u);
    }
    uint out_a = (outc >> uint(24)) & 255u;
    if ((alpha & 262144u) != 0u)
    {
        out_a |= 128u;
    }
    uint out_rgb = outc & 16777215u;
    bool _5351 = (alpha & 524288u) != 0u;
    bool _5364;
    if (_5351)
    {
        bool _5356 = pc.frame_psm == 2u;
        bool _5363;
        if (!_5356)
        {
            _5363 = pc.frame_psm == 10u;
        }
        else
        {
            _5363 = _5356;
        }
        _5364 = _5363;
    }
    else
    {
        _5364 = _5351;
    }
    if (_5364)
    {
        uint param_124 = uint(px);
        uint param_125 = uint(py);
        int d_1 = dimx_entry(param_124, param_125, pc);
        uint dith = 0u;
        for (uint i_4 = 0u; i_4 < 3u; i_4++)
        {
            uint param_126 = out_rgb;
            uint param_127 = i_4;
            int param_128 = int(chan(param_126, param_127)) + d_1;
            dith |= (uint(clamp255(param_128)) << (i_4 * 8u));
        }
        out_rgb = dith;
    }
    uint _5405;
    if (write_rgb)
    {
        _5405 = out_rgb;
    }
    else
    {
        _5405 = dst & 16777215u;
    }
    uint _5414;
    if (write_a)
    {
        _5414 = out_a;
    }
    else
    {
        _5414 = (dst >> uint(24)) & 255u;
    }
    uint written = _5405 | (_5414 << uint(24));
    bool wrote_color = write_rgb || write_a;
    bool _5436;
    if (write_z)
    {
        _5436 = pc.z_write != 0u;
    }
    else
    {
        _5436 = write_z;
    }
    bool wrote_z = _5436;
    if (wrote_color)
    {
        s_color[idx] = written;
        g_wrote_color = true;
    }
    if (wrote_z)
    {
        s_depth[idx] = zsrc;
        g_wrote_z = true;
    }
    bool _5458;
    if (g_alias)
    {
        _5458 = wrote_color || wrote_z;
    }
    else
    {
        _5458 = g_alias;
    }
    if (_5458)
    {
        uint param_129 = pc.frame_psm;
        uint param_130 = s_color[idx];
        uint param_131 = pc.z_psm;
        uint param_132 = zsrc;
        bool param_133 = wrote_z;
        uint bits = gs_alias_word(param_129, param_130, param_131, param_132, param_133);
        uint param_134 = pc.frame_psm;
        uint param_135 = bits;
        s_color[idx] = gs_frame_unpack(param_134, param_135);
        uint param_136 = pc.z_psm;
        s_depth[idx] = bits & gs_z_precision_mask(param_136);
        g_wrote_color = true;
        g_wrote_z = true;
    }
}

static inline __attribute__((always_inline))
uint frame_write_mask16(constant Push& pc)
{
    uint m = ((((pc.frame_mask >> uint(3)) & 31u) | (((pc.frame_mask >> uint(11)) & 31u) << uint(5))) | (((pc.frame_mask >> uint(19)) & 31u) << uint(10))) | (((pc.frame_mask >> uint(31)) & 1u) << uint(15));
    return (~m) & 65535u;
}

static inline __attribute__((always_inline))
void store_masked(thread const uint& word, thread const uint& value, thread const uint& mask, thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16])
{
    if (mask == 0u)
    {
        return;
    }
    uint param = word;
    uint i = mem_index(param, g_plane);
    if (g_shadow)
    {
        if (mask == 4294967295u)
        {
            g_buf[5]->data[i] = value;
            return;
        }
        uint _2777 = atomic_fetch_and_explicit((device atomic_uint*)&g_buf[5]->data[i], ~mask, memory_order_relaxed);
        uint _2783 = atomic_fetch_or_explicit((device atomic_uint*)&g_buf[5]->data[i], value & mask, memory_order_relaxed);
        return;
    }
    if (mask == 4294967295u)
    {
        g_buf[0]->data[i] = value;
        return;
    }
    uint _2797 = atomic_fetch_and_explicit((device atomic_uint*)&g_buf[0]->data[i], ~mask, memory_order_relaxed);
    uint _2803 = atomic_fetch_or_explicit((device atomic_uint*)&g_buf[0]->data[i], value & mask, memory_order_relaxed);
}

static inline __attribute__((always_inline))
void frame_store(thread const uint& rgba, thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint& g_faddr)
{
    uint psm = pc.frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint shift = (g_faddr & 1u) * 16u;
        uint param = rgba;
        uint param_1 = g_faddr >> uint(1);
        uint param_2 = gs_pack16(param) << shift;
        uint param_3 = frame_write_mask16(pc) << shift;
        store_masked(param_1, param_2, param_3, g_plane, g_shadow, g_buf);
        return;
    }
    uint mask = (psm == 1u) ? 16777215u : 4294967295u;
    uint param_4 = g_faddr;
    uint param_5 = rgba;
    uint param_6 = mask & (~pc.frame_mask);
    store_masked(param_4, param_5, param_6, g_plane, g_shadow, g_buf);
}

static inline __attribute__((always_inline))
void z_store(thread const uint& z, thread uint& g_plane, thread bool& g_shadow, device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint& g_zaddr)
{
    uint psm = pc.z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint shift = (g_zaddr & 1u) * 16u;
        uint param = g_zaddr >> uint(1);
        uint param_1 = (z & 65535u) << shift;
        uint param_2 = 65535u << shift;
        store_masked(param, param_1, param_2, g_plane, g_shadow, g_buf);
        return;
    }
    uint mask = (psm == 49u) ? 16777215u : 4294967295u;
    uint param_3 = g_zaddr;
    uint param_4 = z & mask;
    uint param_5 = mask;
    store_masked(param_3, param_4, param_5, g_plane, g_shadow, g_buf);
}

kernel void main0(device GsBuffer* g_buf_0 [[buffer(4)]], device GsBuffer* g_buf_1 [[buffer(5)]], device GsBuffer* g_buf_2 [[buffer(6)]], device GsBuffer* g_buf_3 [[buffer(7)]], device GsBuffer* g_buf_4 [[buffer(8)]], device GsBuffer* g_buf_5 [[buffer(9)]], device GsBuffer* g_buf_6 [[buffer(10)]], device GsBuffer* g_buf_7 [[buffer(11)]], device GsBuffer* g_buf_8 [[buffer(12)]], device GsBuffer* g_buf_9 [[buffer(13)]], device GsBuffer* g_buf_10 [[buffer(14)]], device GsBuffer* g_buf_11 [[buffer(15)]], device GsBuffer* g_buf_12 [[buffer(16)]], device GsBuffer* g_buf_13 [[buffer(17)]], device GsBuffer* g_buf_14 [[buffer(18)]], device GsBuffer* g_buf_15 [[buffer(19)]], constant Push& pc [[buffer(20)]], uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]])
{
    device GsBuffer* g_buf[] =
    {
        g_buf_0,
        g_buf_1,
        g_buf_2,
        g_buf_3,
        g_buf_4,
        g_buf_5,
        g_buf_6,
        g_buf_7,
        g_buf_8,
        g_buf_9,
        g_buf_10,
        g_buf_11,
        g_buf_12,
        g_buf_13,
        g_buf_14,
        g_buf_15,
    };

    threadgroup spvUnsafeArray<uint, 256> s_color;
    threadgroup spvUnsafeArray<uint, 256> s_depth;
    uint tw = pc.tile_w;
    uint th = pc.tile_h;
    uint idx = gl_LocalInvocationIndex;
    uint lx = idx % tw;
    uint ly = (idx / tw) % th;
    uint smp = idx / (tw * th);
    uint g_plane;
    bool g_shadow;
    uint g_faddr;
    uint g_zaddr;
    bool g_wrote_color;
    bool g_wrote_z;
    bool g_alias;
    if (smp >= pc.samples)
    {
        return;
    }
    uint px = ((pc.tile_x0 + gl_WorkGroupID.x) * tw) + lx;
    uint py = ((pc.tile_y0 + gl_WorkGroupID.y) * th) + ly;
    uint binx = px / 64u;
    uint biny = py / 64u;
    if ((binx >= 32u) || (biny >= 32u))
    {
        return;
    }
    uint bin = (biny * 32u) + binx;
    uint off = g_buf[3]->data[bin * 2u];
    uint cnt = g_buf[3]->data[(bin * 2u) + 1u];
    if (cnt == 0u)
    {
        return;
    }
    g_shadow = pc.shadow != 0u;
    uint _5589;
    if (g_shadow)
    {
        _5589 = smp * 1048576u;
    }
    else
    {
        _5589 = 0u;
    }
    g_plane = _5589;
    uint param = pc.frame_psm;
    uint param_1 = pc.frame_base_block;
    uint param_2 = pc.frame_bw;
    uint param_3 = px;
    uint param_4 = py;
    g_faddr = gs_pixel_addr(param, param_1, param_2, param_3, param_4);
    uint param_5 = pc.z_psm;
    uint param_6 = pc.z_base_block;
    uint param_7 = pc.frame_bw;
    uint param_8 = px;
    uint param_9 = py;
    g_zaddr = gs_pixel_addr(param_5, param_6, param_7, param_8, param_9);
    uint param_10 = pc.frame_psm;
    uint param_11 = g_faddr;
    uint param_12 = pc.z_psm;
    uint param_13 = g_zaddr;
    g_alias = gs_alias_pixel(param_10, param_11, param_12, param_13);
    s_color[idx] = frame_load(g_plane, g_shadow, g_buf, pc, g_faddr);
    s_depth[idx] = z_load(g_plane, g_shadow, g_buf, pc, g_zaddr);
    g_wrote_color = false;
    g_wrote_z = false;
    uint param_14 = pc.samples;
    uint param_15 = smp;
    int sxp = (int(px) * 16) + gs_sample_x(param_14, param_15);
    uint param_16 = pc.samples;
    uint param_17 = smp;
    int syp = (int(py) * 16) + gs_sample_y(param_16, param_17);
    for (uint i = 0u; i < cnt; i++)
    {
        uint param_18 = g_buf[2]->data[off + i];
        int param_19 = int(px);
        int param_20 = int(py);
        int param_21 = sxp;
        int param_22 = syp;
        uint param_23 = idx;
        shade(param_18, param_19, param_20, param_21, param_22, param_23, g_buf, pc, s_color, s_depth, g_wrote_color, g_wrote_z, g_alias);
    }
    if (g_wrote_color)
    {
        uint param_24 = s_color[idx];
        frame_store(param_24, g_plane, g_shadow, g_buf, pc, g_faddr);
    }
    bool _5708;
    if (g_wrote_z)
    {
        _5708 = pc.z_write != 0u;
    }
    else
    {
        _5708 = g_wrote_z;
    }
    if (_5708)
    {
        uint param_25 = s_depth[idx];
        z_store(param_25, g_plane, g_shadow, g_buf, pc, g_zaddr);
    }
}
