// src/runtime/gs/render/shaders/msl/scanout.comp.metal: MSL for src/runtime/gs/render/shaders/scanout.comp, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The argument indices were rewritten to the convention in
// src/runtime/rhi/metal/rhi_metal_bindings.h; that header says why.
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct VramBuffer
{
    uint data[1];
};

struct Push
{
    uint frame_w;
    uint frame_h;
    uint field;
    uint deinterlace;
    uint interlaced;
    uint ffmd;
    uint bgcolor;
    uint merge;
    uint c1_enable;
    uint c1_base_block;
    uint c1_fbw;
    uint c1_psm;
    uint c1_dbx;
    uint c1_dby;
    uint c1_x;
    uint c1_y;
    uint c1_w;
    uint c1_h;
    uint c2_enable;
    uint c2_base_block;
    uint c2_fbw;
    uint c2_psm;
    uint c2_dbx;
    uint c2_dby;
    uint c2_x;
    uint c2_y;
    uint c2_w;
    uint c2_h;
    uint hires;
    uint samples;
    uint hist_valid;
};

constant spvUnsafeArray<uint, 32> _333 = spvUnsafeArray<uint, 32>({ 0u, 1u, 4u, 5u, 16u, 17u, 20u, 21u, 2u, 3u, 6u, 7u, 18u, 19u, 22u, 23u, 8u, 9u, 12u, 13u, 24u, 25u, 28u, 29u, 10u, 11u, 14u, 15u, 26u, 27u, 30u, 31u });
constant spvUnsafeArray<uint, 32> _344 = spvUnsafeArray<uint, 32>({ 24u, 25u, 28u, 29u, 8u, 9u, 12u, 13u, 26u, 27u, 30u, 31u, 10u, 11u, 14u, 15u, 16u, 17u, 20u, 21u, 0u, 1u, 4u, 5u, 18u, 19u, 22u, 23u, 2u, 3u, 6u, 7u });
constant spvUnsafeArray<uint, 32> _357 = spvUnsafeArray<uint, 32>({ 0u, 2u, 8u, 10u, 1u, 3u, 9u, 11u, 4u, 6u, 12u, 14u, 5u, 7u, 13u, 15u, 16u, 18u, 24u, 26u, 17u, 19u, 25u, 27u, 20u, 22u, 28u, 30u, 21u, 23u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _367 = spvUnsafeArray<uint, 32>({ 0u, 2u, 16u, 18u, 1u, 3u, 17u, 19u, 8u, 10u, 24u, 26u, 9u, 11u, 25u, 27u, 4u, 6u, 20u, 22u, 5u, 7u, 21u, 23u, 12u, 14u, 28u, 30u, 13u, 15u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _377 = spvUnsafeArray<uint, 32>({ 24u, 26u, 16u, 18u, 25u, 27u, 17u, 19u, 28u, 30u, 20u, 22u, 29u, 31u, 21u, 23u, 8u, 10u, 0u, 2u, 9u, 11u, 1u, 3u, 12u, 14u, 4u, 6u, 13u, 15u, 5u, 7u });
constant spvUnsafeArray<uint, 32> _387 = spvUnsafeArray<uint, 32>({ 24u, 26u, 8u, 10u, 25u, 27u, 9u, 11u, 16u, 18u, 0u, 2u, 17u, 19u, 1u, 3u, 28u, 30u, 12u, 14u, 29u, 31u, 13u, 15u, 20u, 22u, 4u, 6u, 21u, 23u, 5u, 7u });
constant spvUnsafeArray<uint, 16> _425 = spvUnsafeArray<uint, 16>({ 0u, 1u, 4u, 5u, 8u, 9u, 12u, 13u, 2u, 3u, 6u, 7u, 10u, 11u, 14u, 15u });

static inline __attribute__((always_inline))
uint gs_sample_cols(thread const uint& samples)
{
    if (samples >= 8u)
    {
        return 4u;
    }
    if (samples >= 4u)
    {
        return 2u;
    }
    return 1u;
}

static inline __attribute__((always_inline))
uint gs_sample_rows(thread const uint& samples)
{
    uint param = samples;
    return samples / gs_sample_cols(param);
}

static inline __attribute__((always_inline))
uint gs_psm_family(thread const uint& psm)
{
    if (((((psm == 0u) || (psm == 1u)) || (psm == 27u)) || (psm == 36u)) || (psm == 44u))
    {
        return 0u;
    }
    if ((psm == 48u) || (psm == 49u))
    {
        return 5u;
    }
    if (psm == 2u)
    {
        return 1u;
    }
    if (psm == 10u)
    {
        return 2u;
    }
    if (psm == 50u)
    {
        return 6u;
    }
    if (psm == 58u)
    {
        return 7u;
    }
    if (psm == 19u)
    {
        return 3u;
    }
    if (psm == 20u)
    {
        return 4u;
    }
    return 255u;
}

static inline __attribute__((always_inline))
uint gs_page_width(thread const uint& fam)
{
    if ((fam == 3u) || (fam == 4u))
    {
        return 128u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_page_height(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 128u;
    }
    if (fam == 3u)
    {
        return 64u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 32u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_block_width(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 32u;
    }
    if (fam == 3u)
    {
        return 16u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    return 16u;
}

static inline __attribute__((always_inline))
uint gs_block_height(thread const uint& fam)
{
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    if ((fam == 3u) || (fam == 4u))
    {
        return 16u;
    }
    return 8u;
}

static inline __attribute__((always_inline))
uint gs_page_block_cols(thread const uint& fam)
{
    uint param = fam;
    uint param_1 = fam;
    return gs_page_width(param) / gs_block_width(param_1);
}

static inline __attribute__((always_inline))
uint gs_block_number(thread const uint& fam, thread const uint& bx, thread const uint& by)
{
    uint param = fam;
    uint i = (by * gs_page_block_cols(param)) + bx;
    if ((fam == 0u) || (fam == 3u))
    {
        return _333[i];
    }
    if (fam == 5u)
    {
        return _344[i];
    }
    if ((fam == 1u) || (fam == 4u))
    {
        return _357[i];
    }
    if (fam == 2u)
    {
        return _367[i];
    }
    if (fam == 6u)
    {
        return _377[i];
    }
    if (fam == 7u)
    {
        return _387[i];
    }
    return 0u;
}

static inline __attribute__((always_inline))
uint gs_addr_bits(thread const uint& psm)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    if (fam == 3u)
    {
        return 8u;
    }
    if (fam == 4u)
    {
        return 4u;
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        return 16u;
    }
    return 32u;
}

static inline __attribute__((always_inline))
uint gs_block_offset(thread const uint& fam, thread const uint& x, thread const uint& y)
{
    uint param = fam;
    uint bw = gs_block_width(param);
    uint param_1 = fam;
    uint bh = gs_block_height(param_1);
    uint lx = x % bw;
    uint ly = y % bh;
    if ((fam == 0u) || (fam == 5u))
    {
        uint col = ly >> uint(1);
        return (col * 16u) + _425[((ly & 1u) * 8u) + (lx & 7u)];
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        uint col_1 = ly >> uint(1);
        uint w = _425[((ly & 1u) * 8u) + (lx & 7u)];
        uint hword = (lx >> uint(3)) & 1u;
        return ((col_1 * 32u) + (w * 2u)) + hword;
    }
    uint col_2 = ly >> uint(2);
    uint row = ly & 3u;
    uint rot = (row >= 2u) ? 4u : 0u;
    uint w_1 = _425[(((lx >> uint(3)) & 1u) * 8u) + (((lx & 7u) + rot) & 7u)];
    uint _505;
    if (row == 0u)
    {
        _505 = 0u;
    }
    else
    {
        uint _511;
        if (row == 1u)
        {
            _511 = 2u;
        }
        else
        {
            _511 = (row == 2u) ? 1u : 3u;
        }
        _505 = _511;
    }
    uint sub = _505;
    if ((col_2 & 1u) != 0u)
    {
        sub ^= 2u;
    }
    if (fam == 3u)
    {
        return ((col_2 * 64u) + (w_1 * 4u)) + sub;
    }
    uint nib = (((lx >> uint(4)) & 1u) * 4u) + sub;
    return ((col_2 * 128u) + (w_1 * 8u)) + nib;
}

static inline __attribute__((always_inline))
uint gs_pixel_addr(thread const uint& psm, thread const uint& base_block, thread const uint& fbw, thread const uint& x, thread const uint& y)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    uint param_1 = fam;
    uint pw = gs_page_width(param_1);
    uint param_2 = fam;
    uint ph = gs_page_height(param_2);
    uint pages_across = (fbw * 64u) / pw;
    if (pages_across == 0u)
    {
        pages_across = 1u;
    }
    uint page = ((y / ph) * pages_across) + (x / pw);
    uint param_3 = fam;
    uint bx = (x % pw) / gs_block_width(param_3);
    uint param_4 = fam;
    uint by = (y % ph) / gs_block_height(param_4);
    uint param_5 = fam;
    uint param_6 = bx;
    uint param_7 = by;
    uint block = ((base_block + (page * 32u)) + gs_block_number(param_5, param_6, param_7)) & 16383u;
    uint param_8 = psm;
    uint units_per_block = 2048u / gs_addr_bits(param_8);
    uint param_9 = fam;
    uint param_10 = x;
    uint param_11 = y;
    return (block * units_per_block) + gs_block_offset(param_9, param_10, param_11);
}

static inline __attribute__((always_inline))
uint vram_word(thread const uint& word, thread const int& plane, device VramBuffer* (&g_vram)[16])
{
    uint w = word & 1048575u;
    if (plane < 0)
    {
        return g_vram[0]->data[w];
    }
    return g_vram[1]->data[w + (uint(plane) * 1048576u)];
}

static inline __attribute__((always_inline))
uint gs_expand16(thread const uint& v)
{
    uint r = (v & 31u) << uint(3);
    uint g = ((v >> uint(5)) & 31u) << uint(3);
    uint b = ((v >> uint(10)) & 31u) << uint(3);
    uint a = ((v >> uint(15)) & 1u) * 128u;
    return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
}

static inline __attribute__((always_inline))
uint read_circuit(thread const uint& psm, thread const uint& base_block, thread const uint& fbw, thread const uint& x, thread const uint& y, thread const int& plane, device VramBuffer* (&g_vram)[16])
{
    uint param = psm;
    uint param_1 = base_block;
    uint param_2 = fbw;
    uint param_3 = x;
    uint param_4 = y;
    uint addr = gs_pixel_addr(param, param_1, param_2, param_3, param_4);
    if ((psm == 2u) || (psm == 10u))
    {
        uint param_5 = addr >> uint(1);
        int param_6 = plane;
        uint word = vram_word(param_5, param_6, g_vram);
        uint _752;
        if ((addr & 1u) != 0u)
        {
            _752 = word >> uint(16);
        }
        else
        {
            _752 = word & 65535u;
        }
        uint half_word = _752;
        uint param_7 = half_word;
        return gs_expand16(param_7);
    }
    uint param_8 = addr;
    int param_9 = plane;
    uint word_1 = vram_word(param_8, param_9, g_vram);
    if (psm == 1u)
    {
        return (word_1 & 16777215u) | 2147483648u;
    }
    return word_1;
}

static inline __attribute__((always_inline))
uint blend_channel(thread const uint& front, thread const uint& back, thread const uint& alpha)
{
    int f = int(front);
    int b = int(back);
    int a = int(alpha);
    int v = b + (((f - b) * a) >> 7);
    return uint(clamp(v, 0, 255));
}

static inline __attribute__((always_inline))
uint merge_at(thread const uint& x, thread const uint& line, thread const uint& fld, thread const int& plane, device VramBuffer* (&g_vram)[16], constant Push& pc)
{
    uint en1 = pc.merge & 1u;
    uint en2 = (pc.merge >> uint(1)) & 1u;
    uint mmod = (pc.merge >> uint(2)) & 1u;
    uint amod = (pc.merge >> uint(3)) & 1u;
    uint slbg = (pc.merge >> uint(4)) & 1u;
    uint alp = (pc.merge >> uint(8)) & 255u;
    bool _850 = (pc.c1_enable != 0u) && (en1 != 0u);
    bool _858;
    if (_850)
    {
        _858 = x >= pc.c1_x;
    }
    else
    {
        _858 = _850;
    }
    bool _868;
    if (_858)
    {
        _868 = x < (pc.c1_x + pc.c1_w);
    }
    else
    {
        _868 = _858;
    }
    bool _875;
    if (_868)
    {
        _875 = line >= pc.c1_y;
    }
    else
    {
        _875 = _868;
    }
    bool _886;
    if (_875)
    {
        _886 = line < (pc.c1_y + pc.c1_h);
    }
    else
    {
        _886 = _875;
    }
    bool in1 = _886;
    bool _894 = (pc.c2_enable != 0u) && (en2 != 0u);
    bool _901;
    if (_894)
    {
        _901 = x >= pc.c2_x;
    }
    else
    {
        _901 = _894;
    }
    bool _912;
    if (_901)
    {
        _912 = x < (pc.c2_x + pc.c2_w);
    }
    else
    {
        _912 = _901;
    }
    bool _920;
    if (_912)
    {
        _920 = line >= pc.c2_y;
    }
    else
    {
        _920 = _912;
    }
    bool _931;
    if (_920)
    {
        _931 = line < (pc.c2_y + pc.c2_h);
    }
    else
    {
        _931 = _920;
    }
    bool in2 = _931;
    uint texel1 = 0u;
    uint texel2 = 0u;
    if (in1)
    {
        uint sx = pc.c1_dbx + (x - pc.c1_x);
        uint sy = pc.c1_dby + (line - pc.c1_y);
        if (pc.ffmd != 0u)
        {
            sy = (pc.c1_dby + ((line - pc.c1_y) * 2u)) + fld;
        }
        uint param = pc.c1_psm;
        uint param_1 = pc.c1_base_block;
        uint param_2 = pc.c1_fbw;
        uint param_3 = sx;
        uint param_4 = sy;
        int param_5 = plane;
        texel1 = read_circuit(param, param_1, param_2, param_3, param_4, param_5, g_vram);
    }
    if (in2)
    {
        uint sx_1 = pc.c2_dbx + (x - pc.c2_x);
        uint sy_1 = pc.c2_dby + (line - pc.c2_y);
        if (pc.ffmd != 0u)
        {
            sy_1 = (pc.c2_dby + ((line - pc.c2_y) * 2u)) + fld;
        }
        uint param_6 = pc.c2_psm;
        uint param_7 = pc.c2_base_block;
        uint param_8 = pc.c2_fbw;
        uint param_9 = sx_1;
        uint param_10 = sy_1;
        int param_11 = plane;
        texel2 = read_circuit(param_6, param_7, param_8, param_9, param_10, param_11, g_vram);
    }
    bool _1052;
    if (in2)
    {
        _1052 = (slbg == 0u) || (en1 == 0u);
    }
    else
    {
        _1052 = in2;
    }
    uint _1053;
    if (_1052)
    {
        _1053 = texel2;
    }
    else
    {
        _1053 = pc.bgcolor | 2147483648u;
    }
    uint back = _1053;
    if (in1 && (en1 != 0u))
    {
        uint _1072;
        if (mmod != 0u)
        {
            _1072 = alp;
        }
        else
        {
            _1072 = (texel1 >> uint(24)) & 255u;
        }
        uint alpha = _1072;
        uint param_12 = texel1 & 255u;
        uint param_13 = back & 255u;
        uint param_14 = alpha;
        uint r = blend_channel(param_12, param_13, param_14);
        uint param_15 = (texel1 >> uint(8)) & 255u;
        uint param_16 = (back >> uint(8)) & 255u;
        uint param_17 = alpha;
        uint g = blend_channel(param_15, param_16, param_17);
        uint param_18 = (texel1 >> uint(16)) & 255u;
        uint param_19 = (back >> uint(16)) & 255u;
        uint param_20 = alpha;
        uint b = blend_channel(param_18, param_19, param_20);
        uint _1118;
        if (amod != 0u)
        {
            _1118 = (texel2 >> uint(24)) & 255u;
        }
        else
        {
            _1118 = (texel1 >> uint(24)) & 255u;
        }
        uint a = _1118;
        return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
    }
    return back;
}

static inline __attribute__((always_inline))
uint merge_quadrant(thread const uint& x, thread const uint& line, thread const uint& fld, thread const uint& sub_x, thread const uint& sub_y, device VramBuffer* (&g_vram)[16], constant Push& pc)
{
    uint param = pc.samples;
    uint cols = gs_sample_cols(param);
    uint param_1 = pc.samples;
    uint rows = gs_sample_rows(param_1);
    uint cw = max((cols >> uint(1)), 1u);
    uint rh = max((rows >> uint(1)), 1u);
    uint cx = sub_x * cw;
    uint ry = sub_y * rh;
    uint acc0 = 0u;
    uint acc1 = 0u;
    uint acc2 = 0u;
    uint acc3 = 0u;
    uint n = 0u;
    for (uint dy = 0u; dy < rh; dy++)
    {
        for (uint dx = 0u; dx < cw; dx++)
        {
            uint param_2 = x;
            uint param_3 = line;
            uint param_4 = fld;
            int param_5 = int((((ry + dy) * cols) + cx) + dx);
            uint c = merge_at(param_2, param_3, param_4, param_5, g_vram, pc);
            acc0 += (c & 255u);
            acc1 += ((c >> uint(8)) & 255u);
            acc2 += ((c >> uint(16)) & 255u);
            acc3 += ((c >> uint(24)) & 255u);
            n++;
        }
    }
    uint bias0 = n >> uint(1);
    return ((((acc0 + bias0) / n) | (((acc1 + bias0) / n) << uint(8))) | (((acc2 + bias0) / n) << uint(16))) | (((acc3 + bias0) / n) << uint(24));
}

static inline __attribute__((always_inline))
void store(thread const uint2& pix, thread const uint& out_w, thread const uint& result, device VramBuffer* (&g_vram)[16], thread const array<texture2d<float, access::write>, 4>& g_images)
{
    g_vram[2]->data[(pix.y * out_w) + pix.x] = result;
    float4 rgba = float4(float(result & 255u), float((result >> uint(8)) & 255u), float((result >> uint(16)) & 255u), float((result >> uint(24)) & 255u)) / float4(255.0);
    g_images[0].write(rgba, uint2(int2(pix)));
}

static inline __attribute__((always_inline))
uint average2(thread const uint& a, thread const uint& b)
{
    uint out_c = 0u;
    for (uint i = 0u; i < 4u; i++)
    {
        uint ca = (a >> (i * 8u)) & 255u;
        uint cb = (b >> (i * 8u)) & 255u;
        out_c |= ((((ca + cb) + 1u) >> uint(1)) << (i * 8u));
    }
    return out_c;
}

static inline __attribute__((always_inline))
uint channel_distance(thread const uint& a, thread const uint& b)
{
    uint worst = 0u;
    uint _1204;
    for (uint i = 0u; i < 3u; i++)
    {
        uint ca = (a >> (i * 8u)) & 255u;
        uint cb = (b >> (i * 8u)) & 255u;
        if (ca > cb)
        {
            _1204 = ca - cb;
        }
        else
        {
            _1204 = cb - ca;
        }
        uint d = _1204;
        worst = max(worst, d);
    }
    return worst;
}

kernel void main0(device VramBuffer* g_vram_0 [[buffer(4)]], device VramBuffer* g_vram_1 [[buffer(5)]], device VramBuffer* g_vram_2 [[buffer(6)]], device VramBuffer* g_vram_3 [[buffer(7)]], device VramBuffer* g_vram_4 [[buffer(8)]], device VramBuffer* g_vram_5 [[buffer(9)]], device VramBuffer* g_vram_6 [[buffer(10)]], device VramBuffer* g_vram_7 [[buffer(11)]], device VramBuffer* g_vram_8 [[buffer(12)]], device VramBuffer* g_vram_9 [[buffer(13)]], device VramBuffer* g_vram_10 [[buffer(14)]], device VramBuffer* g_vram_11 [[buffer(15)]], device VramBuffer* g_vram_12 [[buffer(16)]], device VramBuffer* g_vram_13 [[buffer(17)]], device VramBuffer* g_vram_14 [[buffer(18)]], device VramBuffer* g_vram_15 [[buffer(19)]], constant Push& pc [[buffer(20)]], array<texture2d<float, access::write>, 4> g_images [[texture(8)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    device VramBuffer* g_vram[] =
    {
        g_vram_0,
        g_vram_1,
        g_vram_2,
        g_vram_3,
        g_vram_4,
        g_vram_5,
        g_vram_6,
        g_vram_7,
        g_vram_8,
        g_vram_9,
        g_vram_10,
        g_vram_11,
        g_vram_12,
        g_vram_13,
        g_vram_14,
        g_vram_15,
    };

    uint _1396;
    if (pc.hires != 0u)
    {
        _1396 = pc.frame_w * 2u;
    }
    else
    {
        _1396 = pc.frame_w;
    }
    uint out_w = _1396;
    uint _1410;
    if (pc.hires != 0u)
    {
        _1410 = pc.frame_h * 2u;
    }
    else
    {
        _1410 = pc.frame_h;
    }
    uint out_h = _1410;
    uint2 pix = gl_GlobalInvocationID.xy;
    bool _1429 = pix.x >= out_w;
    bool _1437;
    if (!_1429)
    {
        _1437 = pix.y >= out_h;
    }
    else
    {
        _1437 = _1429;
    }
    if (_1437)
    {
        return;
    }
    if (pc.hires != 0u)
    {
        uint ny = pix.y >> uint(1);
        uint line = ny;
        uint fld = pc.field;
        uint sub_y = pix.y & 1u;
        if (pc.interlaced != 0u)
        {
            if (pc.ffmd != 0u)
            {
                line = ny >> uint(1);
                fld = ny & 1u;
            }
            else
            {
                line = pix.y >> uint(2);
                sub_y = (pix.y >> uint(1)) & 1u;
            }
        }
        uint param = pix.x >> uint(1);
        uint param_1 = line;
        uint param_2 = fld;
        uint param_3 = pix.x & 1u;
        uint param_4 = sub_y;
        uint2 param_5 = pix;
        uint param_6 = out_w;
        uint param_7 = merge_quadrant(param, param_1, param_2, param_3, param_4, g_vram, pc);
        store(param_5, param_6, param_7, g_vram, g_images);
        return;
    }
    uint line_1;
    if (pc.interlaced != 0u)
    {
        if (pc.deinterlace == 2u)
        {
            if ((pix.y & 1u) != pc.field)
            {
                return;
            }
            line_1 = pix.y >> uint(1);
        }
        else
        {
            if (pc.deinterlace == 0u)
            {
                if ((pix.y & 1u) == pc.field)
                {
                    uint param_8 = pix.x;
                    uint param_9 = pix.y >> uint(1);
                    uint param_10 = pc.field;
                    int param_11 = -1;
                    uint2 param_12 = pix;
                    uint param_13 = out_w;
                    uint param_14 = merge_at(param_8, param_9, param_10, param_11, g_vram, pc);
                    store(param_12, param_13, param_14, g_vram, g_images);
                    return;
                }
                uint above = uint(max((int(pix.y) - 1), 0)) >> uint(1);
                uint below = min((pix.y + 1u), (out_h - 1u)) >> uint(1);
                uint param_15 = pix.x;
                uint param_16 = above;
                uint param_17 = pc.field;
                int param_18 = -1;
                uint param_19 = pix.x;
                uint param_20 = below;
                uint param_21 = pc.field;
                int param_22 = -1;
                uint param_23 = merge_at(param_15, param_16, param_17, param_18, g_vram, pc);
                uint param_24 = merge_at(param_19, param_20, param_21, param_22, g_vram, pc);
                uint bobbed = average2(param_23, param_24);
                if (pc.hist_valid != 0u)
                {
                    uint standing = g_vram[2]->data[(pix.y * out_w) + pix.x];
                    uint param_25 = standing;
                    uint param_26 = bobbed;
                    if (channel_distance(param_25, param_26) <= 24u)
                    {
                        return;
                    }
                }
                uint2 param_27 = pix;
                uint param_28 = out_w;
                uint param_29 = bobbed;
                store(param_27, param_28, param_29, g_vram, g_images);
                return;
            }
            else
            {
                uint _1640;
                if (pix.y >= pc.field)
                {
                    _1640 = pix.y - pc.field;
                }
                else
                {
                    _1640 = 0u;
                }
                uint shifted = _1640;
                line_1 = shifted >> uint(1);
            }
        }
    }
    else
    {
        line_1 = pix.y;
    }
    uint param_30 = pix.x;
    uint param_31 = line_1;
    uint param_32 = pc.field;
    int param_33 = -1;
    uint2 param_34 = pix;
    uint param_35 = out_w;
    uint param_36 = merge_at(param_30, param_31, param_32, param_33, g_vram, pc);
    store(param_34, param_35, param_36, g_vram, g_images);
}
