// src/runtime/gs/render/shaders/msl/shadow.comp.metal: MSL for src/runtime/gs/render/shaders/shadow.comp, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The argument indices were rewritten to the convention in
// src/runtime/rhi/metal/rhi_metal_bindings.h; that header says why.
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct GsBuffer
{
    uint data[1];
};

struct Push
{
    uint mode;
    uint samples;
    uint frame_base_block;
    uint frame_bw;
    uint frame_psm;
    uint frame_mask;
    uint z_base_block;
    uint z_psm;
    uint z_write;
    uint x0;
    uint y0;
    uint x1;
    uint y1;
};

constant spvUnsafeArray<uint, 32> _329 = spvUnsafeArray<uint, 32>({ 0u, 1u, 4u, 5u, 16u, 17u, 20u, 21u, 2u, 3u, 6u, 7u, 18u, 19u, 22u, 23u, 8u, 9u, 12u, 13u, 24u, 25u, 28u, 29u, 10u, 11u, 14u, 15u, 26u, 27u, 30u, 31u });
constant spvUnsafeArray<uint, 32> _340 = spvUnsafeArray<uint, 32>({ 24u, 25u, 28u, 29u, 8u, 9u, 12u, 13u, 26u, 27u, 30u, 31u, 10u, 11u, 14u, 15u, 16u, 17u, 20u, 21u, 0u, 1u, 4u, 5u, 18u, 19u, 22u, 23u, 2u, 3u, 6u, 7u });
constant spvUnsafeArray<uint, 32> _353 = spvUnsafeArray<uint, 32>({ 0u, 2u, 8u, 10u, 1u, 3u, 9u, 11u, 4u, 6u, 12u, 14u, 5u, 7u, 13u, 15u, 16u, 18u, 24u, 26u, 17u, 19u, 25u, 27u, 20u, 22u, 28u, 30u, 21u, 23u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _363 = spvUnsafeArray<uint, 32>({ 0u, 2u, 16u, 18u, 1u, 3u, 17u, 19u, 8u, 10u, 24u, 26u, 9u, 11u, 25u, 27u, 4u, 6u, 20u, 22u, 5u, 7u, 21u, 23u, 12u, 14u, 28u, 30u, 13u, 15u, 29u, 31u });
constant spvUnsafeArray<uint, 32> _373 = spvUnsafeArray<uint, 32>({ 24u, 26u, 16u, 18u, 25u, 27u, 17u, 19u, 28u, 30u, 20u, 22u, 29u, 31u, 21u, 23u, 8u, 10u, 0u, 2u, 9u, 11u, 1u, 3u, 12u, 14u, 4u, 6u, 13u, 15u, 5u, 7u });
constant spvUnsafeArray<uint, 32> _383 = spvUnsafeArray<uint, 32>({ 24u, 26u, 8u, 10u, 25u, 27u, 9u, 11u, 16u, 18u, 0u, 2u, 17u, 19u, 1u, 3u, 28u, 30u, 12u, 14u, 29u, 31u, 13u, 15u, 20u, 22u, 4u, 6u, 21u, 23u, 5u, 7u });
constant spvUnsafeArray<uint, 16> _421 = spvUnsafeArray<uint, 16>({ 0u, 1u, 4u, 5u, 8u, 9u, 12u, 13u, 2u, 3u, 6u, 7u, 10u, 11u, 14u, 15u });

static inline __attribute__((always_inline))
uint plane_word(thread const uint& word, thread const uint& s)
{
    return (word & 1048575u) + (s * 1048576u);
}

static inline __attribute__((always_inline))
void seed(device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint3& gl_WorkGroupID, thread uint& gl_LocalInvocationIndex)
{
    uint page = g_buf[1]->data[gl_WorkGroupID.x];
    uint base = (page & 511u) * 2048u;
    for (uint w = gl_LocalInvocationIndex; w < 2048u; w += 64u)
    {
        uint v = g_buf[0]->data[base + w];
        for (uint s = 0u; s < pc.samples; s++)
        {
            uint param = base + w;
            uint param_1 = s;
            g_buf[5]->data[plane_word(param, param_1)] = v;
        }
    }
}

static inline __attribute__((always_inline))
uint gs_psm_family(thread const uint& psm)
{
    if (((((psm == 0u) || (psm == 1u)) || (psm == 27u)) || (psm == 36u)) || (psm == 44u))
    {
        return 0u;
    }
    if ((psm == 48u) || (psm == 49u))
    {
        return 5u;
    }
    if (psm == 2u)
    {
        return 1u;
    }
    if (psm == 10u)
    {
        return 2u;
    }
    if (psm == 50u)
    {
        return 6u;
    }
    if (psm == 58u)
    {
        return 7u;
    }
    if (psm == 19u)
    {
        return 3u;
    }
    if (psm == 20u)
    {
        return 4u;
    }
    return 255u;
}

static inline __attribute__((always_inline))
uint gs_page_width(thread const uint& fam)
{
    if ((fam == 3u) || (fam == 4u))
    {
        return 128u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_page_height(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 128u;
    }
    if (fam == 3u)
    {
        return 64u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 32u;
    }
    return 64u;
}

static inline __attribute__((always_inline))
uint gs_block_width(thread const uint& fam)
{
    if (fam == 4u)
    {
        return 32u;
    }
    if (fam == 3u)
    {
        return 16u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    return 16u;
}

static inline __attribute__((always_inline))
uint gs_block_height(thread const uint& fam)
{
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    if ((fam == 3u) || (fam == 4u))
    {
        return 16u;
    }
    return 8u;
}

static inline __attribute__((always_inline))
uint gs_page_block_cols(thread const uint& fam)
{
    uint param = fam;
    uint param_1 = fam;
    return gs_page_width(param) / gs_block_width(param_1);
}

static inline __attribute__((always_inline))
uint gs_block_number(thread const uint& fam, thread const uint& bx, thread const uint& by)
{
    uint param = fam;
    uint i = (by * gs_page_block_cols(param)) + bx;
    if ((fam == 0u) || (fam == 3u))
    {
        return _329[i];
    }
    if (fam == 5u)
    {
        return _340[i];
    }
    if ((fam == 1u) || (fam == 4u))
    {
        return _353[i];
    }
    if (fam == 2u)
    {
        return _363[i];
    }
    if (fam == 6u)
    {
        return _373[i];
    }
    if (fam == 7u)
    {
        return _383[i];
    }
    return 0u;
}

static inline __attribute__((always_inline))
uint gs_addr_bits(thread const uint& psm)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    if (fam == 3u)
    {
        return 8u;
    }
    if (fam == 4u)
    {
        return 4u;
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        return 16u;
    }
    return 32u;
}

static inline __attribute__((always_inline))
uint gs_block_offset(thread const uint& fam, thread const uint& x, thread const uint& y)
{
    uint param = fam;
    uint bw = gs_block_width(param);
    uint param_1 = fam;
    uint bh = gs_block_height(param_1);
    uint lx = x % bw;
    uint ly = y % bh;
    if ((fam == 0u) || (fam == 5u))
    {
        uint col = ly >> uint(1);
        return (col * 16u) + _421[((ly & 1u) * 8u) + (lx & 7u)];
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        uint col_1 = ly >> uint(1);
        uint w = _421[((ly & 1u) * 8u) + (lx & 7u)];
        uint hword = (lx >> uint(3)) & 1u;
        return ((col_1 * 32u) + (w * 2u)) + hword;
    }
    uint col_2 = ly >> uint(2);
    uint row = ly & 3u;
    uint rot = (row >= 2u) ? 4u : 0u;
    uint w_1 = _421[(((lx >> uint(3)) & 1u) * 8u) + (((lx & 7u) + rot) & 7u)];
    uint _501;
    if (row == 0u)
    {
        _501 = 0u;
    }
    else
    {
        uint _507;
        if (row == 1u)
        {
            _507 = 2u;
        }
        else
        {
            _507 = (row == 2u) ? 1u : 3u;
        }
        _501 = _507;
    }
    uint sub = _501;
    if ((col_2 & 1u) != 0u)
    {
        sub ^= 2u;
    }
    if (fam == 3u)
    {
        return ((col_2 * 64u) + (w_1 * 4u)) + sub;
    }
    uint nib = (((lx >> uint(4)) & 1u) * 4u) + sub;
    return ((col_2 * 128u) + (w_1 * 8u)) + nib;
}

static inline __attribute__((always_inline))
uint gs_pixel_addr(thread const uint& psm, thread const uint& base_block, thread const uint& fbw, thread const uint& x, thread const uint& y)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    uint param_1 = fam;
    uint pw = gs_page_width(param_1);
    uint param_2 = fam;
    uint ph = gs_page_height(param_2);
    uint pages_across = (fbw * 64u) / pw;
    if (pages_across == 0u)
    {
        pages_across = 1u;
    }
    uint page = ((y / ph) * pages_across) + (x / pw);
    uint param_3 = fam;
    uint bx = (x % pw) / gs_block_width(param_3);
    uint param_4 = fam;
    uint by = (y % ph) / gs_block_height(param_4);
    uint param_5 = fam;
    uint param_6 = bx;
    uint param_7 = by;
    uint block = ((base_block + (page * 32u)) + gs_block_number(param_5, param_6, param_7)) & 16383u;
    uint param_8 = psm;
    uint units_per_block = 2048u / gs_addr_bits(param_8);
    uint param_9 = fam;
    uint param_10 = x;
    uint param_11 = y;
    return (block * units_per_block) + gs_block_offset(param_9, param_10, param_11);
}

static inline __attribute__((always_inline))
uint gs_expand16(thread const uint& v)
{
    uint r = (v & 31u) << uint(3);
    uint g = ((v >> uint(5)) & 31u) << uint(3);
    uint b = ((v >> uint(10)) & 31u) << uint(3);
    uint a = ((v >> uint(15)) & 1u) * 128u;
    return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
}

static inline __attribute__((always_inline))
uint shadow_frame_pixel(thread const uint& addr, thread const uint& s, device GsBuffer* (&g_buf)[16], constant Push& pc)
{
    uint psm = pc.frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint param = addr >> uint(1);
        uint param_1 = s;
        uint w = g_buf[5]->data[plane_word(param, param_1)];
        uint _860;
        if ((addr & 1u) != 0u)
        {
            _860 = w >> uint(16);
        }
        else
        {
            _860 = w & 65535u;
        }
        uint hw = _860;
        uint param_2 = hw;
        return gs_expand16(param_2);
    }
    uint param_3 = addr;
    uint param_4 = s;
    return g_buf[5]->data[plane_word(param_3, param_4)];
}

static inline __attribute__((always_inline))
uint gs_pack16(thread const uint& rgba)
{
    return ((((rgba & 255u) >> uint(3)) | ((((rgba >> uint(8)) & 255u) >> uint(3)) << uint(5))) | ((((rgba >> uint(16)) & 255u) >> uint(3)) << uint(10))) | ((((rgba >> uint(24)) & 255u) >> uint(7)) << uint(15));
}

static inline __attribute__((always_inline))
uint frame_write_mask16(constant Push& pc)
{
    uint m = ((((pc.frame_mask >> uint(3)) & 31u) | (((pc.frame_mask >> uint(11)) & 31u) << uint(5))) | (((pc.frame_mask >> uint(19)) & 31u) << uint(10))) | (((pc.frame_mask >> uint(31)) & 1u) << uint(15));
    return (~m) & 65535u;
}

static inline __attribute__((always_inline))
void native_store_masked(thread const uint& word, thread const uint& value, thread const uint& mask, device GsBuffer* (&g_buf)[16])
{
    if (mask == 0u)
    {
        return;
    }
    uint i = word & 1048575u;
    if (mask == 4294967295u)
    {
        g_buf[0]->data[i] = value;
        return;
    }
    uint _826 = atomic_fetch_and_explicit((device atomic_uint*)&g_buf[0]->data[i], ~mask, memory_order_relaxed);
    uint _832 = atomic_fetch_or_explicit((device atomic_uint*)&g_buf[0]->data[i], value & mask, memory_order_relaxed);
}

static inline __attribute__((always_inline))
void native_frame_store(thread const uint& addr, thread const uint& rgba, device GsBuffer* (&g_buf)[16], constant Push& pc)
{
    uint psm = pc.frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint shift = (addr & 1u) * 16u;
        uint param = rgba;
        uint param_1 = addr >> uint(1);
        uint param_2 = gs_pack16(param) << shift;
        uint param_3 = frame_write_mask16(pc) << shift;
        native_store_masked(param_1, param_2, param_3, g_buf);
        return;
    }
    uint mask = (psm == 1u) ? 16777215u : 4294967295u;
    uint param_4 = addr;
    uint param_5 = rgba;
    uint param_6 = mask & (~pc.frame_mask);
    native_store_masked(param_4, param_5, param_6, g_buf);
}

static inline __attribute__((always_inline))
uint gs_sample_cols(thread const uint& samples)
{
    if (samples >= 8u)
    {
        return 4u;
    }
    if (samples >= 4u)
    {
        return 2u;
    }
    return 1u;
}

static inline __attribute__((always_inline))
int gs_sample_x(thread const uint& samples, thread const uint& s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    return int(((((s % cols) * 2u) + 1u) * 8u) / cols);
}

static inline __attribute__((always_inline))
int gs_sample_y(thread const uint& samples, thread const uint& s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    uint rows = samples / cols;
    return int((((((s / cols) % rows) * 2u) + 1u) * 8u) / rows);
}

static inline __attribute__((always_inline))
uint gs_center_sample(thread const uint& samples)
{
    uint best = 0u;
    int best_d = 1073741824;
    for (uint s = 0u; s < samples; s++)
    {
        uint param = samples;
        uint param_1 = s;
        int dx = gs_sample_x(param, param_1) - 8;
        uint param_2 = samples;
        uint param_3 = s;
        int dy = gs_sample_y(param_2, param_3) - 8;
        int d = (dx * dx) + (dy * dy);
        if (d < best_d)
        {
            best_d = d;
            best = s;
        }
    }
    return best;
}

static inline __attribute__((always_inline))
uint shadow_z_pixel(thread const uint& addr, thread const uint& s, device GsBuffer* (&g_buf)[16], constant Push& pc)
{
    uint psm = pc.z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint param = addr >> uint(1);
        uint param_1 = s;
        uint w = g_buf[5]->data[plane_word(param, param_1)];
        uint _905;
        if ((addr & 1u) != 0u)
        {
            _905 = w >> uint(16);
        }
        else
        {
            _905 = w & 65535u;
        }
        return _905;
    }
    uint param_2 = addr;
    uint param_3 = s;
    uint w_1 = g_buf[5]->data[plane_word(param_2, param_3)];
    uint _925;
    if (psm == 49u)
    {
        _925 = w_1 & 16777215u;
    }
    else
    {
        _925 = w_1;
    }
    return _925;
}

static inline __attribute__((always_inline))
void native_z_store(thread const uint& addr, thread const uint& z, device GsBuffer* (&g_buf)[16], constant Push& pc)
{
    uint psm = pc.z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint shift = (addr & 1u) * 16u;
        uint param = addr >> uint(1);
        uint param_1 = (z & 65535u) << shift;
        uint param_2 = 65535u << shift;
        native_store_masked(param, param_1, param_2, g_buf);
        return;
    }
    uint mask = (psm == 49u) ? 16777215u : 4294967295u;
    uint param_3 = addr;
    uint param_4 = z & mask;
    uint param_5 = mask;
    native_store_masked(param_3, param_4, param_5, g_buf);
}

static inline __attribute__((always_inline))
void resolve(device GsBuffer* (&g_buf)[16], constant Push& pc, thread uint3& gl_WorkGroupID, thread uint& gl_LocalInvocationIndex)
{
    uint px = (pc.x0 + (gl_WorkGroupID.x * 8u)) + (gl_LocalInvocationIndex & 7u);
    uint py = (pc.y0 + (gl_WorkGroupID.y * 8u)) + (gl_LocalInvocationIndex >> uint(3));
    bool _1128 = px > pc.x1;
    bool _1137;
    if (!_1128)
    {
        _1137 = py > pc.y1;
    }
    else
    {
        _1137 = _1128;
    }
    if (_1137)
    {
        return;
    }
    uint param = pc.frame_psm;
    uint param_1 = pc.frame_base_block;
    uint param_2 = pc.frame_bw;
    uint param_3 = px;
    uint param_4 = py;
    uint faddr = gs_pixel_addr(param, param_1, param_2, param_3, param_4);
    uint acc0 = 0u;
    uint acc1 = 0u;
    uint acc2 = 0u;
    uint acc3 = 0u;
    for (uint s = 0u; s < pc.samples; s++)
    {
        uint param_5 = faddr;
        uint param_6 = s;
        uint c = shadow_frame_pixel(param_5, param_6, g_buf, pc);
        acc0 += (c & 255u);
        acc1 += ((c >> uint(8)) & 255u);
        acc2 += ((c >> uint(16)) & 255u);
        acc3 += ((c >> uint(24)) & 255u);
    }
    uint bias0 = pc.samples >> uint(1);
    uint rgba = ((((acc0 + bias0) / pc.samples) | (((acc1 + bias0) / pc.samples) << uint(8))) | (((acc2 + bias0) / pc.samples) << uint(16))) | (((acc3 + bias0) / pc.samples) << uint(24));
    uint param_7 = faddr;
    uint param_8 = rgba;
    native_frame_store(param_7, param_8, g_buf, pc);
    if (pc.z_write != 0u)
    {
        uint param_9 = pc.z_psm;
        uint param_10 = pc.z_base_block;
        uint param_11 = pc.frame_bw;
        uint param_12 = px;
        uint param_13 = py;
        uint zaddr = gs_pixel_addr(param_9, param_10, param_11, param_12, param_13);
        uint param_14 = pc.samples;
        uint param_15 = zaddr;
        uint param_16 = gs_center_sample(param_14);
        uint param_17 = zaddr;
        uint param_18 = shadow_z_pixel(param_15, param_16, g_buf, pc);
        native_z_store(param_17, param_18, g_buf, pc);
    }
}

kernel void main0(device GsBuffer* g_buf_0 [[buffer(4)]], device GsBuffer* g_buf_1 [[buffer(5)]], device GsBuffer* g_buf_2 [[buffer(6)]], device GsBuffer* g_buf_3 [[buffer(7)]], device GsBuffer* g_buf_4 [[buffer(8)]], device GsBuffer* g_buf_5 [[buffer(9)]], device GsBuffer* g_buf_6 [[buffer(10)]], device GsBuffer* g_buf_7 [[buffer(11)]], device GsBuffer* g_buf_8 [[buffer(12)]], device GsBuffer* g_buf_9 [[buffer(13)]], device GsBuffer* g_buf_10 [[buffer(14)]], device GsBuffer* g_buf_11 [[buffer(15)]], device GsBuffer* g_buf_12 [[buffer(16)]], device GsBuffer* g_buf_13 [[buffer(17)]], device GsBuffer* g_buf_14 [[buffer(18)]], device GsBuffer* g_buf_15 [[buffer(19)]], constant Push& pc [[buffer(20)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]])
{
    device GsBuffer* g_buf[] =
    {
        g_buf_0,
        g_buf_1,
        g_buf_2,
        g_buf_3,
        g_buf_4,
        g_buf_5,
        g_buf_6,
        g_buf_7,
        g_buf_8,
        g_buf_9,
        g_buf_10,
        g_buf_11,
        g_buf_12,
        g_buf_13,
        g_buf_14,
        g_buf_15,
    };

    if (pc.mode == 0u)
    {
        seed(g_buf, pc, gl_WorkGroupID, gl_LocalInvocationIndex);
    }
    else
    {
        resolve(g_buf, pc, gl_WorkGroupID, gl_LocalInvocationIndex);
    }
}
