// src/runtime/gs/render/shaders/hlsl/overlay.vert.hlsl: HLSL for src/runtime/gs/render/shaders/overlay.vert, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The registers were rewritten to the convention in
// src/runtime/rhi/d3d12/rhi_d3d12_bindings.h; that header says why.

cbuffer Push : register(b4, space0)
{
    row_major float4x4 pc_transform : packoffset(c0);
    float2 pc_surface_size : packoffset(c4);
    float2 pc_translate : packoffset(c4.z);
    uint pc_use_transform : packoffset(c5);
    uint pc_use_texture : packoffset(c5.y);
};


static float4 gl_Position;
static float2 a_position;
static float2 v_uv;
static float2 a_uv;
static float4 v_color;
static float4 a_color;

struct SPIRV_Cross_Input
{
    float2 a_position : TEXCOORD0;
    float2 a_uv : TEXCOORD1;
    float4 a_color : TEXCOORD2;
};

struct SPIRV_Cross_Output
{
    float2 v_uv : TEXCOORD0;
    float4 v_color : TEXCOORD1;
    float4 gl_Position : SV_Position;
};

void vert_main()
{
    float4 p = float4(a_position + pc_translate, 0.0f, 1.0f);
    if (pc_use_transform != 0u)
    {
        p = mul(p, pc_transform);
    }
    gl_Position = float4(((2.0f * p.x) / pc_surface_size.x) - p.w, ((2.0f * p.y) / pc_surface_size.y) - p.w, 0.0f, p.w);
    v_uv = a_uv;
    v_color = a_color;
    gl_Position.y = -gl_Position.y;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    a_position = stage_input.a_position;
    a_uv = stage_input.a_uv;
    a_color = stage_input.a_color;
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.v_uv = v_uv;
    stage_output.v_color = v_color;
    return stage_output;
}
