// src/runtime/gs/render/shaders/hlsl/overlay.frag.hlsl: HLSL for src/runtime/gs/render/shaders/overlay.frag, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The registers were rewritten to the convention in
// src/runtime/rhi/d3d12/rhi_d3d12_bindings.h; that header says why.

cbuffer Push : register(b4, space0)
{
    row_major float4x4 pc_transform : packoffset(c0);
    float2 pc_surface_size : packoffset(c4);
    float2 pc_translate : packoffset(c4.z);
    uint pc_use_transform : packoffset(c5);
    uint pc_use_texture : packoffset(c5.y);
};

Texture2D<float4> g_textures[8] : register(t0, space0);
SamplerState g_samplers[4] : register(s0, space0);

static float4 v_color;
static float2 v_uv;
static float4 o_color;

struct SPIRV_Cross_Input
{
    float2 v_uv : TEXCOORD0;
    float4 v_color : TEXCOORD1;
};

struct SPIRV_Cross_Output
{
    float4 o_color : SV_Target0;
};

void frag_main()
{
    float4 c = v_color;
    if (pc_use_texture != 0u)
    {
        c *= g_textures[0].Sample(g_samplers[1], v_uv);
    }
    o_color = c;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    v_color = stage_input.v_color;
    v_uv = stage_input.v_uv;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.o_color = o_color;
    return stage_output;
}
