// src/runtime/gs/render/shaders/hlsl/shadow.comp.hlsl: HLSL for src/runtime/gs/render/shaders/shadow.comp, generated by
// tools/gen_gs_shaders.sh from the committed SPIR-V through SPIRV-Cross.
// Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand.
// The registers were rewritten to the convention in
// src/runtime/rhi/d3d12/rhi_d3d12_bindings.h; that header says why.

static const uint _329[32] = { 0u, 1u, 4u, 5u, 16u, 17u, 20u, 21u, 2u, 3u, 6u, 7u, 18u, 19u, 22u, 23u, 8u, 9u, 12u, 13u, 24u, 25u, 28u, 29u, 10u, 11u, 14u, 15u, 26u, 27u, 30u, 31u };
static const uint _340[32] = { 24u, 25u, 28u, 29u, 8u, 9u, 12u, 13u, 26u, 27u, 30u, 31u, 10u, 11u, 14u, 15u, 16u, 17u, 20u, 21u, 0u, 1u, 4u, 5u, 18u, 19u, 22u, 23u, 2u, 3u, 6u, 7u };
static const uint _353[32] = { 0u, 2u, 8u, 10u, 1u, 3u, 9u, 11u, 4u, 6u, 12u, 14u, 5u, 7u, 13u, 15u, 16u, 18u, 24u, 26u, 17u, 19u, 25u, 27u, 20u, 22u, 28u, 30u, 21u, 23u, 29u, 31u };
static const uint _363[32] = { 0u, 2u, 16u, 18u, 1u, 3u, 17u, 19u, 8u, 10u, 24u, 26u, 9u, 11u, 25u, 27u, 4u, 6u, 20u, 22u, 5u, 7u, 21u, 23u, 12u, 14u, 28u, 30u, 13u, 15u, 29u, 31u };
static const uint _373[32] = { 24u, 26u, 16u, 18u, 25u, 27u, 17u, 19u, 28u, 30u, 20u, 22u, 29u, 31u, 21u, 23u, 8u, 10u, 0u, 2u, 9u, 11u, 1u, 3u, 12u, 14u, 4u, 6u, 13u, 15u, 5u, 7u };
static const uint _383[32] = { 24u, 26u, 8u, 10u, 25u, 27u, 9u, 11u, 16u, 18u, 0u, 2u, 17u, 19u, 1u, 3u, 28u, 30u, 12u, 14u, 29u, 31u, 13u, 15u, 20u, 22u, 4u, 6u, 21u, 23u, 5u, 7u };
static const uint _421[16] = { 0u, 1u, 4u, 5u, 8u, 9u, 12u, 13u, 2u, 3u, 6u, 7u, 10u, 11u, 14u, 15u };

RWByteAddressBuffer g_buf[16] : register(u0, space0);
cbuffer Push : register(b4, space0)
{
    uint pc_mode : packoffset(c0);
    uint pc_samples : packoffset(c0.y);
    uint pc_frame_base_block : packoffset(c0.z);
    uint pc_frame_bw : packoffset(c0.w);
    uint pc_frame_psm : packoffset(c1);
    uint pc_frame_mask : packoffset(c1.y);
    uint pc_z_base_block : packoffset(c1.z);
    uint pc_z_psm : packoffset(c1.w);
    uint pc_z_write : packoffset(c2);
    uint pc_x0 : packoffset(c2.y);
    uint pc_y0 : packoffset(c2.z);
    uint pc_x1 : packoffset(c2.w);
    uint pc_y1 : packoffset(c3);
};


static uint3 gl_WorkGroupID;
static uint gl_LocalInvocationIndex;
struct SPIRV_Cross_Input
{
    uint3 gl_WorkGroupID : SV_GroupID;
    uint gl_LocalInvocationIndex : SV_GroupIndex;
};

uint plane_word(uint word, uint s)
{
    return (word & 1048575u) + (s * 1048576u);
}

void seed()
{
    uint page = g_buf[1].Load(gl_WorkGroupID.x * 4 + 0);
    uint base = (page & 511u) * 2048u;
    for (uint w = gl_LocalInvocationIndex; w < 2048u; w += 64u)
    {
        uint v = g_buf[0].Load((base + w) * 4 + 0);
        for (uint s = 0u; s < pc_samples; s++)
        {
            uint param = base + w;
            uint param_1 = s;
            g_buf[5].Store(plane_word(param, param_1) * 4 + 0, v);
        }
    }
}

uint gs_psm_family(uint psm)
{
    if (((((psm == 0u) || (psm == 1u)) || (psm == 27u)) || (psm == 36u)) || (psm == 44u))
    {
        return 0u;
    }
    if ((psm == 48u) || (psm == 49u))
    {
        return 5u;
    }
    if (psm == 2u)
    {
        return 1u;
    }
    if (psm == 10u)
    {
        return 2u;
    }
    if (psm == 50u)
    {
        return 6u;
    }
    if (psm == 58u)
    {
        return 7u;
    }
    if (psm == 19u)
    {
        return 3u;
    }
    if (psm == 20u)
    {
        return 4u;
    }
    return 255u;
}

uint gs_page_width(uint fam)
{
    if ((fam == 3u) || (fam == 4u))
    {
        return 128u;
    }
    return 64u;
}

uint gs_page_height(uint fam)
{
    if (fam == 4u)
    {
        return 128u;
    }
    if (fam == 3u)
    {
        return 64u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 32u;
    }
    return 64u;
}

uint gs_block_width(uint fam)
{
    if (fam == 4u)
    {
        return 32u;
    }
    if (fam == 3u)
    {
        return 16u;
    }
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    return 16u;
}

uint gs_block_height(uint fam)
{
    if ((fam == 0u) || (fam == 5u))
    {
        return 8u;
    }
    if ((fam == 3u) || (fam == 4u))
    {
        return 16u;
    }
    return 8u;
}

uint gs_page_block_cols(uint fam)
{
    uint param = fam;
    uint param_1 = fam;
    return gs_page_width(param) / gs_block_width(param_1);
}

uint gs_block_number(uint fam, uint bx, uint by)
{
    uint param = fam;
    uint i = (by * gs_page_block_cols(param)) + bx;
    if ((fam == 0u) || (fam == 3u))
    {
        return _329[i];
    }
    if (fam == 5u)
    {
        return _340[i];
    }
    if ((fam == 1u) || (fam == 4u))
    {
        return _353[i];
    }
    if (fam == 2u)
    {
        return _363[i];
    }
    if (fam == 6u)
    {
        return _373[i];
    }
    if (fam == 7u)
    {
        return _383[i];
    }
    return 0u;
}

uint gs_addr_bits(uint psm)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    if (fam == 3u)
    {
        return 8u;
    }
    if (fam == 4u)
    {
        return 4u;
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        return 16u;
    }
    return 32u;
}

uint gs_block_offset(uint fam, uint x, uint y)
{
    uint param = fam;
    uint bw = gs_block_width(param);
    uint param_1 = fam;
    uint bh = gs_block_height(param_1);
    uint lx = x % bw;
    uint ly = y % bh;
    if ((fam == 0u) || (fam == 5u))
    {
        uint col = ly >> uint(1);
        return (col * 16u) + _421[((ly & 1u) * 8u) + (lx & 7u)];
    }
    if ((((fam == 1u) || (fam == 2u)) || (fam == 6u)) || (fam == 7u))
    {
        uint col_1 = ly >> uint(1);
        uint w = _421[((ly & 1u) * 8u) + (lx & 7u)];
        uint hword = (lx >> uint(3)) & 1u;
        return ((col_1 * 32u) + (w * 2u)) + hword;
    }
    uint col_2 = ly >> uint(2);
    uint row = ly & 3u;
    uint rot = (row >= 2u) ? 4u : 0u;
    uint w_1 = _421[(((lx >> uint(3)) & 1u) * 8u) + (((lx & 7u) + rot) & 7u)];
    uint _501;
    if (row == 0u)
    {
        _501 = 0u;
    }
    else
    {
        uint _507;
        if (row == 1u)
        {
            _507 = 2u;
        }
        else
        {
            _507 = (row == 2u) ? 1u : 3u;
        }
        _501 = _507;
    }
    uint sub = _501;
    if ((col_2 & 1u) != 0u)
    {
        sub ^= 2u;
    }
    if (fam == 3u)
    {
        return ((col_2 * 64u) + (w_1 * 4u)) + sub;
    }
    uint nib = (((lx >> uint(4)) & 1u) * 4u) + sub;
    return ((col_2 * 128u) + (w_1 * 8u)) + nib;
}

uint gs_pixel_addr(uint psm, uint base_block, uint fbw, uint x, uint y)
{
    uint param = psm;
    uint fam = gs_psm_family(param);
    uint param_1 = fam;
    uint pw = gs_page_width(param_1);
    uint param_2 = fam;
    uint ph = gs_page_height(param_2);
    uint pages_across = (fbw * 64u) / pw;
    if (pages_across == 0u)
    {
        pages_across = 1u;
    }
    uint page = ((y / ph) * pages_across) + (x / pw);
    uint param_3 = fam;
    uint bx = (x % pw) / gs_block_width(param_3);
    uint param_4 = fam;
    uint by = (y % ph) / gs_block_height(param_4);
    uint param_5 = fam;
    uint param_6 = bx;
    uint param_7 = by;
    uint block = ((base_block + (page * 32u)) + gs_block_number(param_5, param_6, param_7)) & 16383u;
    uint param_8 = psm;
    uint units_per_block = 2048u / gs_addr_bits(param_8);
    uint param_9 = fam;
    uint param_10 = x;
    uint param_11 = y;
    return (block * units_per_block) + gs_block_offset(param_9, param_10, param_11);
}

uint gs_expand16(uint v)
{
    uint r = (v & 31u) << uint(3);
    uint g = ((v >> uint(5)) & 31u) << uint(3);
    uint b = ((v >> uint(10)) & 31u) << uint(3);
    uint a = ((v >> uint(15)) & 1u) * 128u;
    return ((r | (g << uint(8))) | (b << uint(16))) | (a << uint(24));
}

uint shadow_frame_pixel(uint addr, uint s)
{
    uint psm = pc_frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint param = addr >> uint(1);
        uint param_1 = s;
        uint w = g_buf[5].Load(plane_word(param, param_1) * 4 + 0);
        uint _860;
        if ((addr & 1u) != 0u)
        {
            _860 = w >> uint(16);
        }
        else
        {
            _860 = w & 65535u;
        }
        uint hw = _860;
        uint param_2 = hw;
        return gs_expand16(param_2);
    }
    uint param_3 = addr;
    uint param_4 = s;
    return g_buf[5].Load(plane_word(param_3, param_4) * 4 + 0);
}

uint gs_pack16(uint rgba)
{
    return ((((rgba & 255u) >> uint(3)) | ((((rgba >> uint(8)) & 255u) >> uint(3)) << uint(5))) | ((((rgba >> uint(16)) & 255u) >> uint(3)) << uint(10))) | ((((rgba >> uint(24)) & 255u) >> uint(7)) << uint(15));
}

uint frame_write_mask16()
{
    uint m = ((((pc_frame_mask >> uint(3)) & 31u) | (((pc_frame_mask >> uint(11)) & 31u) << uint(5))) | (((pc_frame_mask >> uint(19)) & 31u) << uint(10))) | (((pc_frame_mask >> uint(31)) & 1u) << uint(15));
    return (~m) & 65535u;
}

void native_store_masked(uint word, uint value, uint mask)
{
    if (mask == 0u)
    {
        return;
    }
    uint i = word & 1048575u;
    if (mask == 4294967295u)
    {
        g_buf[0].Store(i * 4 + 0, value);
        return;
    }
    uint _826;
    g_buf[0].InterlockedAnd(i * 4 + 0, ~mask, _826);
    uint _832;
    g_buf[0].InterlockedOr(i * 4 + 0, value & mask, _832);
}

void native_frame_store(uint addr, uint rgba)
{
    uint psm = pc_frame_psm;
    if ((psm == 2u) || (psm == 10u))
    {
        uint shift = (addr & 1u) * 16u;
        uint param = rgba;
        uint param_1 = addr >> uint(1);
        uint param_2 = gs_pack16(param) << shift;
        uint param_3 = frame_write_mask16() << shift;
        native_store_masked(param_1, param_2, param_3);
        return;
    }
    uint mask = (psm == 1u) ? 16777215u : 4294967295u;
    uint param_4 = addr;
    uint param_5 = rgba;
    uint param_6 = mask & (~pc_frame_mask);
    native_store_masked(param_4, param_5, param_6);
}

uint gs_sample_cols(uint samples)
{
    if (samples >= 8u)
    {
        return 4u;
    }
    if (samples >= 4u)
    {
        return 2u;
    }
    return 1u;
}

int gs_sample_x(uint samples, uint s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    return int(((((s % cols) * 2u) + 1u) * 8u) / cols);
}

int gs_sample_y(uint samples, uint s)
{
    uint param = samples;
    uint cols = gs_sample_cols(param);
    uint rows = samples / cols;
    return int((((((s / cols) % rows) * 2u) + 1u) * 8u) / rows);
}

uint gs_center_sample(uint samples)
{
    uint best = 0u;
    int best_d = 1073741824;
    for (uint s = 0u; s < samples; s++)
    {
        uint param = samples;
        uint param_1 = s;
        int dx = gs_sample_x(param, param_1) - 8;
        uint param_2 = samples;
        uint param_3 = s;
        int dy = gs_sample_y(param_2, param_3) - 8;
        int d = (dx * dx) + (dy * dy);
        if (d < best_d)
        {
            best_d = d;
            best = s;
        }
    }
    return best;
}

uint shadow_z_pixel(uint addr, uint s)
{
    uint psm = pc_z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint param = addr >> uint(1);
        uint param_1 = s;
        uint w = g_buf[5].Load(plane_word(param, param_1) * 4 + 0);
        uint _905;
        if ((addr & 1u) != 0u)
        {
            _905 = w >> uint(16);
        }
        else
        {
            _905 = w & 65535u;
        }
        return _905;
    }
    uint param_2 = addr;
    uint param_3 = s;
    uint w_1 = g_buf[5].Load(plane_word(param_2, param_3) * 4 + 0);
    uint _925;
    if (psm == 49u)
    {
        _925 = w_1 & 16777215u;
    }
    else
    {
        _925 = w_1;
    }
    return _925;
}

void native_z_store(uint addr, uint z)
{
    uint psm = pc_z_psm;
    if ((psm == 50u) || (psm == 58u))
    {
        uint shift = (addr & 1u) * 16u;
        uint param = addr >> uint(1);
        uint param_1 = (z & 65535u) << shift;
        uint param_2 = 65535u << shift;
        native_store_masked(param, param_1, param_2);
        return;
    }
    uint mask = (psm == 49u) ? 16777215u : 4294967295u;
    uint param_3 = addr;
    uint param_4 = z & mask;
    uint param_5 = mask;
    native_store_masked(param_3, param_4, param_5);
}

void resolve()
{
    uint px = (pc_x0 + (gl_WorkGroupID.x * 8u)) + (gl_LocalInvocationIndex & 7u);
    uint py = (pc_y0 + (gl_WorkGroupID.y * 8u)) + (gl_LocalInvocationIndex >> uint(3));
    bool _1128 = px > pc_x1;
    bool _1137;
    if (!_1128)
    {
        _1137 = py > pc_y1;
    }
    else
    {
        _1137 = _1128;
    }
    if (_1137)
    {
        return;
    }
    uint param = pc_frame_psm;
    uint param_1 = pc_frame_base_block;
    uint param_2 = pc_frame_bw;
    uint param_3 = px;
    uint param_4 = py;
    uint faddr = gs_pixel_addr(param, param_1, param_2, param_3, param_4);
    uint acc0 = 0u;
    uint acc1 = 0u;
    uint acc2 = 0u;
    uint acc3 = 0u;
    for (uint s = 0u; s < pc_samples; s++)
    {
        uint param_5 = faddr;
        uint param_6 = s;
        uint c = shadow_frame_pixel(param_5, param_6);
        acc0 += (c & 255u);
        acc1 += ((c >> uint(8)) & 255u);
        acc2 += ((c >> uint(16)) & 255u);
        acc3 += ((c >> uint(24)) & 255u);
    }
    uint bias = pc_samples >> uint(1);
    uint rgba = ((((acc0 + bias) / pc_samples) | (((acc1 + bias) / pc_samples) << uint(8))) | (((acc2 + bias) / pc_samples) << uint(16))) | (((acc3 + bias) / pc_samples) << uint(24));
    uint param_7 = faddr;
    uint param_8 = rgba;
    native_frame_store(param_7, param_8);
    if (pc_z_write != 0u)
    {
        uint param_9 = pc_z_psm;
        uint param_10 = pc_z_base_block;
        uint param_11 = pc_frame_bw;
        uint param_12 = px;
        uint param_13 = py;
        uint zaddr = gs_pixel_addr(param_9, param_10, param_11, param_12, param_13);
        uint param_14 = pc_samples;
        uint param_15 = zaddr;
        uint param_16 = gs_center_sample(param_14);
        uint param_17 = zaddr;
        uint param_18 = shadow_z_pixel(param_15, param_16);
        native_z_store(param_17, param_18);
    }
}

void comp_main()
{
    if (pc_mode == 0u)
    {
        seed();
    }
    else
    {
        resolve();
    }
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_WorkGroupID = stage_input.gl_WorkGroupID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
