#!/usr/bin/env bash
# tools/gen_overlay_spirv.sh: compiles gs/overlay.{vert,frag} (GLSL, ours,
# not ROM-derived) into src/runtime/gs/overlay_shaders.inc, a committed C
# array of SPIR-V words consumed by gs_parallel_lib.cpp's overlay render
# pass (RtPgs::draw_overlay).
#
# Precedent: the vendored paraLLEl-GS compiles its own shaders ahead of time
# the same way, via slangmosh (see third_party/parallel-gs/gs/shaders/
# slangmosh.hpp and gs/slangmosh.sh) -- this repo's standalone build has no
# runtime shader compiler (GRANITE_SHIPPING), so the overlay pass needs its
# SPIR-V compiled and checked in rather than compiled from GLSL at run time.
#
# Rerun this script whenever overlay.vert or overlay.frag changes; the
# output is committed, not generated at build time.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

GLSLANG=""
if command -v glslangValidator >/dev/null 2>&1; then
    GLSLANG="$(command -v glslangValidator)"
    echo "gen_overlay_spirv: using glslangValidator from PATH ($GLSLANG)"
else
    echo "gen_overlay_spirv: glslangValidator not on PATH, building it from the vendored glslang"
    SRC=third_party/parallel-gs/Granite/third_party/glslang
    BUILD=build/glslang-tools
    GLSLANG="$BUILD/StandAlone/glslangValidator"
    if [[ ! -x "$GLSLANG" ]]; then
        cmake -S "$SRC" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_OPT=OFF -DENABLE_HLSL=OFF -DENABLE_GLSLANG_BINARIES=ON \
            -DENABLE_CTEST=OFF -DBUILD_TESTING=OFF
        # The CMake target that builds the glslangValidator binary is named
        # glslang-standalone, not glslangValidator (that name refers to the
        # binary this whole script exists to produce).
        cmake --build "$BUILD" --target glslang-standalone -j2
    fi
fi

if [[ ! -x "$GLSLANG" ]]; then
    echo "gen_overlay_spirv: no usable glslangValidator at $GLSLANG" >&2
    exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

"$GLSLANG" -V --target-env vulkan1.1 -o "$TMP/overlay.vert.spv" src/runtime/gs/overlay.vert
"$GLSLANG" -V --target-env vulkan1.1 -o "$TMP/overlay.frag.spv" src/runtime/gs/overlay.frag

# Emits `static const uint32_t <name>[] = { ... };` from a raw SPIR-V binary.
# SPIR-V is a stream of little-endian 32-bit words regardless of host
# endianness (Vulkan spec, 2.2.1); struct.unpack("<I", ...) decodes it as
# such rather than relying on host byte order.
emit_array() {
    local name="$1" spv="$2"
    echo "static const uint32_t ${name}[] = {"
    python3 - "$spv" <<'PY'
import struct
import sys

data = open(sys.argv[1], "rb").read()
assert len(data) % 4 == 0, "SPIR-V binary size is not a multiple of 4"
words = struct.unpack("<%uI" % (len(data) // 4), data)
for i in range(0, len(words), 8):
    chunk = words[i:i + 8]
    print("    " + ", ".join("0x%08xu" % w for w in chunk) + ",")
PY
    echo "};"
}

OUT=src/runtime/gs/overlay_shaders.inc
{
    echo "/* gs/overlay_shaders.inc: SPIR-V for gs/overlay.vert and gs/overlay.frag,"
    echo " * generated by tools/gen_overlay_spirv.sh from that GLSL source. Ours"
    echo " * (MIT), our own shader source, not ROM-derived. Do not edit by hand;"
    echo " * rerun the script after changing the .vert/.frag files."
    echo " */"
    emit_array kOverlayVertSpv "$TMP/overlay.vert.spv"
    emit_array kOverlayFragSpv "$TMP/overlay.frag.spv"
} > "$OUT"

echo "gen_overlay_spirv: wrote $OUT ($(wc -c < "$OUT") bytes)"
