# tools/gen_gs_shaders_dxil.ps1: compiles the committed HLSL into signed DXIL
# and writes the index header the D3D12 backend includes.
#
# Runs on Windows only, and it has to: DXIL is rejected by drivers unless it
# carries a signature, and only dxil.dll can produce one. dxil.dll ships with
# the Windows SDK and with a DXC release and is not redistributable through
# this repository, which is why this step is not part of
# tools/gen_gs_shaders.sh and why its output is committed rather than built.
#
# Inputs   src/runtime/gs/render/shaders/hlsl/*.hlsl  (tools/gen_gs_shaders.sh)
#          src/runtime/gs/render/shaders/shaders.manifest, the shader list the
#          same script writes, read here so this stage cannot compile a
#          different set from the one the SPIR-V, HLSL and MSL indexes carry
#          src/runtime/rhi/d3d12/rhi_d3d12_shaders.cpp for the blit shader,
#          which has no GLSL because Vulkan blits with vkCmdBlitImage
# Outputs  src/runtime/gs/render/shaders/dxil/<name>.<stage>.dxil.inc
#          src/runtime/rhi/rhi_shaders_dxil.h
#
# dxc.exe is taken from -Dxc, then from PATH, then from the newest
# %ProgramFiles(x86)%\Windows Kits\10\bin\*\x64\dxc.exe.

[CmdletBinding()]
param(
    [string]$Dxc = "",
    [switch]$SkipBlit
)

$ErrorActionPreference = "Stop"
Set-Location (& git rev-parse --show-toplevel)

$HlslDir  = "src/runtime/gs/render/shaders/hlsl"
$DxilDir  = "src/runtime/gs/render/shaders/dxil"
$Index    = "src/runtime/rhi/rhi_shaders_dxil.h"
$Manifest = "src/runtime/gs/render/shaders/shaders.manifest"

# The shader list, read from the manifest tools/gen_gs_shaders.sh writes rather
# than repeated here. A second hand-kept list is how shadow.comp came to be
# missing from this stage while the SPIR-V, HLSL and MSL indexes all carried
# it. The shader model follows from the stage; entry is always main, because
# that is what glslang emits and what SPIRV-Cross keeps for HLSL.
$Targets = @{ comp = "cs_6_0"; vert = "vs_6_0"; frag = "ps_6_0" }

if (-not (Test-Path $Manifest)) {
    throw "$Manifest is missing. Run tools/gen_gs_shaders.sh first."
}
$Shaders = @()
foreach ($line in Get-Content $Manifest) {
    $t = $line.Trim()
    if ($t -eq "" -or $t.StartsWith("#")) { continue }
    $parts = $t -split "\s+"
    if ($parts.Count -ne 2) { throw "$Manifest has a line this script cannot read: '$line'" }
    if (-not $Targets.ContainsKey($parts[1])) {
        throw "$Manifest names stage '$($parts[1])', which has no shader model here. " +
              "Add it to `$Targets."
    }
    $Shaders += @{ name = $parts[0]; stage = $parts[1]; target = $Targets[$parts[1]]; entry = "main" }
}
if ($Shaders.Count -eq 0) { throw "$Manifest lists no shaders." }

function Resolve-Dxc {
    param([string]$Hint)
    if ($Hint -and (Test-Path $Hint)) { return (Resolve-Path $Hint).Path }
    $onPath = Get-Command dxc.exe -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    $kits = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin"
    if (Test-Path $kits) {
        $found = Get-ChildItem -Path $kits -Filter dxc.exe -Recurse -ErrorAction SilentlyContinue |
                 Where-Object { $_.FullName -match "\\x64\\" } |
                 Sort-Object FullName -Descending
        if ($found) { return $found[0].FullName }
    }
    throw "dxc.exe was not found. Pass -Dxc <path>, put it on PATH, or install the Windows SDK."
}

# The SHA-1 of some bytes, bare lower-case hex. It ties a committed DXIL
# container to the HLSL it was compiled from; tools/check_shaders_fresh.py
# recomputes it and the runtime build fails when the two have drifted.
function Get-Sha1Hex {
    param([byte[]]$Bytes)
    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try {
        return (($sha1.ComputeHash($Bytes) | ForEach-Object { "{0:x2}" -f $_ }) -join "")
    } finally {
        $sha1.Dispose()
    }
}

function Write-Inc {
    param([string]$Path, [string]$Symbol, [string]$Source, [byte[]]$Bytes, [string]$Digest)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("/* $Path`: DXIL for $Source, generated by tools/gen_gs_shaders_dxil.ps1.")
    [void]$sb.AppendLine(" * Ours (MIT), our own shader source, not ROM-derived. Do not edit by hand;")
    [void]$sb.AppendLine(" * rerun the script after rerunning tools/gen_gs_shaders.sh.")
    [void]$sb.AppendLine(" *")
    [void]$sb.AppendLine(" * source SHA-1: $Digest")
    [void]$sb.AppendLine(" */")
    [void]$sb.AppendLine("inline constexpr uint8_t $Symbol[] = {")
    for ($i = 0; $i -lt $Bytes.Length; $i += 12) {
        $chunk = $Bytes[$i..([Math]::Min($i + 11, $Bytes.Length - 1))]
        $line = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
        [void]$sb.AppendLine("    $line,")
    }
    [void]$sb.AppendLine("};")
    [System.IO.File]::WriteAllText($Path, $sb.ToString())
}

$dxcPath = Resolve-Dxc $Dxc
Write-Host "gen_gs_shaders_dxil: using $dxcPath"
New-Item -ItemType Directory -Force -Path $DxilDir | Out-Null

$entries = @()

foreach ($s in $Shaders) {
    $src = "$HlslDir/$($s.name).$($s.stage).hlsl"
    if (-not (Test-Path $src)) {
        throw "$src is missing. Run tools/gen_gs_shaders.sh with spirv-cross available first."
    }
    $obj = [System.IO.Path]::GetTempFileName()
    # -Zpc: column-major matrices, matching the -Zpc the run-time dxcompiler
    # path passes and the convention overlay.vert declares.
    & $dxcPath -T $s.target -E $s.entry -Zpc -O3 -Fo $obj $src
    if ($LASTEXITCODE -ne 0) { throw "dxc failed on $src" }
    $bytes = [System.IO.File]::ReadAllBytes($obj)
    Remove-Item $obj -Force
    $sym = "kDxil_$($s.name)_$($s.stage)"
    $inc = "$DxilDir/$($s.name).$($s.stage).dxil.inc"
    $digest = Get-Sha1Hex ([System.IO.File]::ReadAllBytes($src))
    Write-Inc -Path $inc -Symbol $sym -Source $src -Bytes $bytes -Digest $digest
    Write-Host "gen_gs_shaders_dxil: wrote $inc ($($bytes.Length) bytes, source $digest)"
    $entries += @{ name = "$($s.name).$($s.stage)"; symbol = $sym; inc = $inc; digest = $digest }
}

# The present blit. Its HLSL lives inside the D3D12 backend because there is
# no GLSL twin for it, so it is lifted out of the string literal in
# rhi_d3d12_shaders.cpp rather than kept in a second copy here.
if (-not $SkipBlit) {
    $cpp = Get-Content "src/runtime/rhi/d3d12/rhi_d3d12_shaders.cpp" -Raw
    $m = [regex]::Match($cpp, 'const char kBlitHlsl\[\] =\s*(?<body>(?:\s*"(?:[^"\\]|\\.)*"\s*)+);')
    if (-not $m.Success) {
        throw "the kBlitHlsl literal was not found in rhi_d3d12_shaders.cpp; the blit " +
              "shader and this extractor have drifted apart."
    }
    # One pass over the escapes, matching the Linux twin and
    # tools/check_shaders_fresh.py: three chained -replace calls would turn a
    # literal backslash followed by an n into a newline.
    $unescape = {
        param($mm)
        switch ($mm.Groups[1].Value) {
            'n' { "`n" }
            't' { "`t" }
            'r' { "`r" }
            default { $mm.Groups[1].Value }
        }
    }
    $text = ""
    foreach ($lit in [regex]::Matches($m.Groups["body"].Value, '"((?:[^"\\]|\\.)*)"')) {
        $text += [regex]::Replace($lit.Groups[1].Value, '\\(.)', $unescape)
    }
    $blitSrc = Join-Path ([System.IO.Path]::GetTempPath()) "icorecomp_blit.hlsl"
    # UTF-8 without a BOM, so the digest matches the one the Linux twin and
    # tools/check_shaders_fresh.py compute over the same characters.
    [System.IO.File]::WriteAllText($blitSrc, $text, (New-Object System.Text.UTF8Encoding $false))
    $blitDigest = Get-Sha1Hex ([System.Text.UTF8Encoding]::new($false).GetBytes($text))
    foreach ($b in @(
        @{ name = "blit.vert"; target = "vs_6_0"; entry = "main_vs"; sym = "kDxil_blit_vert" },
        @{ name = "blit.frag"; target = "ps_6_0"; entry = "main_ps"; sym = "kDxil_blit_frag" })) {
        $obj = [System.IO.Path]::GetTempFileName()
        & $dxcPath -T $b.target -E $b.entry -Zpc -O3 -Fo $obj $blitSrc
        if ($LASTEXITCODE -ne 0) { throw "dxc failed on the present blit ($($b.name))" }
        $bytes = [System.IO.File]::ReadAllBytes($obj)
        Remove-Item $obj -Force
        $inc = "$DxilDir/$($b.name).dxil.inc"
        Write-Inc -Path $inc -Symbol $b.sym -Source "src/runtime/rhi/d3d12/rhi_d3d12_shaders.cpp kBlitHlsl" -Bytes $bytes -Digest $blitDigest
        Write-Host "gen_gs_shaders_dxil: wrote $inc ($($bytes.Length) bytes, source $blitDigest)"
        $entries += @{ name = $b.name; symbol = $b.sym; inc = $inc; digest = $blitDigest }
    }
    Remove-Item $blitSrc -Force
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* rhi/rhi_shaders_dxil.h: the native GS renderer's shaders as signed DXIL.")
[void]$sb.AppendLine(" *")
[void]$sb.AppendLine(" * Generated by tools/gen_gs_shaders_dxil.ps1 on Windows. Ours (MIT). Do not")
[void]$sb.AppendLine(" * edit by hand. Rerun it after tools/gen_gs_shaders.sh.")
[void]$sb.AppendLine(" *")
[void]$sb.AppendLine(" * When this header is present the D3D12 backend uses it and never loads")
[void]$sb.AppendLine(" * dxcompiler.dll. See src/runtime/rhi/d3d12/rhi_d3d12_shaders.h.")
[void]$sb.AppendLine(" *")
[void]$sb.AppendLine(" * source_sha1 is the SHA-1 of the HLSL each container was compiled from")
[void]$sb.AppendLine(" * (for blit.vert and blit.frag, of the kBlitHlsl literal lifted out of")
[void]$sb.AppendLine(" * rhi_d3d12_shaders.cpp). tools/check_shaders_fresh.py recomputes them and")
[void]$sb.AppendLine(" * the runtime build fails when one does not match, so HLSL edited without")
[void]$sb.AppendLine(" * a regeneration cannot ship as a D3D12 backend rendering the old shader.")
[void]$sb.AppendLine(" */")
[void]$sb.AppendLine("#ifndef ICORECOMP_RHI_SHADERS_DXIL_H")
[void]$sb.AppendLine("#define ICORECOMP_RHI_SHADERS_DXIL_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#include <cstddef>")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("")
foreach ($e in $entries) {
    $rel = $e.inc -replace "^src/runtime/rhi/", "" -replace "^src/runtime/", "../"
    [void]$sb.AppendLine("#include `"$rel`"")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace rhi {")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("struct ShaderDxil {")
[void]$sb.AppendLine("    const char* name;")
[void]$sb.AppendLine("    const uint8_t* bytes;")
[void]$sb.AppendLine("    size_t size;")
[void]$sb.AppendLine("    const char* source_sha1;")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("inline const ShaderDxil* shader_dxil_table(size_t* count) {")
[void]$sb.AppendLine("    static const ShaderDxil kTable[] = {")
foreach ($e in $entries) {
    [void]$sb.AppendLine("        { `"$($e.name)`", $($e.symbol), sizeof($($e.symbol)), `"$($e.digest)`" },")
}
[void]$sb.AppendLine("    };")
[void]$sb.AppendLine("    *count = sizeof(kTable) / sizeof(kTable[0]);")
[void]$sb.AppendLine("    return kTable;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace rhi")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif /* ICORECOMP_RHI_SHADERS_DXIL_H */")
[System.IO.File]::WriteAllText($Index, $sb.ToString())
Write-Host "gen_gs_shaders_dxil: wrote $Index"
