/* rhi/rhi_shaders_dxil.h: the native GS renderer's shaders as signed DXIL.
 *
 * Generated by tools/gen_gs_shaders_dxil.sh (Linux) or
 * tools/gen_gs_shaders_dxil.ps1 (Windows). Ours (MIT). Do not edit by hand.
 * Rerun after tools/gen_gs_shaders.sh.
 *
 * When this header is present the D3D12 backend uses it and never loads
 * dxcompiler.dll. See src/runtime/rhi/d3d12/rhi_d3d12_shaders.h.
 *
 * source_sha1 is the SHA-1 of the HLSL each container was compiled from
 * (for blit.vert and blit.frag, of the kBlitHlsl literal lifted out of
 * rhi_d3d12_shaders.cpp). tools/check_shaders_fresh.py recomputes them and
 * the runtime build fails when one does not match, so HLSL edited without
 * a regeneration cannot ship as a D3D12 backend rendering the old shader.
 */
#ifndef ICORECOMP_RHI_SHADERS_DXIL_H
#define ICORECOMP_RHI_SHADERS_DXIL_H

#include <cstddef>
#include <cstdint>

#include "../gs/render/shaders/dxil/scanout.comp.dxil.inc"
#include "../gs/render/shaders/dxil/raster.comp.dxil.inc"
#include "../gs/render/shaders/dxil/shadow.comp.dxil.inc"
#include "../gs/render/shaders/dxil/overlay.vert.dxil.inc"
#include "../gs/render/shaders/dxil/overlay.frag.dxil.inc"
#include "../gs/render/shaders/dxil/blit.vert.dxil.inc"
#include "../gs/render/shaders/dxil/blit.frag.dxil.inc"

namespace rhi {

struct ShaderDxil {
    const char* name;
    const uint8_t* bytes;
    size_t size;
    const char* source_sha1;
};

inline const ShaderDxil* shader_dxil_table(size_t* count) {
    static const ShaderDxil kTable[] = {
        { "scanout.comp", kDxil_scanout_comp, sizeof(kDxil_scanout_comp), "bc56bf37f0ca1441430c6748401a272a663f9b27" },
        { "raster.comp", kDxil_raster_comp, sizeof(kDxil_raster_comp), "ae00b4a0cbb8905fe0e379fb6339d22f857d1873" },
        { "shadow.comp", kDxil_shadow_comp, sizeof(kDxil_shadow_comp), "a94de8702218cb89fcffd24ce8ab80225013057d" },
        { "overlay.vert", kDxil_overlay_vert, sizeof(kDxil_overlay_vert), "56a8db5e92290e673cf0173766179cdfc061f9aa" },
        { "overlay.frag", kDxil_overlay_frag, sizeof(kDxil_overlay_frag), "c617f692b94f40e6a826f1a8805b8e164d29839b" },
        { "blit.vert", kDxil_blit_vert, sizeof(kDxil_blit_vert), "49d68a1ad9307b1d8f365fd87accaf9df0a72c9f" },
        { "blit.frag", kDxil_blit_frag, sizeof(kDxil_blit_frag), "49d68a1ad9307b1d8f365fd87accaf9df0a72c9f" },
    };
    *count = sizeof(kTable) / sizeof(kTable[0]);
    return kTable;
}

} // namespace rhi

#endif /* ICORECOMP_RHI_SHADERS_DXIL_H */
