/* rhi/rhi_shaders.h: the native GS renderer's compiled shaders.
 *
 * Generated by tools/gen_gs_shaders.sh from src/runtime/gs/render/shaders.
 * Ours (MIT). Do not edit by hand.
 *
 * Each entry is a pointer and a word count, which is what
 * rhi::Device::create_compute_pipeline and create_graphics_pipeline take.
 */
#ifndef ICORECOMP_RHI_SHADERS_H
#define ICORECOMP_RHI_SHADERS_H

#include <cstddef>
#include <cstdint>

#include "../gs/render/shaders/scanout.comp.spv.inc"
#include "../gs/render/shaders/raster.comp.spv.inc"
#include "../gs/render/shaders/shadow.comp.spv.inc"
#include "../gs/render/shaders/overlay.vert.spv.inc"
#include "../gs/render/shaders/overlay.frag.spv.inc"

namespace rhi {

struct ShaderBlob {
    const uint32_t* words;
    size_t word_count;
};

inline ShaderBlob shader_scanout_comp() { return ShaderBlob{ kScanoutCompSpv, sizeof(kScanoutCompSpv) / sizeof(uint32_t) }; }
inline ShaderBlob shader_raster_comp() { return ShaderBlob{ kRasterCompSpv, sizeof(kRasterCompSpv) / sizeof(uint32_t) }; }
inline ShaderBlob shader_shadow_comp() { return ShaderBlob{ kShadowCompSpv, sizeof(kShadowCompSpv) / sizeof(uint32_t) }; }
inline ShaderBlob shader_overlay_vert() { return ShaderBlob{ kOverlayVertSpv, sizeof(kOverlayVertSpv) / sizeof(uint32_t) }; }
inline ShaderBlob shader_overlay_frag() { return ShaderBlob{ kOverlayFragSpv, sizeof(kOverlayFragSpv) / sizeof(uint32_t) }; }

/* The name of each blob, keyed by its SPIR-V words.
 *
 * The D3D12 and Metal backends identify a shader by comparing the
 * blob they were handed against these arrays word for word, never by
 * address: the arrays are static in a header, so every translation
 * unit holds its own copy at its own address, and the first D3D12 run
 * failed on exactly that. The table is generated from the
 * same list the arrays, the HLSL index and the MSL index come from,
 * so a shader added to the generator reaches all three in one run.
 * Each backend used to keep its own copy of this table by hand, and
 * both copies were missing shadow.comp, which made those backends
 * fatal at renderer construction.
 */
struct ShaderName {
    const uint32_t* spirv;
    size_t words;
    const char* name;
};

inline const ShaderName* shader_name_table(size_t* count) {
    static const ShaderName kTable[] = {
        { kScanoutCompSpv, sizeof(kScanoutCompSpv) / sizeof(uint32_t), "scanout.comp" },
        { kRasterCompSpv, sizeof(kRasterCompSpv) / sizeof(uint32_t), "raster.comp" },
        { kShadowCompSpv, sizeof(kShadowCompSpv) / sizeof(uint32_t), "shadow.comp" },
        { kOverlayVertSpv, sizeof(kOverlayVertSpv) / sizeof(uint32_t), "overlay.vert" },
        { kOverlayFragSpv, sizeof(kOverlayFragSpv) / sizeof(uint32_t), "overlay.frag" },
    };
    *count = sizeof(kTable) / sizeof(kTable[0]);
    return kTable;
}

/* The SHA-1 of every source this run compiled from: each GLSL shader
 * and the three C++ headers the compute shaders #include verbatim.
 *
 * Nothing at run time reads these. They exist so that
 * tools/check_shaders_fresh.py can recompute them and fail the build
 * when a source has moved on without the generator being rerun. The
 * SPIR-V here, the HLSL in rhi_shaders_hlsl.h and the MSL in
 * rhi_shaders_msl.h are all written by one run of the generator, so
 * one digest per source covers all three: an edit with no
 * regeneration leaves every one of them stale and mutually
 * consistent, which is the state nothing else in the tree can see.
 * rhi_shaders_dxil.h carries its own digests of the HLSL, which is
 * the next link in the same chain; the checker verifies both.
 */
struct ShaderSourceDigest {
    const char* path; /* relative to the repository root */
    const char* sha1;
};

inline const ShaderSourceDigest* shader_source_digests(size_t* count) {
    static const ShaderSourceDigest kTable[] = {
        { "src/runtime/gs/render/shaders/scanout.comp", "71e3e7b50ed230c72f0c74b56aa0d9305b5f0b86" },
        { "src/runtime/gs/render/shaders/raster.comp", "f9a3fe8a1199c8b7fe3acef071f44557e2c53eee" },
        { "src/runtime/gs/render/shaders/shadow.comp", "c00856fa566cc1b3a767a7172d0355f1ba996332" },
        { "src/runtime/gs/render/shaders/overlay.vert", "1548dcb3238bb54f3a9c1722b3a012f248319c53" },
        { "src/runtime/gs/render/shaders/overlay.frag", "e238f8dda411893ddfa51ef43ea830d3a1c02e98" },
        { "src/runtime/gs/render/gs_swizzle.h", "f3886bae68744c40537de6e0d56f7d90eef09fc6" },
        { "src/runtime/gs/render/gs_prim.h", "7e06ba20286f559e1a4fbe1f1b8868ebb01a930e" },
        { "src/runtime/gs/render/gs_texture.h", "d01ba387e55895666741cd6773d191ca48259317" },
    };
    *count = sizeof(kTable) / sizeof(kTable[0]);
    return kTable;
}

} // namespace rhi

#endif /* ICORECOMP_RHI_SHADERS_H */
